<?php $this->plugin('translate')->setTranslatorTextDomain('adfabflow'); ?>
<?php
$fm = $this->flashMessenger()->setNamespace('adfabflow')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}
?>
<?php $addLink = $this->url('zfcadmin/adfabflow/action/create', array('actionId' => 0)); ?>

<ul class="liste-buttons">
	<li class="btn-admin"><a href="<?php echo $addLink;?>"><?php echo $this->translate('Add new action'); ?></a></li>
</ul>

<h1>Liste des actions</h1>

<table class="table">
    <tr>
        <th><?php echo $this->translate('Code'); ?></th>
        <th><?php echo $this->translate('Label'); ?></th>
        <th><?php echo $this->translate('Definition'); ?></th>
        <th></th>
    </tr>
    <?php foreach ($this->actions as $action): ?>
    	<?php $editLink = $this->url('zfcadmin/adfabflow/action/edit', array('actionId' => $action->getId()));?>
    	<?php $deleteLink = $this->url('zfcadmin/adfabflow/action/remove', array('actionId' => $action->getId()));?>
    	
        <tr>
            <td><?php echo $action->getCode() ?></td>
            <td><?php echo $action->getLabel() ?></td>
            <td><?php echo $action->getDefinition() ?></td>
            <td>
                <a href='<?php echo $editLink ?>'><?php echo $this->translate('Edit'); ?></a> | <a href='<?php echo $deleteLink ?>'><?php echo $this->translate('Delete'); ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php echo $this->paginationControl($this->actions, 'Sliding', 'adfab-flow/admin/action/pagination_actionlist'); ?>
