<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<div class="return"><a href="<?php echo $this->url('admin/playgroundflow/widget');?>"><?php echo $this->translate('Retour'); ?></a></div>

<h1><?php echo $this->translate('Validate'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div id="content">
        <div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('title')); ?>
	            <?php echo $this->formInput($form->get('title')); ?>
	            <?php echo $this->formElementErrors($form->get('title')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('anchor')); ?>
	            <?php echo $this->formInput($form->get('anchor')); ?>
	            <?php echo $this->formElementErrors($form->get('anchor')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('template')); ?>
	            <?php echo $this->formTextarea($form->get('template')); ?>
	            <?php echo $this->formElementErrors($form->get('template')) ?>
	            <?php $this->QgCKEditor(
                    'template',
                        array(
                            'BasePath' => $this->libAssetPath('js/ckeditor'),
                            'Width' => "100%",
                            'Height' => "340",
                            'filebrowserBrowseUrl' => '/elfinder', // eg. 'includes/elFinder/elfinder.html'
                            'uiColor' => '#9AB8F3',
                            //'Color' => "#000",
                            'Toolbar'=> array(
                                 array('Source','Maximize'),
                                 array('Templates','Styles','Format'),
                                 array('Bold','Italic','Underline','Subscript','Superscript'),
                                 array('NumberedList','BulletedList','Outdent','Indent'),
                                 array('JustifyLeft','JustifyCenter','JustifyRight'),
                                 array('Link','Unlink'),
                                 array('Image','Table')
                             )
                        )
                    );
                ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('jsFile')); ?>
	            <?php echo $this->formInput($form->get('jsFile')); ?>
	            <?php echo $this->formElementErrors($form->get('jsFile')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('cssFile')); ?>
	            <?php echo $this->formInput($form->get('cssFile')); ?>
	            <?php echo $this->formElementErrors($form->get('cssFile')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('timeout')); ?>
	            <?php echo $this->formInput($form->get('timeout')); ?>
	            <?php echo $this->formElementErrors($form->get('timeout')) ?>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>