<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow'); ?>
<?php
$fm = $this->flashMessenger()->setNamespace('playgroundflow')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}
?>
<?php $addLink = $this->url('admin/playgroundflow/story/create', array('storyId' => 0)); ?>

<a class="btn btn-default right" href="<?php echo $addLink;?>"><?php echo $this->translate('Add new story'); ?></a>

<h1>Liste des stories</h1>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th><?php echo $this->translate('Code'); ?></th>
            <th><?php echo $this->translate('Label'); ?></th>
            <th><?php echo $this->translate('Action'); ?></th>
            <th><?php echo $this->translate('Object'); ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->stories as $story): ?>
    	<?php $editLink = $this->url('admin/playgroundflow/story/edit', array('storyId' => $story->getId()));?>
    	<?php $deleteLink = $this->url('admin/playgroundflow/story/remove', array('storyId' => $story->getId()));?>
    	<?php $optionLink = '';//$this->url('admin/playgroundflow/story/attribute', array('storyId' => $story->getId())); ?>
        <tr>
            <td><?php echo $story->getCode() ?></td>
            <td><?php echo $story->getLabel() ?></td>
            <td><?php echo $story->getAction()->getLabel() ?></td>
            <td><?php foreach($story->getObjects() as $object):?>
                    <?php echo $object->getCode();?>
                    (
                    <?php foreach($object->getAttributes() as $attribute):?>
                        <?php echo $attribute->getCode() . ',';?>
                    <?php endforeach;?>
                    )<br/>
                <?php endforeach;?>
            </td>
            <td>
                <a href='<?php echo $editLink ?>'><?php echo $this->translate('Edit'); ?></a> | <a href='<?php echo $deleteLink ?>'><?php echo $this->translate('Delete'); ?></a><?php if($optionLink != ''):?> | <a href='<?php echo $optionLink ?>'><?php echo $this->translate('Add options'); ?></a><?php endif;?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->stories, 'Sliding', 'playground-flow/admin/story/pagination_storylist'); ?>
