<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();

//$form->setAttribute('action', $this->url('admin/playgroundgame/quiz-question-add', array('quizId' => $this->quiz_id, 'questionId' => $this->question_id)));
?>

<h1><?php echo $this->translate('Associate Game'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formButton($form->get('submit')->setLabel($this->translate('Validate'))); ?>
<div id="dz-root"></div>
<div id="content" class="tabbable tabs-left">
    <div id="my-tab-content" class="tab-content">

        <div id="conditions">
            <ul class="liste-buttons">
                <li class="btn-admin"><a href="#" onclick="add_game()"><?php echo $this->translate('Add a game'); ?></a></li>
            </ul>

            <div id="conditions_entry" class="control-group">
            <?php echo $this->formCollection($form->get('missionGameCondition'));?>
            </div>

            <ul class="liste-buttons">
                <li class="btn-admin"><a href="#" onclick="add_game()"><?php echo $this->translate('Add a game'); ?></a></li>
            </ul>
        </div>
    </div>
</div>
<input type="hidden" id="countGame" value="0" name="countGame"/>
<?php echo $this->form()->closeTag() ?>

<script>

    var template = $('#conditions_entry > fieldset > span');
    var datatemplate = $('#conditions_entry > fieldset > span').data('template');
    template.data('template', '<fieldset id="answers__index__">'+datatemplate+'</fieldset>');

    function add_game() {
        var currentCount = $('#conditions_entry input').length / 2;
        $('#countGame').attr({value : currentCount});
        var template = $('#conditions_entry > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);
        $('#conditions_entry').append(template);
        $('#conditions_entry').append('<hr/>');

        return false;
    }
</script>

<?php $i=0; foreach($this->missionGames as $missionGame) : ?>
    <script>
        add_game();
        $('select[name=<?php echo "games".$i?>] option[value=<?php echo $missionGame["games"]; ?>]').attr("selected", "selected");
        $('select[name=<?php echo "conditions".$i?>] option[value=<?php echo $missionGame["conditions"]; ?>]').attr("selected", "selected");
        $('input[name=<?php echo "points".$i?>]').attr("value", '<?php echo $missionGame["points"] ; ?>'); 
        $('button[name=<?php echo "delete".$i?>]').click(function(){
            $('#answers<?php echo $i?>').html('');
        });
    </script>
   
<?php $i++;endforeach; ?>