<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundGame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form) 
?>
<div class="row-fluid show-grid">
    <div class="span8">
        <?php echo $this->formHidden($form->get('id')); ?>

        <div class="control-group">
            <?php echo $this->formLabel($form->get('title')); ?>
            <?php echo $this->formInput($form->get('title')); ?>
            <?php echo $this->formElementErrors($form->get('title')) ?>
        </div>

         <div class="control-group">
                <?php echo $this->formLabel($form->get('description')); ?>
                <div class="controls">
                    <?php echo $this->formTextarea($form->get('description')); ?>
                    <?php echo $this->formElementErrors($form->get('description')) ?>
                </div>
            <?php $this->QgCKEditor(
                'description',
                    array(
                        'BasePath' => $this->libAssetPath('js/ckeditor'),
                        'Width' => "450",
                        'Height' => "100",
                        //'Color' => "#000",
                        'Toolbar'=> array(
                             array('Bold','Italic','Underline','Link','Unlink'),
                         )
                    )
                );
            ?>
        </div>

        <div class="control-group">
            <?php echo $this->formLabel($form->get('hidden')); ?>
            <div class="controls"><?php echo $this->formCheckbox($form->get('hidden')); ?></div>
            <?php echo $this->formElementErrors($form->get('hidden')); ?>
        </div>
    </div>

    <div class="span4">
        <div class="thumbnail">
            <?php if($form->get('image')->getValue() != ''):?>
            <?php echo $this->formLabel($form->get('uploadImage')); ?>
            <img  data-src="holder.js/300x200" style="width: 300px; height: 200px;"src="<?php echo $this->basePath($form->get('image')->getValue()); ?>" />
            <?php endif;?>
            <div class="caption">
               <?php echo $this->formFile($form->get('uploadImage')); ?>
            </div>
        </div>
    </div>
    <div class="span8">
    <ul class="liste-buttons">
		<li class="btn-admin"><a href="#" onclick="add_game()"><?php echo $this->translate('Add a game'); ?></a></li>
	</ul>

    <div id="game_entry" class="control-group">
    <?php echo $this->formCollection($form->get('missionGames'));?>
    </div>

    <ul class="liste-buttons">
		<li class="btn-admin"><a href="#" onclick="add_game()"><?php echo $this->translate('Add a game'); ?></a></li>
	</ul>
    </div>
</div>
<div class="row-fluid show-grid">
    <div class="span12">
        <?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
        <?php echo $this->formButton($form->get('submit')) ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>

<script>

    var template = $('#game_entry > fieldset > span');
    var datatemplate = $('#game_entry > fieldset > span').data('template');
    template.data('template', '<fieldset id="games__index__">'+datatemplate+'</fieldset>');

    function add_game() {
        var currentCount = $('#game_entry select').length;
        var template = $('#game_entry > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);
        $('#game_entry').append(template);
        $('#game_entry').append('<hr/>');
        
        $('#position'+currentCount).val(currentCount);

        return false;
    }

    $( '#game_entry' ).on('click', '.addCondition', function() {

            var currentCount = $( this ).parent().children("fieldset").children("input").length;
            var template = $( this ).parent().children("fieldset").children("span").data('template');
            template = template.replace(/__index__/g, currentCount);
            $( this ).parent().children("fieldset").append(template);

            return false;
      });

    /*$('#game_entry button').live('click',function(){
    	$(this).parent().parent().empty();
    	return false;
    });*/
</script>