<!-- HOW DOES IT WORK -->
<div id="how-does-it-work">
	<div class="row-fluid">
				
		<h1>Comment ça marche ?</h1>
				
		<!-- play-win-gifts -->
		<div id="play-win-gifts" class="content-block arrow-double-green">
			<h2>Jouez et gagnez plein de cadeaux</h2>
			<p>Playground vous propose des jeux concours gratuits pour tenter de gagner pleins de cadeaux ! > <a href="<?php echo $this->url('frontend/jeuxconcours') ?>" class="green">Voir tous les jeux en cours</a></p>
			<img src="<?php echo $this->frontendAssetPath('images/content/how-does-it-work/play-and-win-gifts.png')?>" border="0" width="617" height="374" alt="Jouez et gagnez plein de cadeaux" />
		</div><!-- END #play-win-gifts -->
		
		<div id="get-badges" class="content-block">
			<h2>Obtenez des badges!</h2>
			<p>Vos actions (jouer, partager...) vous permettent de cumuler des badges exclusifs!</p>
			<img src="<?php echo $this->frontendAssetPath('images/content/how-does-it-work/get-badges.png')?>" border="0" width="511" height="186" alt="Obtenez des badges!" />
		</div><!-- END #get-badges -->
		
		<div id="earn-max-points" class="content-block">
			<h2>Cumulez le max de points!</h2>
			<p>Chacune de vos actions vous rapporte également des points, faites-en le maximum pour remonter dans le classement ! </p>
			<img src="<?php echo $this->frontendAssetPath('images/content/how-does-it-work/earn-max-points.png')?>" border="0" width="273" height="246" alt="Cumulez le max de points!" />
		</div><!-- END #earn-max-points -->

	</div><!-- END .row-fluid -->
</div><!-- END HOW DOES IT WORK -->