<?php $this->plugin('translate')->setTranslatorTextDomain('application');// Pour le texte ?>

<!-- CONTACT-US -->
<div id="contact-us" class="row-fluid">
				
	<h1>Contactez-nous</h1>
	<h2>Une question à nous poser ?</h2>

	<?php $form = $this->form;?>
    <?php $form->prepare();?>
    <?php $form->setAttribute('action', $this->url('frontend/contact')); ?>
    <?php $form->setAttribute('class', 'validate');?>
	<?php echo $this->form()->openTag($form); ?>
	
	<div id="contact-inner" class="backgrey row-fluid">
		<div class="row-fluid">
			<div class="block-left span4"><?php echo $this->formLabel($form->get('lastname')); ?> <span>*</span> :</div>
			<div class="block-right span7">
				<?php echo $this->formInput($form->get('lastname')); ?>
				<?php echo $this->formElementErrors($form->get('lastname')) ?>
			</div>
		</div>
		<div class="row-fluid">
			<div class="block-left span4"><?php echo $this->formLabel($form->get('firstname')); ?> <span>*</span> :</div>
			<div class="block-right span7">
				<?php echo $this->formInput($form->get('firstname')); ?>
				<?php echo $this->formElementErrors($form->get('firstname')) ?>
			</div>
		</div>
		<div class="row-fluid">
			<div class="block-left span4"><?php echo $this->formLabel($form->get('email')); ?> <span>*</span> :</div>
			<div class="block-right span7">
				<?php echo $this->formInput($form->get('email')); ?>
				<?php echo $this->formElementErrors($form->get('email')) ?>			
			</div>
		</div>
		<div class="row-fluid">
			<div class="block-left span4"><?php echo $this->formLabel($form->get('object')); ?> <span>*</span> :</div>
			<div class="block-right span7 mobile contact-select">
				<?php echo $this->formSelect($form->get('object')) ?>
				<?php echo $this->formElementErrors($form->get('object')) ?>
			</div>
		</div>
		<div class="row-fluid">
			<div class="block-left span4"><?php echo $this->formLabel($form->get('message')); ?> <span>*</span> :</div>
			 <div class="block-right span7 contact-textarea">
             	<?php echo $this->formTextarea($form->get('message')) ?>
             	<?php echo $this->formElementErrors($form->get('message')) ?>
             </div>	
        </div>
		<div id="btn-send" class="row-fluid">
			<div class="span3 center">
				<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
				<?php echo $this->formButton($form->get('submit')) ?>
			</div>
		</div>
	</div>
	
	<?php echo $this->form()->closeTag() ?>
	
	<p id="annotation"><?php echo $this->translate('* champs obligatoires')?></p>

</div>