<?php $this->plugin('translate')->setTranslatorTextDomain('application');// Pour le texte ?>

<!-- CONTACT-US -->
<div id="contact-us" class="row-fluid">

	<h1>Contactez-nous</h1>
	<h2>Une question à nous poser ?</h2>

	<div id="contact-inner" class="backgrey row-fluid">
		<div class="message-confirm">
			<p>Votre demande a bien été envoyée, nous la traiterons dans les plus brefs délais.</p>
			<p>Merci.</p>
			<p>L'équipe Playground</p>
		</div>
		<div id="btn-send" class="row-fluid">
			<div class="span3 center">
				<a href="<?php echo $this->url('home');?>" class="btn btn-success">continuer</a>
			</div>
		</div>
	</div>

</div>