<?php $this->plugin('translate')->setTranslatorTextDomain('adfabgame');// Pour le texte ?>

<!-- THEMATIQUES -->
<div id="jeux-concours" class="thematique">
    <div class="row-fluid">
        <h1><?php echo $this->prizecategoryname;?></h1>
    </div>

    <?php $this->partialLoop()->setObjectKey('game')?>
    <?php echo $this->partialLoop('adfab-game/frontend/partial/game.phtml', $this->games) ?>
</div><!-- END THEMATIQUES -->