<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<!-- NEWSLETTER -->
<div id="newsletter" class="row">
	<?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('frontend/zfcuser/newsletter', array('channel' => $this->channel)));
    $form->setAttribute('method', 'post');
    ?>
    <h1>
        Newsletter
    </h1>
	<!-- create account -->
	<div class="choose row">
		<!-- start form -->
        <?php echo $this->form()->openTag($form) ?>				
			<!-- opt-in -->
			<div class="row opt-in">
				<b class="col-md-12">
				    <?php echo $this->translate('Inscrivez-vous aux newsletters pour ne rater aucun jeu et être informé de tous nos bons plans :')?>
				</b>
				<?php if(($this->zfcUserIdentity() && ! $this->zfcUserIdentity()->getOptin()) || ($this->zfcUserIdentity() && ! $this->zfcUserIdentity()->getOptinPartner())): ?>
				<p class="col-md-12">
				    <b>
				        Gagnez 150 points par inscription !
				    </b>
				</p>
				<?php endif ?>
				<div class="col-md-7">
					<p>
					    <?php echo $this->translate('Je souhaite recevoir la newsletter Playground')?>
					    <br/>
					   <?php echo $this->translate('(nouveaux jeux-concours, bons plans, invitations VIP...)')?>
					</p>
				</div>
				<div class="col-md-3">
					<?php echo $this->formRadio($form->get('optin')) ?>
					<?php echo $this->formElementErrors($form->get('optin')) ?>
				</div>
				<div class="col-md-2">
					<?php if($this->zfcUserIdentity() && ! $this->zfcUserIdentity()->getOptin()) : ?>
    					<p>
    					    + 150 pts
    					</p>
					<?php endif; ?>
				</div>
			</div>
			<div class="row opt-in">
				<div class="col-md-7">
					<p>
					    <?php echo $this->translate('Je souhaite recevoir les offres des partenaires de Playground')?>
					   <?php echo $this->translate('(réductions, bons plans...)')?>
					</p>
				</div>
				<div class="col-md-3">
					<?php echo $this->formRadio($form->get('optinPartner')) ?>
					<?php echo $this->formElementErrors($form->get('optinPartner')) ?>
				</div>
				<div class="col-md-2">
					<?php if($this->zfcUserIdentity() && ! $this->zfcUserIdentity()->getOptinPartner()): ?>
					<p>
					    + 150 pts
					</p>
					<?php endif; ?>
				</div>
			</div>
			<div id="btn-create-account" class="row col-md-2">
				<?php echo $this->formButton($form->get('submit')) ?>
			</div>
        <?php echo $this->form()->closeTag() ?>
		<!-- end form -->			
	</div>	
</div>
<!-- END NEWSLETTER -->