<div id="sidebar-user" class="col-md-4 sidebar">
	<?php if($this->zfcUserIdentity()): ?>
        <?php $rank =  $this->rankWidget($this->zfcUserIdentity()->getId()); ?>
		<div id="user" class="row">
			<div class="col-md-6 avatar"
			    data-noavatarf="<?php echo $this->frontendAssetPath('images/user/no-avatar-f.png') ?>"
			    data-noavatarh="<?php echo $this->frontendAssetPath('images/user/no-avatar-h.png') ?>" >
			    <?php if($this->zfcUserIdentity()->getAvatar()):?>
			        <img src="<?php echo $this->basePath($this->zfcUserIdentity()->getAvatar()) ?>" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" />
			    <?php else:?>
			    	<?php if($this->zfcUserIdentity()->getTitle() && $this->zfcUserIdentity()->getTitle() == 'M'): ?>
			        	<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-h.png') ?>" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" />
			    	<?php else: ?>
			        	<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-f.png') ?>" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" />
			    	<?php endif; ?>
			    <?php endif;?>
            </div>
			<div class="col-md-6">
				<p id="username">
					<?php
					if ($this->zfcUserIdentity()->getUsername() != '') echo $this->zfcUserIdentity()->getUsername();
					else echo $this->zfcUserIdentity()->getFirstname().' '.$this->zfcUserIdentity()->getLastname();
					?>
				</p>
            </div>
            <div class="col-md-12 clearfix btn-wrapper">
                <a class="btn btn-default" href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel)) ?>#avatarfile">
                    Changer votre photo de profil
                </a>
            </div>
		</div>
		<div id="point" class="row sb-block">
			<div class="col-md-12 icon-reward">
				<img src="<?php echo $this->frontendAssetPath('images/common/icon-cup.png') ?>" alt="" />
			</div>
			<div class="col-md-12">
				<p>
					<span id="mypoints">
					    Vous avez<br/>
					    <span>
					        <?php echo number_format($rank['points'], 0, ',', ' ' ); ?> points
					    </span>
					</span>
					<br/>
					<span class="small">
					    <?php echo $rank['rank'];?>
					    <sup>
					        <?php echo ($rank['rank'] == 1)? 'ère' : 'ème'; ?>
					    </sup> 
					    position
					</span>
					<br/>
					<a href="<?php echo $this->url('frontend/reward/leaderboard', array('period'=>'general','channel' => $this->channel)) ?>">
					    Voir le classement
					</a>
				</p>
			</div>
			<p id="more-points" class="col-md-12">
			    <a class="btn btn-default" href="<?php echo $this->url('frontend/cms', array('id' => 'comment-ca-marche','channel' => $this->channel)); ?>">
			        Comment gagner plus de points ?
			    </a>
			</p>
		</div>
		<div id="gerer" class="sb-block" >
			<p>
			    Gérer votre compte
			</p>
			<ul>
				<li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-money-black.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel)) ?>">
					    Mes badges et mes points
					</a>
				</li>
				<li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-calendar-black.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/activity', array('channel' => $this->channel)) ?>">
					    Mon activité
					</a>
				</li>
				<li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-cog-black.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel)) ?>">
					    Modifier mes informations
					</a>
				</li>
				<li>
					<img class="icon-news" src="<?php echo $this->frontendAssetPath('images/header/icon-news.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/zfcuser/newsletter', array('channel' => $this->channel)) ?>">
					    Gérer mes newletters
					</a>
				</li>
				<li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-users-black.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/sponsorfriends', array('channel' => $this->channel)) ?>">
					    Parrainer mes amis
					</a>
				</li>
			</ul>
		</div>
		<div id="howto" class="sb-block">
			<p>
			    <?php echo $this->translate('How it works ?'); ?>
			</p>
			<ul>
				<li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-money-black.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/cms', array('id' => 'comment-ca-marche', 'channel' => $this->channel)); ?>">
					    <?php echo $this->translate('Badges and points'); ?>
					</a>
				</li>
				<li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-calendar-black.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/faq', array('channel' => $this->channel)) ?>">
					    <?php echo $this->translate('F.A.Q'); ?>
					</a>
				</li>
				<li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-contact-black.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/contact', array('channel' => $this->channel)) ?>">
					    <?php echo $this->translate('Contact us'); ?>
					</a>
				</li>
			</ul>
		</div>
		<div id="deco" class="sb-block">
			<ul>
				<li>
					<a class="btn btn-default" href="<?php echo $this->url('frontend/zfcuser/logout', array('channel' => $this->channel)) ?>">
					    Déconnexion
					</a>
				</li>
			</ul>
		</div>
	<?php else:?>
		<div id="howto" class="sb-block">
			<p class="green green-star">
			    <?php echo $this->translate('How it works ?'); ?>
			</p>
			<ul>
				<li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-money-black.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/cms', array('id' => 'comment-ca-marche', 'channel' => $this->channel)); ?>">
					    <?php echo $this->translate('Badges and points'); ?>
					</a>
				</li>
				<li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-calendar-black.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/faq', array('channel' => $this->channel)) ?>">
					    <?php echo $this->translate('F.A.Q'); ?>
					</a>
				</li>
				<!-- <li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-cog-black.png') ?>" alt="" />
					<a href="">La boutique</a>
				</li> -->
				<li>
					<img src="<?php echo $this->frontendAssetPath('images/user/icon-contact-black.png') ?>" alt="" />
					<a href="<?php echo $this->url('frontend/contact', array('channel' => $this->channel)) ?>">
					    <?php echo $this->translate('Contact us'); ?>
					</a>
				</li>
			</ul>
		</div>
		<div id="deco" class="sb-block">
			<ul>
				<li>
					<a class="btn btn-default" href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Se connecter / Créer un compte</a>
				</li>
			</ul>
		</div>
	<?php endif;?>
</div>