<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<div class="game-lottery row-fluid welcome">
	<h1><?php echo $this->game->getTitle(); ?></h1>

	<!-- BLOCK GAME START -->
    <?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game, 'channel' => $this->channel));?>
    <!-- END BLOCK GAME START -->

	<!-- contenu article -->
	<div id="content-article" class="row-fluid rounded backgrey">
		<div class="welcome-block<?php if($this->layout()->facebooktemplate): echo ' fb-target'; endif ?>"><?php echo $this->game->getWelcomeBlock(); ?></div>
		<?php if($game->isStarted()):?>
		<div class="center">
			<div class="btn btn-default">
				<a href="<?php echo $this->url('frontend/treasurehunt/play', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" class="arrow-right">Participer</a>
			</div>
		</div>
		<?php endif;?>
	</div>
	<p id="reglement"><a href="<?php echo $this->url('frontend/treasurehunt/terms', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" target="_blank">Règlement</a></p>
</div>