<?php
$this->plugin('translate')->setTranslatorTextDomain('playgroundgame');
$playLimitScale = $game->getPlayLimitScale();
$playLimitValue = '';
if ($playLimitScale == 'day') : $playLimitValue = $this->translate('every day');
elseif ($playLimitScale == 'week') : $playLimitValue = $this->translate('every week');
elseif ($playLimitScale == 'month') : $playLimitValue = $this->translate('every month');
elseif ($playLimitScale == 'year') : $playLimitValue = $this->translate('every year');
else : $playLimitValue = $this->translate('everytime');
endif;
?>
<div class="game-instantwin row">
	
	<?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game, 'channel' => $this->channel));?>

    <div class="block-game game-play <?php if ($this->basePath($this->game->getMainImage()) == "") echo "no-image"; ?>">
        <div class="star-center"></div>
        <div class="img-content">
            <img class="rounded" src="<?php echo $this->basePath($this->game->getMainImage()); ?>" />
        </div>
        <div class="game-infos">
            <div class="win part">
                <div class="question">Votre ticket est <strong>gagnant</strong> ?</div>
                <div class="choice">Découvrez vite votre gain !</div>
            </div>
            <div class="lose part">
                <div class="question">Votre ticket est <strong>perdant</strong> ?</div>
                <div class="choice">Nous vous offrons une 2<sup>ème</sup> chance</div>
            </div>
        </div>
        <?php if ($this->game->getOccurrenceType()=='code'): ?>
            <?php $form->prepare(); ?>
            <?php $form->setAttributes(array('class' => 'form-number')); ?>
            <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formInput($form->get('code-input')->setAttributes(array('placeholder' =>$this->translate('Saisissez votre code...')))); ?>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            <?php echo $this->form()->closeTag($form); ?>
        <?php endif; ?>
        <?php
        if (isset($this->flashMessages)){
            foreach ($this->flashMessages as $fm){
                echo '<div class="flash-msg"><span>' . $fm . '</span></div>';
            }
        }
        ?>
        <div class="error-msg"><span class="no-value">Vous devez entrer un code avant de valider !</span></div>
        <p class="desc">Et découvrez votre expérience...</p>
    </div>
    
    <?php if ($this->game->getOccurrenceType()=='datetime'): ?>
        <div id="result-instantwin">
            <?php if($this->winner):?>
                <div class="row win">
                    <div class="col-md-1">
                        <img src="<?php echo $this->frontendAssetPath('images/common/round-valid.png')?>" alt="" />
                    </div>
                    <div class="col-md-11">
                        <p id="valid-text">
                            <?php echo $this->translate('Félicitations, vous avez gagné !'); ?>
                        </p>
                    </div>
                </div>
                <!-- contenu form address -->
                <?php if ($this->form_address) : ?>
                     <?php echo $this->form_address ?>
                <?php endif;?>
            <?php else:?>
                <div class="row win">
                    <div class="col-md-1">
                        <img src="<?php echo $this->frontendAssetPath('images/common/round-wrong.png')?>" alt="" />
                    </div>
                    <div class="col-md-11">
                        <p id="valid-text">
                            <?php echo $this->translate('Retentez votre chance dès demain!'); ?>
                        </p>
                    </div>
                </div>
            <?php endif;?>
        </div>
        
        <div id="play-instantwin">
            <p class="instructions">
                <?php echo $this->translate('Scratch'); ?>
                <?php echo $playLimitValue; ?> <?php echo $this->translate('and find out immediately if you won'); ?> :
            </p>
            <!-- BLOCK GAME START -->
            <div class="block-game game-play">
                <div class="game-infos">
                    <?php if ($this->game->getStartDate() && $this->game->getEndDate()):?>
                        <div class="instantwin">
                            <?php echo $this->translate('instantwin'); ?> : <?php echo $this->translate('Play'); ?> <?php echo $this->translate('from'); ?> <?php echo strftime("%d %B", $this->game->getStartDate()->format('U'));?> <?php echo $this->translate('to'); ?>
                            <?php echo strftime("%d %B", $this->game->getEndDate()->format('U'));?> <?php echo $this->translate('with'); ?>
                        </div>
                    <?php elseif ($this->game->getStartDate()):?>
                        <div class="instantwin">
                            <?php echo $this->translate('instantwin'); ?> : <?php echo $this->translate('Play'); ?> <?php echo $this->translate('after'); ?> <?php echo strftime("%d %B", $this->game->getStartDate()->format('U'));?> <?php echo $this->translate('with'); ?>
                        </div>
                    <?php elseif ($this->game->getEndDate()):?>
                        <div class="instantwin">
                            <?php echo $this->translate('instantwin'); ?> : <?php echo $this->translate('Play'); ?> <?php echo $this->translate('up to'); ?> <?php echo strftime("%d %B", $this->game->getEndDate()->format('U'));?> <?php echo $this->translate('with'); ?>
                        </div>
                    <?php else:?>
                        <div class="instantwin">
                            <?php echo $this->translate('instantwin'); ?> : <?php echo $this->translate('Play'); ?> <?php echo $this->translate('with'); ?>
                        </div>
                    <?php endif; ?>
                    <div class="logo-partner">
                        <?php if($this->game->getPartner()):?>
                            <?php if( ($this->game->getPartner()->getLogo() != '') || ($this->game->getPartner()->getSmallLogo() !='')) : ?>
                                <img
                                    src="<?php if($this->game->getPartner()->getSmallLogo() !='') : echo $this->basePath($this->game->getPartner()->getSmallLogo());
                                                else : echo $this->basePath($this->game->getPartner()->getLogo()); endif;?>"
                                    alt="<?php echo $this->game->getPartner()->getName();?>" />
                            <?php else:?>
                                <span>
                                    <?php echo $this->game->getPartner()->getName();?>
                                </span>
                            <?php endif;?>
                        <?php else :?>
                            <img src="<?php echo $this->frontendAssetPath('images/common/logo-game-start.png');?>" alt="Logo" />
                        <?php endif;?>
                    </div>
                </div>
                <div class="img-content">
                    <img class="rounded" src="<?php echo $this->basePath($this->game->getScratchcardImage()); ?>" />
                    <div id="wScratchgame" data-percentscratched="" data-scratchover='<?php echo $this->frontendAssetPath('images/games/scratch-over.png')?>'
                        <?php if($this->winner):?>
                            data-scratchthis="<?php echo $this->frontendAssetPath('images/games/scratch-win.png')?>" >
                        <?php else:?>
                        data-scratchthis="<?php echo $this->frontendAssetPath('images/games/scratch-loose.png')?>" >
                        <?php endif;?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
	
	<?php echo $this->partial('playground-game/partial/game-footer', array('game'=>$this->game, 'channel' => $this->channel));?>
</div>
