<?php echo $this->headTitle($this->translate('Playground'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php
$this->headMeta()->setCharset('UTF-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable = no');
//$this->headMeta()->setProperty('og:title', 'my article title');
//$this->headMeta()->setProperty('og:type', 'article');
?>
<?php echo $this->headMeta(); ?>

<!-- Le styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->frontendAssetPath('images/favicon.ico'))) ?>

<?php /*
                ->prependStylesheet($this->basePath() . '/css/ie7.css', 'screen', 'IE 7')
                ->prependStylesheet($this->basePath() . '/css/ie8.css', 'screen', 'IE 8')
                ->prependStylesheet($this->basePath() . '/css/ie.css', 'screen', 'IE')
                ->prependStylesheet($this->basePath() . '/css/styles.css')
				->prependStylesheet($this->basePath() . '/css/uniform.default.css')*/
                ?>

<!-- Scripts -->
<?php /* echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
							  ->prependFile($this->basePath() . '/js/lib/pie.js', 'text/javascript', array('conditional' => 'IE 8',))
							  ->prependFile($this->basePath() . '/js/lib/selectivizr-min.js', 'text/javascript', array('conditional' => 'IE',))
                              ->prependFile($this->basePath() . '/js/bootstrap.min.js')
							  ->prependFile($this->basePath() . '/js/games.js')
							  ->prependFile($this->basePath() . '/js/share.js')
							  ->prependFile($this->basePath() . '/js/users.js')
							  ->prependFile($this->basePath() . '/js/script.js')
							  ->prependFile($this->basePath() . '/js/functions.js')
							  ->prependFile($this->basePath() . '/js/sniffer.js')
							  ->prependFile($this->basePath() . '/js/lib/jquery.timer.js')
							  ->prependFile($this->basePath() . '/js/lib/wScratchPad.js')
							  ->prependFile($this->basePath() . '/js/lib/jquery.limit-1.2.source.js')
							  ->prependFile($this->basePath() . '/js/lib/jquery.uniform-2.0.js')
							  ->prependFile($this->basePath() . '/js/lib/bowser.min.js')
							  ->prependFile($this->basePath() . '/js/lib/jquery.nivo.slider.js')
                              ->prependFile('http://ad1.emediate.dk/EAS_tag.1.0.js')
                              ->prependFile($this->basePath() . '/js/lib/jquery.validate.min.js')
							  ->prependFile($this->basePath() . '/js/lib/mousewheel.js')
							  ->prependFile($this->basePath() . '/js/lib/jscrollpane.js')
							  ->prependFile($this->basePath() . '/js/popin.js')
							  ->prependFile($this->basePath() . '/js/loader.js')
                              ->prependFile($this->basePath() . '/js/lib/jquery-1.9.0.min.js')*/ ?>
         
<?php
	echo $this->plugin('HeadLink');
    echo $this->plugin('HeadStyle');
    echo $this->plugin('HeadScript');
?>