<!-- user sidebar -->
<div class="span4 sidebar sidebar-left contact">
	<!-- sidebar user -->
    <div class="row-fluid">
    	<div id="sidebar-user" class="span9 center">
	    		
    		<div id="howto">
    			<p class="green green-star">Comment ça marche ?</p>
    			<ul>
    				<li>
    					<img src="<?php echo $this->frontendAssetPath('images/user/icon-money-black.png') ?>" alt="" />
    					<a href="<?php echo $this->url('cms', array('id' => 'comment-ca-marche')); ?>">Les badges et les points</a>
    				</li>
    				<li>
    					<img src="<?php echo $this->frontendAssetPath('images/user/icon-calendar-black.png') ?>" alt="" />
    					<a href="<?php echo $this->url('faq') ?>">F.A.Q</a>
    				</li>
    				<!-- <li>
    					<img src="<?php echo $this->frontendAssetPath('images/user/icon-cog-black.png') ?>" alt="" />
    					<a href="">La boutique</a>
    				</li> -->
    				<li>
    					<img src="<?php echo $this->frontendAssetPath('images/user/icon-contact-black.png') ?>" alt="" />
    					<a href="<?php echo $this->url('contact') ?>">Contactez-nous</a>
    				</li>
    			</ul>
    		</div>
    	
    	</div>
    </div>
</div>