<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<div class="game-header">
    <h1 class="baseline">
        <span class="first">Un jeu riche</span>
        <span>en &eacute;motions</span>
    </h1>
    
    <!-- contenu article -->
    <div class="welcome-block<?php if($this->layout()->facebooktemplate): echo ' fb-target'; endif ?>">
        <h2>
            <?php echo $this->game->getTitle(); ?>
        </h2>
        <?php if($this->game->getWelcomeBlock() && $this->game->getWelcomeBlock() != ''): ?>
            <?php echo $this->game->getWelcomeBlock(); ?>
        <?php else: ?>
            <p>
                week-ends en hôtel 4****, sauts en parachute,<br/>
                dîners étoilés, séances de bien-être...
            </p>
        <?php endif; ?>
    </div>
    
    <div class="star-left"></div>
    <div class="star-right"></div>
</div>