<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundGame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form) 
?>
<div class="row-fluid show-grid">
    <div class="span8">
        <?php echo $this->formHidden($form->get('id')); ?>

        <div class="control-group">
            <?php echo $this->formLabel($form->get('title')); ?>
            <?php echo $this->formInput($form->get('title')); ?>
            <?php echo $this->formElementErrors($form->get('title')) ?>
        </div>

         <div class="control-group">
                <?php echo $this->formLabel($form->get('description')); ?>
                <div class="controls">
                    <?php echo $this->formTextarea($form->get('description')); ?>
                    <?php echo $this->formElementErrors($form->get('description')) ?>
                </div>
            <?php $this->QgCKEditor(
                'description',
                    array(
                        'BasePath' => $this->basePath('zfcadmin/js/lib/ckeditor'),
                        'Width' => "450",
                        'Height' => "100",
                        //'Color' => "#000",
                        'Toolbar'=> array(
                             array('Bold','Italic','Underline','Link','Unlink'),
                         )
                    )
                );
            ?>
        </div>

        <div class="control-group">
            <?php echo $this->formLabel($form->get('hidden')); ?>
            <div class="controls"><?php echo $this->formCheckbox($form->get('hidden')); ?></div>
            <?php echo $this->formElementErrors($form->get('hidden')); ?>
        </div>
    </div>

    <div class="span4">
        <div class="thumbnail">
            <?php if($form->get('image')->getValue() != ''):?>
            <?php echo $this->formLabel($form->get('uploadImage')); ?>
            <img  data-src="holder.js/300x200" style="width: 300px; height: 200px;"src="<?php echo $this->basePath($form->get('image')->getValue()); ?>" />
            <?php endif;?>
            <div class="caption">
               <?php echo $this->formFile($form->get('uploadImage')); ?>
            </div>
        </div>
    </div>

</div>
<div class="row-fluid show-grid">
    <div class="span12">
        <?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
        <?php echo $this->formButton($form->get('submit')) ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>