<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<?php /* echo $this->form()->openTag($form) */ ?>
<?php /* echo $this->formButton($form->get('submit')) */ ?>

<form action="/admin/user/create/0" method="post" enctype="multipart/form-data" role="form">

    <button type="submit" name="submit" class="btn btn-default right" value="">Créer</button>
    <h1>Editer un utilisateur</h1>

<?php if ($this->redirect): ?><input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" /><?php endif ?>

<div id="content" class="tabbable tabs-left">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#identity" data-toggle="tab"><?php echo $this->translate('Identity'); ?></a></li>
        <li><a href="#address" data-toggle="tab"><?php echo $this->translate('Address'); ?></a></li>
        <li><a href="#newsletter" data-toggle="tab"><?php echo $this->translate('Newsletters'); ?></a></li>
        <li><a href="#avatar" data-toggle="tab"><?php echo $this->translate('Avatar'); ?></a></li>
    </ul>
    
    
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane active" id="identity">
            <?php echo $this->formHidden($form->get('id')); ?>
            
            <div class="form-group">
                <?php echo $this->formLabel($form->get('username')); ?>
                <?php echo $this->formInput($form->get(('username'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('username'))) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('email')); ?>
                <?php echo $this->formInput($form->get(('email'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('email'))) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('title')); ?>
                <?php foreach ($form->get('title')->getValueOptions() as $key => $value) : ?>
                <div class="radio">
                    <label>
                        <input type="radio" name="<?php echo $form->get('title')->getAttribute('name'); ?>"
                            <?php echo ($key == $form->get('title')->getValue()) ? 'checked="checked"' : ''; ?> value="<?php echo $key; ?>" />
                        <?php echo $value; ?>
                    </label>
                </div>
                <?php endforeach; ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('firstname')); ?>
                <?php echo $this->formInput($form->get(('firstname'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('firstname'))) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('lastname')); ?>
                <?php echo $this->formInput($form->get(('lastname'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('lastname'))) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('roleId')); ?>
                <?php echo $this->formSelect($form->get(('roleId'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('roleId'))) ?>
            </div>
            
            <div class="form-group">
                <?php echo $this->formLabel($form->get('dob')); ?>
                <?php echo $this->formDateTime($form->get(('dob'))->setAttribute('class', 'form-control date')) ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('dob'))) ?>
            </div>
        </div>
        <div class="tab-pane" id="address">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('address')); ?>
                <?php echo $this->formInput($form->get(('address'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('address'))) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('address2')); ?>
                <?php echo $this->formInput($form->get(('address2'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('address2'))) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('postal_code')); ?>
                <?php echo $this->formInput($form->get(('postal_code'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('postal_code'))) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('city')); ?>
                <?php echo $this->formInput($form->get(('city'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('city'))) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('telephone')); ?>
                <?php echo $this->formInput($form->get(('telephone'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('telephone'))) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('country')); ?>
                <?php echo $this->formSelect($form->get(('country'))->setAttribute('class', 'form-control')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('country'))) ?>
            </div>
        </label>
        </div>
        <div class="tab-pane" id="newsletter">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('optin')); ?>
                <?php foreach ($form->get('optin')->getValueOptions() as $key => $value) : ?>
                <div class="radio">
                    <label>
                        <input type="radio" name="<?php echo $form->get('optin')->getAttribute('name'); ?>"
                            <?php echo ($key == $form->get('optin')->getValue()) ? 'checked="checked"' : ''; ?> value="<?php echo $key; ?>" />
                        <?php echo $value; ?>
                    </label>
                </div>
                <?php endforeach; ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('optinPartner')); ?>
                <?php foreach ($form->get('optinPartner')->getValueOptions() as $key => $value) : ?>
                <div class="radio">
                    <label>
                        <input type="radio" name="<?php echo $form->get('optinPartner')->getAttribute('name'); ?>"
                            <?php echo ($key == $form->get('optinPartner')->getValue()) ? 'checked="checked"' : ''; ?> value="<?php echo $key; ?>" />
                        <?php echo $value; ?>
                    </label>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="tab-pane" id="avatar">
            <div class="image-profil">
                <?php echo $this->formLabel($form->get('avatar')); ?>
                <?php echo $this->formFile($form->get('avatar')); ?>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('avatar'))) ?>
            </div>
            <?php if($form->get('avatar')->getValue() != ''):?>
                <img src="<?php echo $this->basePath($form->get('avatar')->getValue()); ?>" />
            <?php endif;?>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>