<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();

//$form->setAttribute('action', $this->url('admin/playgroundgame/quiz-question-add', array('quizId' => $this->quiz_id, 'questionId' => $this->question_id)));
?>

<h1><?php echo $this->translate('Add questions'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?><?php echo $this->formButton($form->get('submit')) ?>

<div id="content" class="tabbable tabs-left">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#general" data-toggle="tab"><?php echo $this->translate('General'); ?></a></li>
        <li><a href="#options" data-toggle="tab"><?php echo $this->translate('Options'); ?></a></li>
        <li><a href="#answers" data-toggle="tab"><?php echo $this->translate('Answers'); ?></a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane active" id="general">
                
            <?php echo $this->formInput($form->get(('quiz_id'))->setAttribute('class', 'form-control')); ?>
            
            <div class="control-group">
                <?php echo $this->formLabel($form->get('type')); ?>
                <div class="controls"><?php echo $this->formRadio($form->get('type')); ?></div>
                <div class="controls"><?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('type'))); ?></div>
            </div>
            
            <div class="control-group">
                <?php echo $this->formLabel($form->get('question')); ?>
                <div class="controls">
                    <?php echo $this->formTextarea($form->get(('question'))->setAttribute('class', 'form-control')->setAttribute('row', '4')); ?>
                    <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('question'))) ?>
                </div>
            <?php $this->QgCKEditor(
                'question',
                    array(
                    	'BasePath' => $this->libAssetPath('js/ckeditor'),
                    	'Width' => "450",
                        'Height' => "100",
                        //'Color' => "#000",
                        'Toolbar'=> array(
    	                     array('Bold','Italic','Underline','Link','Unlink'),
                         )
                    )
                );
            ?>
            </div>
                
            <div class="control-group">
                <?php echo $this->formLabel($form->get('hint')); ?>
                <div class="controls">
                    <?php echo $this->formTextarea($form->get(('hint'))->setAttribute('class', 'form-control')->setAttribute('row', '4')); ?>
                    <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('hint'))) ?>
                </div>
                <?php $this->QgCKEditor(
                    'hint',
                        array(
                        	'BasePath' => $this->libAssetPath('js/ckeditor'),
                        	'Width' => "450",
                            'Height' => "100",
                            //'Color' => "#000",
                            'Toolbar'=> array(
        	                     array('Bold','Italic','Underline','Link','Unlink'),
                             )
                        )
                    );
                ?>
            </div>        
        </div>
        <div class="tab-pane" id="options">
            <div class="control-group">
                <?php echo $this->formLabel($form->get('timer')); ?>
                <div class="controls"><?php echo $this->formRadio($form->get('timer')); ?></div>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('timer'))); ?>
            </div>

            <div class="control-group">
                <?php echo $this->formLabel($form->get('timer_duration')); ?>
                <div class="controls"><?php echo $this->formInput($form->get(('timer_duration'))->setAttribute('class', 'form-control')); ?></div>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('timer_duration'))) ?>
            </div>
                
            <div class="control-group">
                <?php echo $this->formLabel($form->get('weight')); ?>
                <div class="controls"><?php echo $this->formInput($form->get(('weight'))->setAttribute('class', 'form-control')); ?></div>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('weight'))) ?>
            </div>
                
            <div class="control-group">
                <?php echo $this->formLabel($form->get('position')); ?>
                <div class="controls"><?php echo $this->formInput($form->get(('position'))->setAttribute('class', 'form-control')); ?></div>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('position'))) ?>
            </div>
            
            <div class="control-group">  
                <?php echo $this->formLabel($form->get('video')); ?>
                <div class="controls"><?php echo $this->formInput($form->get(('video'))->setAttribute('class', 'form-control')); ?></div>
                <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('video'))) ?>
            </div>
            
            <div class="control-group">
                <?php echo $this->formLabel($form->get('upload_image')); ?>
                <div class="controls"><?php echo $this->formFile($form->get('upload_image')); ?></div>
            </div>
            <?php if($form->get('image')->getValue() != ''):?>
            	<img src="<?php echo $this->basePath($form->get('image')->getValue()); ?>" />
            <?php endif;?>
        </div>
        <div class="tab-pane" id="answers">
            <a href="#" onclick="add_answer()">Add a new answer</a>
            <div id="answer_entry" class="control-group">
            <?php echo $this->formCollection($form->get('answers'));?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>