<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-default right')) ?>

<h1><?php echo $this->translate($this->title); ?></h1>

<div id="content" class="tabbable tabs-left">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#general" data-toggle="tab"><?php echo $this->translate('General'); ?></a></li>
        <li><a href="#mechanics" data-toggle="tab"><?php echo $this->translate('Game Mechanics'); ?></a></li>
        <li><a href="#prizes" data-toggle="tab"><?php echo $this->translate('Lots'); ?></a></li>
        <li><a href="#platform" data-toggle="tab"><?php echo $this->translate('Plateforme'); ?></a></li>
        <li><a href="#facebook" data-toggle="tab"><?php echo $this->translate('Facebook'); ?></a></li>
        <li><a href="#design" data-toggle="tab"><?php echo $this->translate('Design'); ?></a></li>
        <li><a href="#column" data-toggle="tab"><?php echo $this->translate('Colonne de droite'); ?></a></li>
        <li><a href="#share" data-toggle="tab"><?php echo $this->translate('Partage'); ?></a></li>
        <li><a href="#welcome_page" data-toggle="tab"><?php echo $this->translate('Bloc de bienvenue'); ?></a></li>
        <li><a href="#terms_page" data-toggle="tab"><?php echo $this->translate('Page de règlement'); ?></a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <?php echo $this->game_form;?>

        <div class="tab-pane" id="mechanics">
        	<div class="form-group">
	            <?php echo $this->formLabel($form->get('template')); ?>
	            <?php echo $this->formSelect($form->get(('template'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('template'))) ?>
	        </div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('postDisplayMode')); ?>
	            <?php echo $this->formSelect($form->get(('postDisplayMode'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('postDisplayMode'))) ?>
			</div>
			<div class="form-group checkbox">
	            <?php echo $this->formLabel($form->get('voteAnonymous')); ?>
	            <?php echo $this->formCheckbox($form->get('voteAnonymous')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('voteAnonymous'))) ?>
	        </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>