<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<?php
$form = $this->loginForm;
$form->prepare();
//$form->setAttribute('action', $this->url('frontend/zfcuser/ajaxlogin'));
//$form->setAttribute('action', $this->url('frontend/zfcuser/login'));
$form->setAttribute('id', 'loginAdmin');
$form->setAttribute('method', 'post');
?>
<div class="row-fluid">
    <div class="span4" id="login">
        <fieldset>
            <legend>
                <span>Playground</span>
            </legend>
            <?php echo $this->form()->openTag($form) ?>
            <?php echo $this->formElementErrors($form->get('identity')) ?>
            <div class="control-group">
                <?php echo $this->formInput($form->get('identity')) ?>
            </div>
            <div class="control-group">
                <?php echo $this->formInput($form->get('credential')) ?>
            </div>
            <div class="form-actions center">
                <?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
                <?php echo $this->formButton($form->get('submit')) ?>
            </div> 
            <?php echo $this->form()->closeTag() ?>
        </fieldset>
    </div>
</div>