<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow'); ?>
<?php
$fm = $this->flashMessenger()->setNamespace('playgroundflow')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}
?>
<?php $addLink = $this->url('admin/playgroundflow/webtechno/story/create', array('webTechnoId' => $this->webTechnoId, 'mappingId' => 0)); ?>

<ul class="liste-buttons">
	<li class="btn-admin"><a href="<?php echo $addLink;?>"><?php echo $this->translate('Add new story'); ?></a></li>
</ul>

<h1>Liste des stories</h1>

<table class="table">
    <tr>
        <th><?php echo $this->translate('Code'); ?></th>
        <th><?php echo $this->translate('Label'); ?></th>
        <th><?php echo $this->translate('Description'); ?></th>
        <th></th>
    </tr>
    <?php foreach ($this->mapping as $map): ?>
    	<?php $editLink = $this->url('admin/playgroundflow/webtechno/story/edit', array('webTechnoId' => $this->webTechnoId, 'mappingId' => $map->getId()));?>
    	<?php $deleteLink = $this->url('admin/playgroundflow/webtechno/story/remove', array('webTechnoId' => $this->webTechnoId, 'mappingId' => $map->getId()));?>
    	<?php $optionLink = $this->url('admin/playgroundflow/webtechno/story/object', array('webTechnoId' => $webTechno->getId(), 'mappingId' => $map->getId())); ?>
        <tr>
            <td><?php echo $map->getStory()->getCode() ?></td>
            <td><?php echo $map->getStory()->getLabel() ?></td>
            <td><?php echo $map->getStory()->getDefinition() ?></td>
            <td>
                <a href='<?php echo $editLink ?>'><?php echo $this->translate('Edit'); ?></a> | <a href='<?php echo $deleteLink ?>'><?php echo $this->translate('Delete'); ?></a><?php if($optionLink != ''):?> | <a href='<?php echo $optionLink ?>'><?php echo $this->translate('Manage objects'); ?></a><?php endif;?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php echo $this->paginationControl($this->mapping, 'Sliding', 'playground-flow/web-techno/pagination_webtechnostorylist'); ?>
