<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow'); ?>
<?php
$fm = $this->flashMessenger()->setNamespace('playgroundflow')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}
?>
<?php $addLink = $this->url('admin/playgroundflow/webtechno/create', array('webTechnoId' => 0)); ?>

<ul class="liste-buttons">
	<li class="btn-admin"><a href="<?php echo $addLink;?>"><?php echo $this->translate('Add new Web Techno'); ?></a></li>
</ul>

<h1>Liste des Web Technos</h1>

<table class="table">
    <tr>
        <th><?php echo $this->translate('Label'); ?></th>
        <th><?php echo $this->translate('Definition'); ?></th>
        <th></th>
    </tr>
    <?php foreach ($this->webtechnos as $webtechno): ?>
    	<?php $editLink = $this->url('admin/playgroundflow/webtechno/edit', array('webTechnoId' => $webtechno->getId()));?>
    	<?php $deleteLink = $this->url('admin/playgroundflow/webtechno/remove', array('webTechnoId' => $webtechno->getId()));?>
    	<?php $optionLink = $this->url('admin/playgroundflow/webtechno/story', array('webTechnoId' => $webtechno->getId())); ?>
        <tr>
            <td><?php echo $webtechno->getLabel() ?></td>
            <td><?php echo $webtechno->getDefinition() ?></td>
            <td>
                <a href='<?php echo $editLink ?>'><?php echo $this->translate('Edit'); ?></a> | <a href='<?php echo $deleteLink ?>'><?php echo $this->translate('Delete'); ?></a><?php if($optionLink != ''):?> | <a href='<?php echo $optionLink ?>'><?php echo $this->translate('Manage stories'); ?></a><?php endif;?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php echo $this->paginationControl($this->webtechnos, 'Sliding', 'playground-flow/web-techno/pagination_webtechnolist'); ?>
