<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php $locale= $this->plugin('translate')->getTranslator()->getLocale(); ?>
<?php $downloadLink = $this->url('admin/'. $this->game->getClassType() .'/download', array('gameId' => $this->game->getId()));?>
<?php $drawLink = $this->url('admin/'. $this->game->getClassType() .'/draw', array('gameId' => $this->game->getId()));?>
<?php
/*$fm = $this->flashMessenger()->setNamespace('playgroundgame')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}*/
?>
<h1><a href="<?php echo $this->url('admin/playgroundgame/edit-lottery', array('gameId' => $this->gameId)) ?>"><?php echo $this->game->getTitle(); ?></a></h1>

<h3><?php echo $this->translate('Liste des Participants'); ?></h3>

<a href='<?php echo $downloadLink ?>'>Export CSV</a>
<?php if($this->game->getDrawAuto()): ?>
  |  <a href='<?php echo $drawLink ?>'>Tirage au sort automatique</a>
<?php endif; ?>
<table class="table">
    <tr>
        <?php if (!$this->game->getAnonymousAllowed()) : ?>
            <th><?php echo $this->translate('Id'); ?></th>
            <th><?php echo $this->translate('Pseudo'); ?></th>
            <th><?php echo $this->translate('Nom'); ?></th>
            <th><?php echo $this->translate('Prenom'); ?></th>
            <th><?php echo $this->translate('E-mail'); ?></th>
            <th><?php echo $this->translate('Optin partenaire'); ?></th>
        <?php endif; ?>
        <?php if (current($this->entries->getCurrentItems()) && current($this->entries->getCurrentItems())->getPlayerData()) : ?>
        <?php $entryData = json_decode(current($this->entries->getCurrentItems())->getPlayerData()); ?>
            <?php foreach ($entryData as $key => $attrib): ?>
                <th><?php echo $key ?></th>
            <?php endforeach; ?>
        <?php endif; ?>
        <th><?php echo $this->translate('A gagné'); ?></th>
        <th><?php echo $this->translate('Date - H'); ?></th>
    </tr>
    <?php foreach ($this->entries as $entry): ?>
        <tr>
            <?php if (!$this->game->getAnonymousAllowed()) : ?>
                <td><?php echo $entry->getUser()->getId(); ?></td>
                <td><?php echo $entry->getUser()->getUsername(); ?></td>
                <td><?php echo $entry->getUser()->getLastname(); ?></td>
                <td><?php echo $entry->getUser()->getFirstname(); ?></td>
                <td><?php echo $entry->getUser()->getEmail(); ?></td>
                <td><?php echo $entry->getUser()->getOptinPartner(); ?></td>
            <?php endif; ?>
            <?php if ($entry->getPlayerData()) : ?>
                <?php $entryData = json_decode($entry->getPlayerData()); ?>
                <?php foreach ($entryData as $key => $attrib): ?>
                    <td><?php if (is_array($attrib)) {echo implode(', ', $attrib); } else { echo $attrib; } ?></td>
                <?php endforeach; ?>
            <?php endif; ?>
            <td><?php echo $entry->getWinner(); ?></td>

            <?php //$editLink = $this->url('admin/playgroundgame/edit', array('gameId' => $game->getId()));?>
            <?php //$deleteLink = $this->url('admin/playgroundgame/remove', array('gameId' => $game->getId()));?>

            <td><?php echo $this->dateFormat($entry->getCreatedAt(), IntlDateFormatter::LONG, IntlDateFormatter::MEDIUM, $locale); ?></td>
        </tr>
    <?php endforeach; ?>
</table>

<?php echo (count($this->entries)>1)?$this->paginationControl($this->entries, 'Sliding', 'playground-game/admin/pagination_entrylist', array('classType' => $this->game->getClassType()  ,'gameId' => $this->gameId)):''; ?>
