<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundpartnership');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>
<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?><?php echo $this->formButton($form->get('submit')) ?>
<div class="tab-pane active" id="general">
    <div>

        <?php echo $this->formHidden($form->get('id')); ?>

        <?php echo $this->formLabel($form->get('name')); ?>
        <?php echo $this->formInput($form->get('name')); ?>
        <?php echo $this->formElementErrors($form->get('name')) ?>

        <?php echo $this->formLabel($form->get('active')); ?>
        <?php echo $this->formSelect($form->get('active')); ?>
        <?php echo $this->formElementErrors($form->get('active')) ?>
        
        <?php echo $this->formLabel($form->get('bouncePage')); ?>
        <?php echo $this->formRadio($form->get('bouncePage')); ?>
        <?php echo $this->formElementErrors($form->get('bouncePage')) ?>
        
        <?php echo $this->formLabel($form->get('website')); ?>
        <?php echo $this->formInput($form->get('website')); ?>
        <?php echo $this->formElementErrors($form->get('website')) ?>
        
        <?php echo $this->formLabel($form->get('facebook')); ?>
        <?php echo $this->formInput($form->get('facebook')); ?>
        <?php echo $this->formElementErrors($form->get('facebook')) ?>       

        <?php echo $this->formLabel($form->get('newsletter')); ?>
        <?php echo $this->formSelect($form->get('newsletter')); ?>
        <?php echo $this->formElementErrors($form->get('newsletter')) ?> 
        
    </div>
</div>
<div class="tab-pane" id="images">
    <div>
    <?php echo $this->formLabel($form->get('uploadLogo')); ?>
    <?php echo $this->formFile($form->get('uploadLogo')); ?>
    </div>
    <?php if($form->get('logo')->getValue() != ''):?>
    	<img src="<?php echo $this->basePath($form->get('logo')->getValue()); ?>" />
    <?php endif;?>
    
    <div>
    <?php echo $this->formLabel($form->get('uploadSmallLogo')); ?>
    <?php echo $this->formFile($form->get('uploadSmallLogo')); ?>
    </div>
    <?php if($form->get('smallLogo')->getValue() != ''):?>
    	<img src="<?php echo $this->basePath($form->get('smallLogo')->getValue()); ?>" />
    <?php endif;?>
</div>
<?php echo $this->form()->closeTag() ?>