<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundpartnership');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>
<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-default right')) ?>

<h1><?php echo $this->translate('Edit Partners'); ?></h1>

<div class="tab-pane active" id="general">
    <div>

        <?php echo $this->formHidden($form->get('id')); ?>

        <div class="form-group">
        <?php echo $this->formLabel($form->get('name')); ?>
        <?php echo $this->formInput($form->get(('name'))->setAttribute('class', 'form-control')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('name'))) ?>
        </div>
        <div class="form-group">
        <?php echo $this->formLabel($form->get('active')); ?>
        <?php echo $this->formSelect($form->get(('active'))->setAttribute('class', 'form-control')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('active'))) ?>
        </div>
        <div class="form-group">
        <?php echo $this->formLabel($form->get('bouncePage')); ?>
        <?php echo $this->formRadio($form->get('bouncePage')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('bouncePage'))) ?>
        </div>
        <div class="form-group">
        <?php echo $this->formLabel($form->get('website')); ?>
        <?php echo $this->formInput($form->get(('website'))->setAttribute('class', 'form-control')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('website'))) ?>
        </div>
        <div class="form-group">
        <?php echo $this->formLabel($form->get('facebook')); ?>
        <?php echo $this->formInput($form->get(('facebook'))->setAttribute('class', 'form-control')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('facebook'))) ?>
        </div>
        <div class="form-group">
        <?php echo $this->formLabel($form->get('newsletter')); ?>
        <?php echo $this->formSelect($form->get(('newsletter'))->setAttribute('class', 'form-control')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('newsletter'))) ?>
        </div>
    </div>
</div>
<div class="tab-pane" id="images">
    <div>
    <?php echo $this->formLabel($form->get('uploadLogo')); ?>
    <?php echo $this->formFile($form->get('uploadLogo')); ?>
    </div>
    <?php if($form->get('logo')->getValue() != ''):?>
    	<img src="<?php echo $this->basePath($form->get('logo')->getValue()); ?>" />
    <?php endif;?>
    
    <div>
    <?php echo $this->formLabel($form->get('uploadSmallLogo')); ?>
    <?php echo $this->formFile($form->get('uploadSmallLogo')); ?>
    </div>
    <?php if($form->get('smallLogo')->getValue() != ''):?>
    	<img src="<?php echo $this->basePath($form->get('smallLogo')->getValue()); ?>" />
    <?php endif;?>
</div>
<?php echo $this->form()->closeTag() ?>