<?php $achievements =  $this->userBadges(0,true);?>
<!-- USER ACCOUNT -->
<div id="account-badge" class="row">
	<!-- mes badges -->
	<div id="my-badges">
		<h1>
		    Mes badges
		</h1>
		<ul>
		    <?php $i=1;foreach($achievements as $key=>$achievement): ?>
    		    <?php $badge = $achievement['badge'];?>
    			<li<?php if ($i == 1): ?> id="first-badge"<?php endif;?> class="col-md-4">
    			     <?php if($badge):?>
    			         <img src="<?php echo $this->frontendAssetPath('images/badges/big-'. strtolower($badge->getLevelLabel()) .'-' . strtolower($key) .'.png')?>" alt="" />
    			     <?php else:?>
    			         <img  src="<?php echo $this->frontendAssetPath('images/badges/big-default.png')?>" alt="" />
    			     <?php endif;?>
    			     <div class="<?php echo ($badge)? strtolower($badge->getLevelLabel()):'silverlight'?>">
			             <p>
			                 <b>
			                     <?php echo ucfirst(strtolower($this->translate($key)));?>
			                 </b>
			             </p>
			             <p>
			                 <?php echo ($badge)?'Niveau '.$this->translate($badge->getLevelLabel()):'Pas de niveau'; ?>
			             </p>
    					 <p>
    					     <?php echo $achievement['eventsDone'] ?>
    					 </p>
    					 <p>
    					     <?php echo $achievement['nextBadge']?>
    					 </p>
    			     </div>
    		    </li>
            <?php $i++;endforeach;?>
		</ul>
	</div>
	<div class="clearfix"></div>
	<!-- mes points -->
	<div id="my-points">
		<div id="title-point">
			<h1>
			    Mes points
			</h1>
			<p class="view-detail">
			    <a class="btn btn-default" href="<?php echo $this->url('frontend/activity', array('channel' => $this->channel));?>">
			        Votre historique de points
			    </a>
			</p>
		</div>
		<div class="row">
			<div class="col-md-8">
				<p>
				    <b>
				        Participer à un jeu
				    </b>
				    <span>
				        + 100 points
				    </span>
				</p>
				<p>
				    Participez aux jeux concours pour tenter de gagner pleins de cadeaux, et en plus vous cumulez des points !
				</p>
				<p>
				    <a class="btn btn-default" href="<?php echo $this->url('frontend/jeuxconcours', array('channel' => $this->channel));?>">
				        Voir les jeux en cours
				    </a>
				</p>
			</div>
			<div class="col-md-4">
				<p class="view-detail">
				    <?php echo number_format($this->gamesTotal, 0, ',', ' ' ) ?> points
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<p>
				    <b>
				        Renseignez les infos de votre compte
				    </b>
				    <span>
				        Jusqu'à + 725 points
				    </span>
				</p>
				<p>
				    Validez vos informations d'inscriptions, changez votre pseudo ou votre image de profil et renseignez vos coordonnées. Plus vous renseignez d'informations, plus vous gagnez de points !
				</p>
				<p>
				    <a class="btn btn-default" href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel));?>">
				        Modifier mes informations persos
				    </a>
				</p>
			</div>
			<div class="col-md-4">
				<p class="view-detail">
				    <?php echo number_format($this->userTotal, 0, ',', ' ' ) ?> points
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<p>
				    <b>
				        Inscrivez-vous aux newletter
				    </b>
				    <span>
				        +300 points
				    </span>
				</p>
				<p>
				    <a class="btn btn-default" href="<?php echo $this->url('frontend/zfcuser/newsletter', array('channel' => $this->channel));?>">
				        Inscrivez-vous
				    </a>
				    à la newsletter Playground et à celle de nos partenaires officiels
				</p>
			</div>
			<div class="col-md-4">
				<p class="view-detail">
				    <?php echo number_format($this->newsletterTotal, 0, ',', ' ' ) ?> points
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<p>
				    <b>
				        Parrainez vos amis
				    </b>
				    <span>
				        +250 points par ami inscrit
				    </span>
				</p>
				<p>
				    Lorsque vous participe à un jeu, partagez le auprès de vos amis par mail ou sur les réseaux sociaux, chaque nouvel ami qui s'inscrit vous rapporte des points.
				</p>
				<p>
				    <a class="btn btn-default" href="<?php echo $this->url('frontend/sponsorfriends', array('channel' => $this->channel)) ?>">
				        Invitez des amis maintenant!
				    </a>
				</p>
			</div>
			<div class="col-md-4">
				<p class="view-detail">
				    <?php echo number_format($this->sponsorshipTotal, 0, ',', ' ' ) ?> points
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<p>
				    <b>
				        Atteindre le niveau bronze d'un badge
				    </b>
				    <span>
				        +250 points
				    </span>
                </p>
			</div>
			<div class="col-md-4">
				<p class="view-detail">
				    <?php echo number_format($this->badgesBronze, 0, ',', ' ' ) ?> points
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<p>
				    <b>
				        Atteindre le niveau argent d'un badge
				    </b>
				    <span>
				        +500 points
				    </span>
			    </p>
			</div>
			<div class="col-md-4">
				<p class="view-detail">
				    <?php echo number_format($this->badgesSilver, 0, ',', ' ' ) ?> points
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<p>
				    <b>
				        Atteindre le niveau or d'un badge
				    </b>
				    <span>
				        +750 points
				    </span>
				</p>
			</div>
			<div class="col-md-4">
				<p class="view-detail">
				    <?php echo number_format($this->badgesGold, 0, ',', ' ' ) ?> points
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<p>
				    <b>
				        Anniversaire
				    </b>
				    <span>
				        +250 points
				    </span>
				</p>
				<p>
				    Pour récompenser nous vous offrons des points chaque année le jour de votre inscription !
				</p>
			</div>
			<div class="col-md-4">
				<p class="view-detail">
				    <?php echo number_format($this->anniversaryTotal, 0, ',', ' ' ) ?> points
				</p>
			</div>
		</div>
		<div>
			<p class="big-points">
			    Total : <?php echo number_format($this->total, 0, ',', ' ' ) ?> points
			</p>
		</div>
	</div>
</div>
<!-- END USER ACCOUNT -->