<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();

//$form->setAttribute('action', $this->url('admin/playgroundgame/quiz-question-add', array('quizId' => $this->quiz_id, 'questionId' => $this->question_id)));
?>

<h1><?php echo $this->translate('Questions'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formButton($form->get('submit')->setLabel($this->translate('Validate'))); ?>
<div id="dz-root"></div>
<div id="content" class="tabbable tabs-left">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#general" data-toggle="tab"><?php echo $this->translate('General'); ?></a></li>
        <li><a href="#answers" data-toggle="tab"><?php echo $this->translate('Réponses'); ?></a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane active" id="general">

            <?php echo $this->formInput($form->get('quiz_id')); ?>

            <div class="control-group">
                <?php echo $this->formLabel($form->get('prediction')); ?>
                <div class="controls"><?php echo $this->formCheckbox($form->get('prediction')); ?></div>
                <?php echo $this->formElementErrors($form->get('prediction')); ?>
            </div>

            <div class="control-group">
                <?php echo $this->formLabel($form->get('type')); ?>
                <div class="controls"><?php echo $this->formRadio($form->get('type')); ?></div>
                <div class="controls"><?php echo $this->formElementErrors($form->get('type')); ?></div>
            </div>

            <div class="control-group">
                <?php echo $this->formLabel($form->get('question')); ?>
                <div class="controls">
                    <?php echo $this->formTextarea($form->get('question')); ?>
                    <?php echo $this->formElementErrors($form->get('question')) ?>
                </div>
            <?php $this->QgCKEditor(
                'question',
                    array(
                        'BasePath' => $this->libAssetPath('js/ckeditor'),
                        'Width' => "450",
                        'Height' => "100",
                        //'Color' => "#000",
                        'Toolbar'=> array(
                             array('Bold','Italic','Underline','Link','Unlink'),
                         )
                    )
                );
            ?>
            </div>

            <div class="control-group">
                <?php echo $this->formLabel($form->get('hint')); ?>
                <div class="controls">
                    <?php echo $this->formTextarea($form->get('hint')); ?>
                    <?php echo $this->formElementErrors($form->get('hint')) ?>
                </div>
                <?php $this->QgCKEditor(
                    'hint',
                        array(
                            'BasePath' => $this->libAssetPath('js/ckeditor'),
                            'Width' => "450",
                            'Height' => "100",
                            //'Color' => "#000",
                            /*'Toolbar'=> array(
                                 array('Bold','Italic','Underline','Link','Unlink'),
                             )*/
                             'Toolbar'=> array(
                                 array('Link','Unlink'),
                             )
                        )
                    );
                ?>
            </div>

            <?php echo $this->formHidden($form->get('timer')); ?>
            <?php echo $this->formHidden($form->get('timer_duration')); ?>

            <div class="control-group">
                <?php echo $this->formLabel($form->get('position')); ?>
                <div class="controls"><?php echo $this->formInput($form->get('position')); ?></div>
                <?php echo $this->formElementErrors($form->get('position')) ?>
            </div>

            <div class="control-group">
                <?php echo $this->formLabel($form->get('video')); ?>
                <div class="controls"><?php echo $this->formInput($form->get('video')); ?></div>
                <?php echo $this->formElementErrors($form->get('video')) ?>
            </div>

            <div class="control-group">
                <?php echo $this->formLabel($form->get('upload_image')); ?>
                <div class="controls"><?php echo $this->formFile($form->get('upload_image')); ?></div>
            </div>
            <?php if($form->get('image')->getValue() != ''):?>
                <img src="<?php echo $this->basePath($form->get('image')->getValue()); ?>"  class="image_uploaded"/>
                <div class="controls">
                    <input id="delete_image" name="delete_image" type="button" value="Supprimer l'image">
                    <?php echo $this->formHidden($form->get('delete_image')); ?>
                </div>
            <?php endif;?>

            <div class="control-group">
                <label class="control-label" for="search_sound">Audio</label>
                <div class="controls">
                    <input id="search_sound" name="search_sound" type="text" placeholder="Search music on Deezer">
                </div>
            </div>
            <?php if($form->get('audio')->getValue() != ''):?>
                <div class="controls">
                    <input id="delete_audio" name="delete_audio_button" type="button" value="Supprimer la musique">
                </div>
            <?php endif; ?>

             <?php echo $this->formHidden($form->get('audio')); ?>
             <?php echo $this->formHidden($form->get('autoplay')); ?>

        </div>
        <div class="tab-pane" id="answers">
            <ul class="liste-buttons">
                <li class="btn-admin"><a href="#" onclick="add_answer()"><?php echo $this->translate('Ajouter une réponse'); ?></a></li>
            </ul>

            <div id="answer_entry" class="control-group">
            <?php echo $this->formCollection($form->get('answers'));?>
            </div>

            <ul class="liste-buttons">
                <li class="btn-admin"><a href="#" onclick="add_answer()"><?php echo $this->translate('Ajouter une réponse'); ?></a></li>
            </ul>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $('#tabs').tab();
        $('.datepicker').datepicker();

        // TODO : Placer ce JS dans un fichier JS
        $('#delete_image').on('click', function() {
            $('.delete_image').val(true);
            $('.image_uploaded').remove();
        });
	    
	    $('#delete_audio').on('click', function() {
	    	$('input[name=audio]').val('');
	    	$('#audio-informations').remove();
	    });
    });
</script>
<script>

    var template = $('#answer_entry > fieldset > span');
    var datatemplate = $('#answer_entry > fieldset > span').data('template');
    var initialCount = $('#answer_entry textarea').length;
    template.data('template', '<fieldset id="answers__index__">'+datatemplate+'</fieldset>');

    for(i=0;i<initialCount;i++){
        var answerName = 'answers['+i+'][answer]';
        var explanationName = 'answers['+i+'][explanation]';
        CKEDITOR.replace(answerName, {"toolbar":[["Source","Maximize"],["Templates","Styles","Format"],["Bold","Italic","Underline","Subscript","Superscript"],["NumberedList","BulletedList","Outdent","Indent"],["JustifyLeft","JustifyCenter","JustifyRight"],["Link","Unlink"],["Image","Table"]],"width":"100%","height":"340","language":"fr","uiColor":"#F7F7F7","filebrowserBrowseUrl":"\/elfinder\/ckeditor","filebrowserWindowWidth":"1000","filebrowserWindowHeight":"650"});
        CKEDITOR.replace(explanationName, {"toolbar":[["Source","Maximize"],["Templates","Styles","Format"],["Bold","Italic","Underline","Subscript","Superscript"],["NumberedList","BulletedList","Outdent","Indent"],["JustifyLeft","JustifyCenter","JustifyRight"],["Link","Unlink"],["Image","Table"]],"width":"100%","height":"340","language":"fr","uiColor":"#F7F7F7","filebrowserBrowseUrl":"\/elfinder\/ckeditor","filebrowserWindowWidth":"1000","filebrowserWindowHeight":"650"});
    }

    function add_answer() {
        var currentCount = $('#answer_entry textarea').length;
        var template = $('#answer_entry > fieldset > span').data('template');
        var answerName = 'answers['+currentCount+'][answer]';
        var explanationName = 'answers['+currentCount+'][explanation]';
        template = template.replace(/__index__/g, currentCount);
        $('#answer_entry').append(template);
        $('#answer_entry').append('<hr/>');

        CKEDITOR.replace(answerName, {"toolbar":[["Source","Maximize"],["Templates","Styles","Format"],["Bold","Italic","Underline","Subscript","Superscript"],["NumberedList","BulletedList","Outdent","Indent"],["JustifyLeft","JustifyCenter","JustifyRight"],["Link","Unlink"],["Image","Table"]],"width":"100%","height":"340","language":"fr","uiColor":"#F7F7F7","filebrowserBrowseUrl":"\/elfinder\/ckeditor","filebrowserWindowWidth":"1000","filebrowserWindowHeight":"650"});
        CKEDITOR.replace(explanationName, {"toolbar":[["Source","Maximize"],["Templates","Styles","Format"],["Bold","Italic","Underline","Subscript","Superscript"],["NumberedList","BulletedList","Outdent","Indent"],["JustifyLeft","JustifyCenter","JustifyRight"],["Link","Unlink"],["Image","Table"]],"width":"100%","height":"340","language":"fr","uiColor":"#F7F7F7","filebrowserBrowseUrl":"\/elfinder\/ckeditor","filebrowserWindowWidth":"1000","filebrowserWindowHeight":"650"});

        return false;
    }

    /*$('#answer_entry button').live('click',function(){
        $(this).parent().parent().empty();
        return false;
    });*/
</script>