<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<div class="return"><a href="<?php echo $this->url('admin/playgroundflow/object');?>"><?php echo $this->translate('Retour'); ?></a></div>

<h1><?php echo $this->translate('Création'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?><?php echo $this->formButton($form->get('submit')) ?>

<div id="content">
        <div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('code')); ?>
	            <?php echo $this->formInput($form->get('code')); ?>
	            <?php echo $this->formElementErrors($form->get('code')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('label')); ?>
	            <?php echo $this->formInput($form->get('label')); ?>
	            <?php echo $this->formElementErrors($form->get('label')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('definition')); ?>
	            <?php echo $this->formTextarea($form->get('definition')); ?>
	            <?php echo $this->formElementErrors($form->get('definition')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('parent')); ?>
	            <?php echo $this->formSelect($form->get('parent')); ?>
	            <?php echo $this->formElementErrors($form->get('parent')) ?>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>