<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-default right')) ?>

<h1><?php echo $this->translate('Création'); ?></h1>

<div id="content">
        <div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('code')); ?>
	            <?php echo $this->formInput($form->get(('code'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('code'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('label')); ?>
	            <?php echo $this->formInput($form->get(('label'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('label'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('definition')); ?>
	            <?php echo $this->formTextarea($form->get(('definition'))->setAttribute('class', 'form-control')->setAttribute('row', '4')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('definition'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('parent')); ?>
	            <?php echo $this->formSelect($form->get(('parent'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('parent'))) ?>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>