<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<div class="game-postvote row-fluid welcome">
	<h1><?php echo $this->game->getTitle(); ?></h1>
	
	<!-- BLOCK GAME START -->
    <?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game, 'channel' => $this->channel));?>
    <!-- END BLOCK GAME START -->

	<!-- contenu article -->
	<div id="content-article" class="row-fluid rounded backgrey">
		
		<?php if(count($this->flashMessages)>0):?>
			<p class="already-play"><?php echo $this->flashMessages[0];?></p>
	    <?php endif;?>
	    
		<div class="welcome-block<?php if($this->layout()->facebooktemplate): echo ' fb-target'; endif ?>"><?php echo $this->game->getWelcomeBlock(); ?></div>
		<div class="center">
			<div class="btn btn-inverse seeparticipants">
				<a href="<?php echo $this->url('frontend/postvote/list', array('id' => $this->game->getIdentifier(), 'filter' => $this->game->getPostDisplayMode(), 'channel' => $this->channel))?>" class="arrow-right">Voir les participants</a>
			</div>
			<?php if($game->isStarted()):?>
			<div class="btn btn-orange">
				<a href="<?php echo $this->url('frontend/postvote/play', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" class="arrow-right">Participer</a>
			</div>
			<?php endif;?>
		</div>
	</div>
	<p id="reglement"><a href="<?php echo $this->url('frontend/postvote/terms', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" target="_blank">Règlement</a></p>
</div>