<div id="lost-pass" class="row-fluid">
	<div class="container-content span8">
		<div class="row-fluid">
		
			<p class="h2"><?php echo $this->translate('Your password has been changed');?>.</p>
		
			<div id="container-form" class="row-fluid">				
				<p><?php echo $this->translate('You can now log in using your new password');?>.</p>
				<p class="change-password-link"><a href="<?php echo $this->url('frontend/zfcuser/login', array('channel' => $this->channel)) ?>">> <?php echo $this->translate('Login');?></a></p>
			</div>
			
		</div>
	</div>
</div>