<?php
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>

<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-default right')) ?>

<h1><?php echo $this->translate('Edit Appli'); ?></h1>

<div class="facebook-admin">
    <?php echo $this->formHidden($form->get('id')); ?>
        
    <div class="form-group">
        <?php echo $this->formLabel($form->get('appId')); ?>
        <?php echo $this->formInput($form->get(('appId'))->setAttribute('class', 'form-control')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('appId'))) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('appSecret')); ?>
        <?php echo $this->formInput($form->get(('appSecret'))->setAttribute('class', 'form-control')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('appSecret'))) ?>
	</div>
</div>
    
<?php echo $this->form()->closeTag() ?>

