<?php
$fm = $this->flashMessenger()->setNamespace('playgroundcms')->getMessages();
if (isset($fm[0]))
{
    print '<div class="alert alert-success">' . $fm[0] . '</div>';
}
?>
<ul class="liste-buttons">
	<li class="btn-admin"></li>
</ul>

<h1>Liste des blocs dynamiques</h1>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th><?php echo $this->translate('Dynarea'); ?></th>
            <th><?php echo $this->translate('Dynablocks'); ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->activeDynareas as $dynarea => $dynablocks): ?>
            <tr>
                <td><?php echo $dynarea ?></td>
                <td><?php echo count($dynablocks);?></td>
    
                <?php $editLink = $this->url('admin/playgroundcmsadmin/dynablocks/create', array('dynareaId' => $dynarea));?>
                <?php $deleteLink = $this->url('admin/playgroundcmsadmin/dynablocks/remove', array('dynareaId' => $dynarea));?>
                <td><a href='<?php echo $editLink ?>'><?php echo $this->translate('Edit'); ?></a> | <a href='<?php echo $deleteLink ?>'><?php echo $this->translate('Delete'); ?></a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php //echo $this->paginationControl($this->blocks, 'Sliding', 'playground-cms/block/pagination_pagelist.phtml'); ?>

<h2><?php echo $this->translate('Available Dynareas'); ?></h2>

<ul class="list-group">
<?php foreach ($this->dynareas as $id => $attributes): ?>
    <?php if(!array_key_exists($id,$this->activeDynareas) ): ?>
        <li class="list-group-item">
            <a href="<?php echo $this->url('admin/playgroundcmsadmin/dynablocks/create', array('dynareaId' => $id))?>"> <?php echo $id . " : " . $attributes['title']?></a>
            <?php //echo $attributes['description']; ?>
            <?php //echo $attributes['location']; ?>
        </li>
    <?php endif;?>
<?php endforeach; ?>
</ul>
