<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<div class="return"><a href="<?php echo $this->url('admin/playgroundflow/domain/story');?>"><?php echo $this->translate('Retour'); ?></a></div>

<h1><?php echo $this->translate('Création'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div id="content">
        <div>
        	<?php echo $this->formInput($form->get('domainId')); ?>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('story')); ?>
	            <?php echo $this->formSelect($form->get('story')); ?>
	            <?php echo $this->formElementErrors($form->get('story')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('leaderboardType')); ?>
	            <?php echo $this->formSelect($form->get('leaderboardType')); ?>
	            <?php echo $this->formElementErrors($form->get('leaderboardType')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('points')); ?>
	            <?php echo $this->formInput($form->get('points')); ?>
	            <?php echo $this->formElementErrors($form->get('points')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('hint')); ?>
	            <?php echo $this->formInput($form->get('hint')); ?>
	            <?php echo $this->formElementErrors($form->get('hint')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('displayNotification')); ?>
	            <?php echo $this->formCheckbox($form->get('displayNotification')); ?>
	            <?php echo $this->formElementErrors($form->get('displayNotification')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('notification')); ?>
	            <?php echo $this->formTextarea($form->get('notification')); ?>
	            <?php echo $this->formElementErrors($form->get('notification')) ?>
	            <?php $this->QgCKEditor(
                    'notification',
                        array(
                            'BasePath' => $this->libAssetPath('js/ckeditor'),
                            'Width' => "50%",
                            'Height' => "150",
                            'filebrowserBrowseUrl' => '/elfinder', // eg. 'includes/elFinder/elfinder.html'
                            'uiColor' => '#9AB8F3',
                            //'Color' => "#000",
                            'Toolbar'=> array(
                                 array('Source','Maximize'),
                                 array('Templates','Styles','Format'),
                                 array('Bold','Italic','Underline','Subscript','Superscript'),
                                 array('NumberedList','BulletedList','Outdent','Indent'),
                                 array('JustifyLeft','JustifyCenter','JustifyRight'),
                                 array('Link','Unlink'),
                                 array('Image','Table')
                             )
                        )
                    );
                ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('displayActivityStream')); ?>
	            <?php echo $this->formCheckbox($form->get('displayActivityStream')); ?>
	            <?php echo $this->formElementErrors($form->get('displayActivityStream')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('activityStream')); ?>
	            <?php echo $this->formTextarea($form->get('activityStream')); ?>
	            <?php echo $this->formElementErrors($form->get('activityStream')) ?>
	            <?php $this->QgCKEditor(
                    'activityStream',
                        array(
                            'BasePath' => $this->libAssetPath('js/ckeditor'),
                            'Width' => "50%",
                            'Height' => "150",
                            'filebrowserBrowseUrl' => '/elfinder', // eg. 'includes/elFinder/elfinder.html'
                            'uiColor' => '#9AB8F3',
                            //'Color' => "#000",
                            'Toolbar'=> array(
                                 array('Source','Maximize'),
                                 array('Templates','Styles','Format'),
                                 array('Bold','Italic','Underline','Subscript','Superscript'),
                                 array('NumberedList','BulletedList','Outdent','Indent'),
                                 array('JustifyLeft','JustifyCenter','JustifyRight'),
                                 array('Link','Unlink'),
                                 array('Image','Table')
                             )
                        )
                    );
                ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('countLimit')); ?>
	            <?php echo $this->formInput($form->get('countLimit')); ?>
	            <?php echo $this->formElementErrors($form->get('countLimit')) ?>
			</div>
			<div class="label-input file">
        	    <?php echo $this->formLabel($form->get('uploadPicto')); ?>
        	    <?php echo $this->formFile($form->get('uploadPicto')); ?>
        	    <?php if($form->get('picto')->getValue() != ''):?>
        	    	<img src="<?php echo $this->basePath($form->get('picto')->getValue()); ?>" />
        	    <?php endif;?>
            </div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('conditionsUrl')); ?>
	            <?php echo $this->formInput($form->get('conditionsUrl')); ?>
	            <?php echo $this->formElementErrors($form->get('conditionsUrl')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('conditionsXpath')); ?>
	            <?php echo $this->formInput($form->get('conditionsXpath')); ?>
	            <?php echo $this->formElementErrors($form->get('conditionsXpath')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('eventBeforeUrl')); ?>
	            <?php echo $this->formInput($form->get('eventBeforeUrl')); ?>
	            <?php echo $this->formElementErrors($form->get('eventBeforeUrl')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('eventBeforeXpath')); ?>
	            <?php echo $this->formInput($form->get('eventBeforeXpath')); ?>
	            <?php echo $this->formElementErrors($form->get('eventBeforeXpath')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('eventAfterUrl')); ?>
	            <?php echo $this->formInput($form->get('eventAfterUrl')); ?>
	            <?php echo $this->formElementErrors($form->get('eventAfterUrl')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('eventAfterXpath')); ?>
	            <?php echo $this->formInput($form->get('eventAfterXpath')); ?>
	            <?php echo $this->formElementErrors($form->get('eventAfterXpath')) ?>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>