<?php if ($this->pageCount): ?>
<div>
    <ul class="pagination">

        <!-- First page link -->
        <li<?php echo (isset($this->previous)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo $this->url('admin/playgroundflow/domain/story/attribute', array('p' => $this->first)); ?>">&lt;&lt;</a>
        </li>

        <!-- Previous page link -->
        <li<?php echo (isset($this->previous)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo $this->url('admin/playgroundflow/domain/story/attribute', array('p' => $this->previous)); ?>">&lt;</a>
        </li>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
        <li<?php echo ($page == $this->current) ? ' class="active"' : ''; ?>>
            <a href="<?php echo $this->url('admin/playgroundflow/domain/story/attribute', array('p' => $page)); ?>"><?php echo $page; ?></a>
        </li>
        <?php endforeach; ?>

        <!-- Next page link -->
        <li<?php echo (isset($this->next)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo $this->url('admin/playgroundflow/domain/story/attribute', array('p' => $this->next)); ?>">&gt;</a>
        </li>

        <!-- Last page link -->
        <li<?php echo (isset($this->next)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo $this->url('admin/playgroundflow/domain/story/attribute', array('p' => $this->last)); ?>">&gt;&gt;</a>
        </li>

    </ul>
</div>
<?php endif; ?>

<?php
$script = $this->inlineScript();
$script->appendScript(<<<'EOT'
    
$(".pagination .disabled a").click(function() {
  return false;
});

EOT
);
