<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<div class="return"><a href="<?php echo $this->url('admin/playgroundflow/domain/story');?>"><?php echo $this->translate('Retour'); ?></a></div>

<h1><?php echo $this->translate('Création'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div id="content">
        <div>
        	<?php echo $this->formInput($form->get(('domainId'))->setAttribute('class', 'form-control')); ?>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('story')); ?>
	            <?php echo $this->formSelect($form->get(('story'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('story'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('conditionsUrl')); ?>
	            <?php echo $this->formInput($form->get(('conditionsUrl'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('conditionsUrl'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('conditionsXpath')); ?>
	            <?php echo $this->formInput($form->get(('conditionsXpath'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('conditionsXpath'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('eventBeforeUrl')); ?>
	            <?php echo $this->formInput($form->get(('eventBeforeUrl'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('eventBeforeUrl'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('eventBeforeXpath')); ?>
	            <?php echo $this->formInput($form->get(('eventBeforeXpath'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('eventBeforeXpath'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('eventAfterUrl')); ?>
	            <?php echo $this->formInput($form->get(('eventAfterUrl'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('eventAfterUrl'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('eventAfterXpath')); ?>
	            <?php echo $this->formInput($form->get(('eventAfterXpath'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('eventAfterXpath'))) ?>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>