<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame'); ?>
<div class="game-postvote list-participant row wrap-game">
	<h1>
	    <?php echo $this->game->getTitle(); ?>
	</h1>
	<!-- BLOCK GAME START -->
	<div class="block-game game-play <?php if ($this->basePath($this->game->getSecondImage()) == "") echo "no-image"; ?>">
		<div class="img-content">
			<img class="rounded" src="<?php echo $this->basePath($this->game->getSecondImage()); ?>" />
			<?php if($this->game->getPartner()):?>
				<?php if( ($this->game->getPartner()->getLogo() != '')) : ?>
					<div class="logo-sponsor">
						<img src="<?php echo $this->basePath($this->game->getPartner()->getLogo());?>" alt="<?php echo $this->game->getPartner()->getName();?>" />
					</div>
				<?php endif;?>
			<?php else :?>
				<div class="logo-sponsor">
					<img src="<?php echo $this->frontendAssetPath('images/common/logo-game-start.png')?>" alt="logo" />
				</div>
			<?php endif;?>

			<div class="dark-overlay row">
				<h2 class="col-md-12">
				    <?php echo $this->translate('Post & Vote'); ?> <?php echo $this->translate('offered by'); ?> <?php if($this->game->getPartner()): echo $this->game->getPartner()->getName(); else:?>Playground<?php endif;?>
				</h2>
			</div>
		</div>
	</div>
	<!-- END BLOCK GAME START -->
	<!-- BLOCK CONTENT -->
	<div class="row search-bar">
        <div class="col-md-3">
            <select class="form-control" name="filter-postvote" id="filter-postvote">
                <option value="<?php echo $this->url('frontend/postvote/list', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'filter' => 'date'))?>"<?php if($this->filter == 'date') : echo ' selected'; endif; ?>>
                    <?php echo $this->translate('Latest'); ?>
                </option>
                <option value="<?php echo $this->url('frontend/postvote/list', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'filter' => 'random'))?>"<?php if($this->filter == 'random') : echo ' selected'; endif; ?>>
                    <?php echo $this->translate('Random'); ?>
                </option>
                <option value="<?php echo $this->url('frontend/postvote/list', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'filter' => 'vote'))?>"<?php if($this->filter == 'vote') : echo ' selected'; endif; ?>>
                    <?php echo $this->translate('Most popular'); ?>
                </option>
            </select>
        </div>
        <!-- <div class="clearfix"></div> -->
        <form action="<?php echo $this->url('frontend/postvote/list', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'filter' => $this->filter)); ?>" method="GET" class="row">
	        <div class="col-md-10 offset4 searchbar">	            
				<input class="form-control" type="text" name="name" id="" placeholder="<?php echo $this->translate('Search'); ?>" value="<?php echo $this->search?>"/>
	        </div>
	        <div class="col-md-2 btn-search">
	            <input type="submit" class="btn btn-default" value="<?php echo $this->translate('Search'); ?>" />
	        </div>
        </form>
    </div>
	<?php echo $this->paginationControl($this->posts, 'Sliding', 'playground-game/post-vote/pagination_list.phtml', array('id' => $this->game->getIdentifier(), 'filter' => $this->filter)); ?>
	<?php $form = $this->form;?>
	<?php $form->prepare();?>
	<div class="posts consultation-list-wrap<?php if(!$game->isStarted()):?> game-close<?php endif ?>">
			<?php foreach($this->posts as $post): ?>
				<div class="row">
					<div class="col-md-10">
						<?php if($this->game->getTemplate() == 'photo'): ?>
							<div class="photo-noslider">
								<?php if(isset($post['data'][1])):?>
									<h2>
									    <a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>">
									        <?php echo $post['data'][1];?>
									    </a>
									</h2>
								<?php endif ?>
							    <div class="couv-img">
							    	<?php if(isset($post['data'][2])):?>
							    		<a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>">
							    		    <img src="<?php echo $this->basePath($post['data'][2])?>" alt="" />
							    		</a>
							    	<?php elseif(isset($post['data'][3])):?>
							    		<a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>">
							    		    <img src="<?php echo $this->basePath($post['data'][3])?>" alt="" />
							    		</a>
							    	<?php elseif(isset($post['data'][4])):?>
							    		<a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>">
							    		    <img src="<?php echo $this->basePath($post['data'][4])?>" alt="" />
							    		</a>
							    	<?php elseif(isset($post['data'][5])):?>
							    		<a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>">
							    		    <img src="<?php echo $this->basePath($post['data'][5])?>" alt="" />
							    		</a>
							    	<?php elseif(isset($post['data'][6])):?>
							    		<a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>">
							    		    <img src="<?php echo $this->basePath($post['data'][6])?>" alt="" />
							    		</a>
							    	<?php endif;?>
							    </div>
								<p>
								    <?php if(isset($post['data'][7])): echo substr(nl2br($post['data'][7]), 0, 200); endif;?>...
								</p>
							</div>
						<?php elseif($this->game->getTemplate() == 'recipe'): ?>
							<?php if(isset($post['data'][1])):?>
								<h2>
								    <a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>">
								        <?php echo $post['data'][1];?>
								    </a>
								</h2>
							<?php endif ?>
							<?php if(isset($post['data'][2])):?>
								<div class="picture-kitchen">
								    <a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>">
								        <img src="<?php echo $this->basePath($post['data'][2])?>" />
								    </a>
								</div>
							<?php endif ?>
							<?php if(isset($post['data'][3])):?>
								<h3>
								    <?php echo $this->translate('Ingredients')?>
								</h3>
								<p>
								    <?php echo substr(nl2br($post['data'][3]), 0, 200); ?>...
								</p>
							<?php elseif(isset($post['data'][4])):?>
								<h3>
								    <?php echo $this->translate('Preparation')?>
								</h3>
								<p>
								    <?php echo substr(nl2br($post['data'][4]), 0, 200); ?>...
								</p>
							<?php elseif(isset($post['data'][5])): ?>
								<h3>
								    <?php echo $this->translate('Service')?>
								</h3>
								<p>
								    <?php echo substr(nl2br($post['data'][5]), 0, 200); ?>...
								</p>
							<?php endif ?>
						<?php else : ?>
							<h2>
							    <a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>">
							        <?php echo $post['data'][1] ?>
							    </a>
							</h2>
							<p>
							    <?php echo substr(nl2br($post['data'][2]), 0, 200); ?>...
							</p>
						<?php endif; ?>
						<p class="readmore postvote">
						    <a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id'])) ?>" class="btn btn-default" >
						        <?php echo $this->translate('Read more'); ?>
						    </a>
						</p>
						<?php echo $this->partial(
                            'playground-game/partial/name.phtml',
                            array('post'=> $post['user'],
                            'game' => $game,
                            'channel' => $this->channel,
                            'urlPost' => $this->url(
                                'frontend/postvote/post',
                                array(
                                    'id' => $this->game->getIdentifier(),
                                    'channel' => $this->channel,
                                    'post' => $post['id']),
                                    array('force_canonical' => true)
                                ),
                                'postTitle' => $post['data'][1]
                            )
                        ) ?>
						<?php if($game->isStarted()):?>
							<?php if($this->statusMail && ($post['id'] == $this->reportId )) : ?>
								<p class="report-result">
								    <?php echo $this->translate('Thank you for reporting'); ?>.
								</p>
							<?php else : ?>
								<?php echo $this->form()->openTag($form) ?>
									<?php echo $this->formInput($form->get('moderation')->setAttributes(array('class' => 'form-control'))); ?>
									<input type="hidden" name="link" value="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>" />
									<input type="hidden" name="reportid" value="<?php echo $post['id'] ?>" />
									<p class="alert-link">
									    <a href="#" class="btn btn-default">
									        <?php echo $this->translate('Report'); ?>
									    </a>
									</p>
								<?php echo $this->form()->closeTag($form) ?>
							<?php endif; ?>
						<?php endif ?>
					</div>
					<?php if($game->isStarted()):?>
					<div class="col-md-2">				    
				        <div class="nb-votes">
				        	<div class="already-voted">
				        	    <?php echo $this->translate('You have already voted !'); ?>
				        	</div>
				        <?php if(!$this->zfcUserIdentity() && $this->game->getVoteAnonymous()): ?>
				            <a href="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>" class="btn-post-vote"></a>
				        <?php elseif(!$this->zfcUserIdentity() && !$this->game->getVoteAnonymous()):?>
				            <a href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . '?redirect=' . $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id'])) ?>" class="btn-post-vote"></a>
				            <div class="bn-votes"><?php echo $this->translate('You must be registered to vote'); ?></div>
				        <?php elseif($this->zfcUserIdentity()):?>
				            <a href="<?php echo $this->url('frontend/postvote/vote', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post['id']))?>" class="btn-post-vote logged"></a>
				        <?php endif;?>
				            <div class="bn-votes"><span class="nb-post-vote-number"><?php echo $post['votes'];?></span> <?php echo ($post['votes'] > 1) ? 'votes' : 'vote'; ?></div>
				        </div>
					</div>
					<?php endif ?>
            </div>
        <?php endforeach; ?>
	 </div>
	 <div class="btn-group">
	 	<div id="participants">
	 		<a href="<?php echo $this->url('frontend/postvote/list', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'filter' => $this->game->getPostDisplayMode()))?>" class="btn btn-default">
		        <?php echo $this->translate('See participants'); ?>
		    </a>
	 	</div>
	 	<div class="btn-participate">
		 	<a href="<?php echo $this->url('frontend/postvote/play', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" class="btn btn-default">
		        <?php echo $this->translate('Participate'); ?>
	        </a>
	 	</div>
    </div>
	<?php
    	echo $this->paginationControl(
    	   $this->posts,
    	   'Sliding', 'playground-game/post-vote/pagination_list.phtml',
    	   array(
    	       'id' => $this->game->getIdentifier(),
        	   'channel' => $this->channel,
        	   'filter' => $this->filter
           )
        );
    ?>
</div>