<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('frontend/'. $this->game->getClassType() . '/play', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel)));
?>

<?php $totalQuestions = count($this->questions);?>
<!-- GAME QUIZ - FERME QUESTIONS -->
<div class="game-postvote play wrap-game">
	<h1>
	    <?php echo $this->game->getTitle(); ?>
	</h1>
    <?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game, 'channel' => $this->channel));?>
	<!-- Content -->
	<div id="content-article" class="content-game clearfix">
        <div class="col-md-12">
            <?php echo $this->game->getForm()->getDescription(); ?>
        </div>
        <div class="page col-md-12 clearfix">
			<?php
			echo $this->form()->openTag($form);
            foreach ($this->form as $element) :
        		$attributes = $element->getAttributes();
        		$required = $attributes['required'];
                $element->setAttributes(array('class' => 'form-control'));
        		$requiredContent = '';
				(!empty($required)) ? $requiredContent = '<span class="text-error">*</span>' : '';
				if ($element instanceof Zend\Form\Element\Text) : ?>
					<div class="form-group clearfix">
						 <label class="col-md-5">
					 	    <?php echo ($element->getLabel())? $this->formLabel($element) . ' ' . $requiredContent : ''; ?>
						 </label>
						 <div class="col-md-7">
						 	<?php echo $this->formText($element) ?>
							<?php echo $this->formElementErrors($element) ?>
						 </div>
					</div>
                <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
	                <div class="form-group clearfix">
                        <label class="col-md-5">
                            <?php echo ($element->getLabel()) ? $this->formLabel($element) . ' ' . $requiredContent : ''; ?>
		               	</label>
		               	<div class="col-md-7">
		               		<?php
		               		echo $this->formTextarea($element);
                            ?>
    						<?php echo $this->formElementErrors($element) ?>
		               	</div>
		               <div class="text-right col-md-11">
			               <span class="character-left"></span> 
			               <?php echo $this->translate('remaining characters'); ?>
			           </div>
			         </div>
                <?php elseif ($element instanceof Zend\Form\Element\File): ?>
                    <div class="photo-file form-group clearfix" data-url="<?php echo $this->url('frontend/'. $this->game->getClassType() . '/play/ajaxupload', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" data-canonical="<?php echo $this->url('frontend', array('channel' => $this->channel), array('force_canonical' => true)) ?>">
                    	<label class="col-md-5">
						    <?php echo ($element->getLabel()) ? $this->formLabel($element) . ' ' . $requiredContent :''; ?>
						    <br/>
    						<span class="annotation">
    						    500ko maximum
    						</span>
    					</label>
    					<div class="col-md-7">
                            <div class="preview-img">
                            <?php if($element->getValue() != ''):?>
                                <img class="preview" src="<?php echo $this->basePath($element->getValue());?>"/>
                                <a href="#"
                                    class="trash"
                                    data-delete="<?php echo $this->url('frontend/'. $this->game->getClassType() . '/play/ajaxdelete', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>"
                                    data-name="<?php echo $element->getName() ?>">
                                    <img src="<?php echo $this->frontendAssetPath('images/common/trash.png');?>" alt="Supprimer" />
                                </a>
                            <?php endif;?>
                            </div>
                                <div class="progress progress-striped">
                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" >
                                        <span class="sr-only">0% Complete (success)</span>
                                    </div>
                                </div>
                            <div class="wrap-progress">
                            </div>
                            <?php echo $this->formFile($element); ?>
                            <?php echo $this->formElementErrors($element) ?>
    					</div>
    				</div>
                <?php endif;?>
    	    <?php endforeach;?> 
            <p class="champs-obligatoitres">
                * <?php echo $this->translate('required fields'); ?>
            </p>
        
            <div class="row text-center">
                <button type="submit" name="submitPost" value="" class="btn btn-default btn-green">
                    <?php echo $this->translate('Preview'); ?>
                </button>
            </div>
        
            <?php echo $this->form()->closeTag() ?>
            <!-- FORM HANDLER LIVE UPLOAD PHOTO -->
            <form
               action="<?php echo $this->url('frontend/photocontestcreate', array('channel' => $this->channel)) ?>"
               enctype="multipart/form-data"
               target="upload_iframe"
               id="uploadform"
               method="post"
               style="display:none;" >
               </form>
	    </div>
                
        <div class="clearfix">
            <div class="btn btn-default btn-arrow-right">
                <a href="<?php echo $this->url('frontend/'. $this->game->getClassType() . '/list', array('id' => $this->game->getIdentifier(), 'filter' => $this->game->getPostDisplayMode(), 'channel' => $this->channel))?>">
                    <span class="left">left</span>
                    <span class="center"><?php echo $this->translate('See participants'); ?></span>
                    <span class="right">right</span>
                </a>
            </div>
        </div>
	</div>
</div>
<!-- END GAME QUIZ - FERME QUESTIONS-->