<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php $data = array();foreach($this->post->getPostElements() as $element):?>
<?php $data[$element->getPosition()] = $element->getValue();?>
<?php endforeach;?>
<div class="game-postvote wrap-game preview">
	<h1>
	    <?php echo $this->game->getTitle(); ?>
	</h1>
	
    <?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game, 'channel' => $this->channel));?>
    
    <div id="content-article" class="content-game clearfix">
	<!-- END BLOCK GAME START -->
        <form action="" method="post" name="preview_form" class="page form-preview">
            <div>
                <h2 class="col-md-12">
                    <?php echo $this->translate('Preview of your message'); ?>
                </h2>
                <p>
                    <?php echo $this->game->getForm()->getDescription(); ?>
                </p>
                <div class="col-md-12">
    				<div class="postvote-preview">
                   		<?php echo $this->partial('playground-game/post-vote/templates/' . $this->game->getTemplate(), array('data'=>$data, 'post'=>$this->post, 'channel' => $this->channel));?>
    					<div class="avatar">
					    	<?php if($this->post->getUser()->getAvatar()):?>
						        <img class="img-responsive" src="<?php echo $this->basePath($this->post->getUser()->getAvatar()) ?>" alt="<?php echo $this->post->getUser()->getFirstname(); ?> <?php echo $this->post->getUser()->getLastname(); ?>" />
						    <?php else:?>
					    		<?php if($this->post->getUser()->getTitle() && $this->post->getUser()->getTitle() == 'M'): ?>
					        		<img class="img-responsive" src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="no avatar" />
					    		<?php else: ?>
					    			<img class="img-responsive" src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="no avatar" />
					    		<?php endif; ?>
						    <?php endif;?>
						    <?php echo $this->post->getUser()->getUsername(); ?>
					    </div>
               		</div>
                </div>
                
                <div class="col-md-12 text-center clearfix">
                    <a class="btn btn-default btn-green" href="<?php echo $this->url('frontend/'. $this->game->getClassType() . '/play', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" class="btn btn-default modify">
                        <?php echo $this->translate('Modify'); ?>
                    </a>
                    <button type="submit" name="submitPost" value="" class="btn btn-default btn-green validate">
                        <?php echo $this->translate('Validate'); ?>
                    </button>
                </div>
            </div>
        </form>
    </div>
            
    <div class="clearfix">
        <div class="btn btn-default btn-arrow-right">
            <a href="<?php echo $this->url('frontend/'. $this->game->getClassType() . '/list', array('id' => $this->game->getIdentifier(), 'filter' => $this->game->getPostDisplayMode(), 'channel' => $this->channel))?>">
                <span class="left">left</span>
                <span class="center"><?php echo $this->translate('See participants'); ?></span>
                <span class="right">right</span>
            </a>
        </div>
    </div>
</div>
