<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundfacebook'); ?>
<?php
// TODO : refactor message display
$fm = $this->flashMessenger()->setNamespace('playgroundfacebook')->getMessages();
if (isset($fm[0]))
{
    echo '<span class="alert">' . $fm[0] . '</span>';
}
?>
<ul class="liste-buttons">
	<li class="btn-admin"><a href="<?php echo $this->url('admin/facebook/page/create');?>"><?php echo $this->translate('Add facebook page'); ?></a></li>
</ul>

<h1><?php echo $this->translate('Pages list'); ?></h1>

<?php if(!$this->fbLogged):?>
   <?php echo $this->translate('Facebook admin page message'); ?>
    <a href="<?php echo $this->fbLoginUrl ?>"><?php echo $this->translate('Facebook admin page link'); ?></a>
<?php endif;?>
<table class="table">
    <tr>
        <th><?php echo $this->translate('Page Id'); ?></th>
        <th><?php echo $this->translate('Page Name'); ?></th>
        <th></th>
    </tr>
    <?php foreach ($this->pages as $page): ?>
        <?php $editLink = $this->url('admin/facebook/page/edit', array('pageId' => $page['id']));?>
        <?php $deleteLink = $this->url('admin/facebook/page/remove', array('pageId' => $page['id']));?>
        <tr>
            <td><?php echo $page['pageId'] ?></td>
            <td><a href="<?php echo $page['pageLink'] ?>" target="_blank"><?php echo $page['pageName'] ?><br/>
                <img src="https://graph.facebook.com/<?php echo $page['pageId']?>/picture?type=large"/></a></td>
            <td></td>
            <td>
                <a href='<?php echo $editLink ?>'><?php echo $this->translate('Edit'); ?></a>
                <a href='<?php echo $deleteLink ?>'><?php echo $this->translate('Delete'); ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<ul class="liste-buttons bottom">
	<li class="btn-admin bottom"><a href="<?php echo $this->url('admin/facebook/page/create');?>"><?php echo $this->translate('Add facebook page'); ?></a></li>
</ul>

<?php //echo $this->paginationControl($this->apps, 'Sliding', 'playground-facebook/admin/pagination_applist.phtml'); ?>