<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundreward'); ?>
<?php
$fm = $this->flashMessenger()->setNamespace('playgroundreward')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}
?>

<ul class="liste-buttons">
    <li class="btn btn-default right margin-left10"><a href="<?php echo $this->url('admin/leaderboardtype/create');?>"><?php echo $this->translate('Add new Type'); ?></a></li>
</ul>

<h1><?php echo $this->translate('Reward list'); ?></h1>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th><?php echo $this->translate('Title'); ?></th>
            <th></th>
        </tr>
        <?php foreach ($leaderboardTypes as $leaderboardType) : ?>
            <tr>
                <th><?php echo $leaderboardType->getName(); ?></th>
                <th>
                    <a href="<?php echo $this->url('admin/leaderboardtype/edit', array('leaderboardId' => $leaderboardType->getId()));?>"><?php echo $this->translate('Editer');?></a>  |
                    <a href="<?php echo $this->url('admin/leaderboardtype/delete', array('leaderboardId' => $leaderboardType->getId()));?>"><?php echo $this->translate('Supprimer');?></a>
                </th>
            </tr>
        <?php endforeach; ?>
    </thead>
    <tbody>
    </tbody>
</table>

<?php // echo $this->paginationControl($this->rewards, 'Sliding', 'playground-reward/reward/pagination_rewardlist'); ?>
