<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounddesign');// Pour le texte ?>
<div class="row show-grid">
    <?php 
        $form = $this->form;
        $form->prepare();
        $form->get('submit')->setLabel('Validate');
        $type = 'add';
        if($form->get('title')->getValue() != '') {
            $type = 'edit';
        }
        echo $this->partial('playground-design/partial/menu.phtml', array('action' => $type, 'automaticTheme' => $automaticTheme));
        echo $this->form()->openTag($form);
    ?>
    <span class="col-md-6">
        <?php echo $this->formHidden($form->get('id')); ?>

        <div class="form-group">
            <label for="<?php echo $form->get('title')->getAttribute('name'); ?>">
                <?php echo $form->get('title')->getLabel(); ?>
            </label>
            <input name="<?php echo $form->get('title')->getAttribute('name'); ?>" type="text"
                value="<?php echo $form->get('title')->getValue(); ?>" class="form-control" />
            
            <?php if($this->formElementErrors($form->get('title')) != '') : ?>
            <div class="alert alert-danger">
                <?php echo $this->formElementErrors($form->get('title')); ?>
            </div>
            <?php endif; ?>
        </div>
        
        <ol class="breadcrumb form-inline">
            <li>
                <label for="<?php echo $form->get('theme_path')->getAttribute('name'); ?>">
                    <?php echo $form->get('theme_path')->getLabel(); ?>
                </label>
            <li>
            </li>
                <input name="<?php echo $form->get('area')->getAttribute('name'); ?>" type="text"
                    value="<?php echo $form->get('area')->getValue(); ?>" 
                        placeholder="<?php echo $form->get('area')->getAttribute('placeholder'); ?>" class="form-control" />
            </li>
            </li>
                <input name="<?php echo $form->get('package')->getAttribute('name'); ?>" type="text"
                    value="<?php echo $form->get('package')->getValue(); ?>" 
                        placeholder="<?php echo $form->get('package')->getAttribute('placeholder'); ?>" class="form-control" />
            </li>
            </li>
                <input name="<?php echo $form->get('theme')->getAttribute('name'); ?>" type="text"
                    value="<?php echo $form->get('theme')->getValue(); ?>" 
                        placeholder="<?php echo $form->get('theme')->getAttribute('placeholder'); ?>" class="form-control" />
            </li>
        </ol>
        
        <div class="form-group">
            <label for="<?php echo $form->get('author')->getAttribute('name'); ?>">
                <?php echo $form->get('author')->getLabel(); ?>
            </label>
            <input name="<?php echo $form->get('author')->getAttribute('name'); ?>" type="text"
                value="<?php echo $form->get('author')->getValue(); ?>" class="form-control" />
            
            <?php if($this->formElementErrors($form->get('author')) != '') : ?>
            <div class="alert alert-danger">
                <?php echo $this->formElementErrors($form->get('author')); ?>
            </div>
            <?php endif; ?>
        </div>
        
        <div class="form-group">
            
            <?php if($form->get('image')->getValue() != ''):?>
            <div class="thumbnail">
                <?php echo $this->formLabel($form->get('uploadImage')); ?>
                <img  data-src="holder.js/300x200" style="width: 300px; height: 200px;"src="<?php echo $this->basePath($form->get('image')->getValue()); ?>" />
            </div>
            <?php endif;?>
                
            <label for="<?php echo $form->get('uploadImage')->getAttribute('name'); ?>">
                <?php echo $form->get('uploadImage')->getLabel(); ?>
            </label>
            <input name="<?php echo $form->get('uploadImage')->getAttribute('name'); ?>" type="file"
                value="<?php echo $form->get('uploadImage')->getValue(); ?>" class="form-control" />
            
            <?php if($this->formElementErrors($form->get('uploadImage')) != '') : ?>
            <div class="alert alert-danger">
                <?php echo $this->formElementErrors($form->get('uploadImage')); ?>
            </div>
            <?php endif; ?>
                
                <?php /* echo $this->formFile($form->get('uploadImage')); */ ?>
        </div>
    </span>
</div>
<div class="row show-grid">
    <div class="col-md-12">
        <?php echo $this->formButton($form->get('submit')) ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>