<?php
$this->plugin('translate')->setTranslatorTextDomain('playgroundgame');
$game = $this->game;
$user = $this->user;
$availableGames = $this->availableGames
?>
<div class="game-postvote recirculation row">
	<!-- BOUNCE -->
	<?php echo $this->partial('playground-game/partial/bounce', array(
		'game' => $game,
		'user' => $user,
		'gameType' => 'Ce post &amp; vote',
		'facebooktemplate' => $this->layout()->facebooktemplate,
		'channel' => $this->channel,
		'isSubscriber' => $this->partnerSubscriber($game->getPartner(), $user) )
	);?>
	<!-- OTHER GAMES -->
	<?php if(!$this->layout()->facebooktemplate) : ?>
	<div class="row other-games">
		<h2 class="title">
			<?php if($availableGames): ?>
				<?php echo $this->translate('Tentez votre chance avec d\'autres jeux'); ?> Playground
			<?php else: ?>
				<?php echo $this->translate('Vous avez joué à tous les jeux'); ?> ! <br/>
				<?php echo $this->translate('Revenez très bientôt'); ?>
			<?php endif; ?>
		</h2>
		<?php $this->partialLoop()->setObjectKey('game')?>
		<?php echo $this->partialLoop('playground-game/partial/game.phtml', $availableGames) ?>
	</div>
	<?php endif; ?>
	<!-- RSS FEED -->
	<?php echo $this->partial('playground-game/partial/news-feed', array('rssUrl' => $this->rssUrl, 'channel' => $this->channel)); ?>
</div>
