<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame'); ?>
<div class="col-md-4 mobile sidebar game-sidebar">
	<div class="row">
		<!-- COLUMNBLOCK1 (if not null) -->
		<?php if($this->game->getColumnBlock1() != ''):?>
			<div class="sd-block block-custom">
				<?php echo $this->game->getColumnBlock1();?>
			</div>
		<?php endif; ?>
		<!-- END COLUMNBLOCK1 -->
		<!-- ADSERVING SIDEBAR -->
		<?php //echo $this->partial('application/index/partial/col-adserving.phtml', array('cat2' => 'game', 'cat3' => '&EASTgameid='.$this->game->getId(), 'channel' => $this->channel)); ?>
		<!-- END ADSERVING SIDEBAR -->
		<!-- COLUMNBLOCK2 (if not null) -->
		<?php if($this->game->getColumnBlock2() != ''):?>
		<div class="sd-block block-custom">
			<?php echo $this->game->getColumnBlock2();?>
		</div>
		<?php endif;?>
		<!-- END COLUMNBLOCK2 -->
		<?php if(($this->playgroundDynablock('game'.$this->game->getId())) != ''):?>
	    	<?php foreach($this->playgroundDynablock('game'.$this->game->getId()) as $block): ?>
	    		<div class="sd-block ad">
	    		    <?php echo $block ?>
	    		</div>
	    	<?php endforeach; ?>
    	<?php endif; ?>
		<div id="sidebar-game" class="sd-block">
			<p class="green">
			    <?php echo $this->translate('How to participate ?'); ?>
			</p>
			<div id="reply" class="row">
				<div class="col-md-2">
					<img src="<?php echo $this->frontendAssetPath('images/common/btn-reply.png') ?>" alt="" />
				</div>
				<div class="col-md-10">
					<p>
					    <?php echo $this->translate('Click to participate'); ?>
					</p>
				</div>
			</div>
			<div id="quiz-question" class="row">
				<div class="col-md-2">
					<img src="<?php echo $this->frontendAssetPath('images/common/btn-edit.png') ?>" alt="" />
				</div>
				<div class="col-md-10">
					<p>
					    <?php echo $this->translate('Write your message'); ?>
					</p>
				</div>
			</div>
			<div id="ecusson" class="row">
				<div class="col-md-2">
					<img src="<?php echo $this->frontendAssetPath('images/common/btn-parrain.png') ?>" alt="" />
				</div>
				<div class="col-md-10">
					<p>
					    <?php echo $this->translate('Invite your friends to vote for you !'); ?>
					</p>
				</div>
			</div>
		</div>
		<!-- COLUMNBLOCK3 (if not null) -->
		<?php if($this->game->getColumnBlock3() != ''):?>
			<div class="sd-block block-custom">
				<?php echo $this->game->getColumnBlock3();?>
			</div>
		<?php endif;?>
		<!-- END COLUMNBLOCK3 -->
	</div>
</div>
