<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame'); ?>
<div class="col-md-4 mobile sidebar game-sidebar">
	<div class="row">
		<!-- COLUMNBLOCK1 (if not null) -->
		<?php if($this->game->getColumnBlock1() != ''):?>
			<div class="sd-block block-custom">
				<?php echo $this->game->getColumnBlock1();?>
			</div>
		<?php endif; ?>
		<!-- END COLUMNBLOCK1 -->
		<!-- ADSERVING SIDEBAR -->
		<?php //echo $this->partial('application/index/partial/col-adserving.phtml', array('cat2' => 'game', 'cat3' => '&EASTgameid='.$this->game->getId(), 'channel' => $this->channel)); ?>
		<!-- END ADSERVING SIDEBAR -->
		<!-- COLUMNBLOCK2 (if not null) -->
		<?php if($this->game->getColumnBlock2() != ''):?>
		<div class="sd-block block-custom">
			<?php echo $this->game->getColumnBlock2();?>
		</div>
		<?php endif;?>
		<!-- END COLUMNBLOCK2 -->
		<?php if(($this->playgroundDynablock('game'.$this->game->getId())) != ''):?>
	    	<?php foreach($this->playgroundDynablock('game'.$this->game->getId()) as $block): ?>
	    		<div class="sd-block ad">
	    		    <?php echo $block ?>
	    		</div>
	    	<?php endforeach; ?>
    	<?php endif; ?>
		<div id="sidebar-game">
			<div class="sd-block participate">
				<img src="<?php echo $this->frontendAssetPath('images/common/icon-participate.png')?>" alt="participate" />
	            <h5><?php echo $this->translate('How to participate ?'); ?></h5>
	            
	            <div class="sb-content">
	            	<ul id="reply" class="row links-list">
		            	<li><?php echo $this->translate('Click to participate'); ?></li>
		            	<li><?php echo $this->translate('Write your message'); ?></li>
		            	<li><?php echo $this->translate('Invite your friends to vote for you !'); ?></li>
		            </ul>
	            </div>
			</div>
		</div>
		<!-- COLUMNBLOCK3 (if not null) -->
		<?php if($this->game->getColumnBlock3() != ''):?>
			<div class="sd-block block-custom">
				<?php echo $this->game->getColumnBlock3();?>
			</div>
		<?php endif;?>
		<!-- END COLUMNBLOCK3 -->
	</div>
</div>
