<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');
$data = array();foreach($this->post->getPostElements() as $element){
    $data[$element->getPosition()] = $element->getValue();
}
?>
<div class="game-postvote post row">
	<h1>
	    <?php echo $this->game->getTitle(); ?>
	</h1>
	<!-- BLOCK GAME START -->
	<div class="block-game game-play <?php if ($this->basePath($this->game->getSecondImage()) == "") echo "no-image"; ?>">
		<div class="img-content">
			<img class="rounded" src="<?php echo $this->basePath($this->game->getSecondImage()); ?>" />
			<?php if($this->game->getPartner()):?>
				<?php if( ($this->game->getPartner()->getLogo() != '')) : ?>
					<div class="logo-sponsor">
						<img src="<?php echo $this->basePath($this->game->getPartner()->getLogo());?>" alt="<?php echo $this->game->getPartner()->getName();?>" />
					</div>
				<?php endif;?>
			<?php else :?>
				<div class="logo-sponsor">		
					<img src="<?php echo $this->frontendAssetPath('images/common/logo-game-start.png')?>" alt="logo" />
				</div>
			<?php endif;?>
			<div class="dark-overlay row">
				<div class="postvote">
				    <?php echo $this->translate('Post & Vote'); ?>
				        offert par 
			        <?php if($this->game->getPartner()): echo $this->game->getPartner()->getName(); else:?>
				        Playground
			        <?php endif;?>
				</div>
			</div>
		</div>
	</div>
    <!-- END BLOCK GAME START -->
    <!-- BLOCK CONTENT -->
    <div class="btn-group">
		<a href="<?php echo $this->url('frontend/postvote', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" class="btn btn-default">
            Accueil
        </a>
		<a href="<?php echo $this->url('frontend/postvote/list', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'filter' => $this->game->getPostDisplayMode()))?>" class="btn btn-default">
            Voir les participations
        </a>
		</div>
		<?php if($game->isStarted()):?>
			<a href="<?php echo $this->url('frontend/postvote/play', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" class="btn btn-default">
			    Participer
			</a>
		<?php endif ?>
	</div>
    <!-- BLOCK CONTENT -->
    <div class="row posts">
        <div class="col-md-10">
            <div class="row rounded backgrey">
            	<?php if(count($this->flashMessages)>0):?>
					<p class="already-play"><?php echo $this->flashMessages[0]; ?></p>
			    <?php
			    endif;
           		echo $this->partial(
                    'playground-game/post-vote/templates/' . $this->game->getTemplate(),
                    array(
                        'data'=>$data,
                        'channel' => $this->channel,
                        'post' => $post->getId()
                    )
                );
				echo $this->partial(
    				'playground-game/partial/name.phtml',
    				array(
    				    'post' => $post->getUser(),
    				    'game' => $game,
    				    'channel' => $this->channel,
    				    'urlPost' => $this->url(
                            'frontend/postvote/post',
        				    array(
            				    'id' => $this->game->getIdentifier(),
            				    'channel' => $this->channel,
                                'post' => $post->getId()),
                                array(
                                    'force_canonical' => true
                                )
                            ),
                        'postTitle' => $data[1]
                        )
                    );
				?>
       		</div>
       		<?php if($game->isStarted()):?>
	       		<?php if($this->statusMail && ($post->getId() == $this->reportId )) : ?>
					<p class="report-result">Merci d'avoir signalé.</p>
				<?php else : ?>
		       		<?php $formModeration = $this->formModeration; ?>
					<?php $formModeration->prepare(); ?>
		       		<?php echo $this->form()->openTag($formModeration); ?>
						<?php echo $this->formInput($formModeration->get('moderation')->setAttributes(array('class' => 'form-control'))); ?>
						<input type="hidden" name="link" value="<?php echo $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $post->getId()))?>" />
						<input type="hidden" name="reportid" value="<?php echo $post->getId() ?>" />
						<p class="alert-link">
						    <a href="#" class="btn btn-default">
						        Signaler
						    </a>
						</p>
					<?php echo $this->form()->closeTag($formModeration) ?>
				<?php endif; ?>
			<?php endif ?>
       </div>
       <?php if($game->isStarted()):?>
       <div class="col-md-2">
           <?php 
                $form = $this->form;
                $form->setAttribute(
                    'action',
                    $this->url('frontend/postvote/post',
                        array(
                            'id' => $this->game->getIdentifier(),
                            'channel' => $this->channel,
                            'post' => $post->getId()
                        )
                    )
                );
                $form->prepare();
                echo $this->form()->openTag($form);
            ?>
            <?php if(!$this->zfcUserIdentity() &&  $this->game->getVoteAnonymous() && ! $this->voted ): ?>
                <div class="vote">
                    <?php echo $this->formRow($form->get('captcha')); ?>
                </div>
            <?php elseif(!$this->zfcUserIdentity() && ! $this->game->getVoteAnonymous()):?>
                <div class="vote">
                    Vous devez être 
                    <a href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . '?redirect=' . $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $this->post->getId())) ?>"> 
                        inscrit
                    </a>
                    pour voter
                </div>
            <?php endif ?>
            <?php if ($this->post->getStatus() == 2) : ?>
	            <div class="row <?php if($this->zfcUserIdentity()): ?>logged<?php endif ?> nb-votes<?php echo ($this->voted)?'-check':'';?>">
	            	<?php if($this->alreadyVoted) : ?>
	            	    <div class="already-voted">
	            	        <?php echo $this->alreadyVoted; ?>
	            	    </div>
	            	<?php endif; ?>
	                <?php if($this->voted):?>
	                    <img src="<?php echo $this->frontendAssetPath('images/common/icon-check.png');?>" />
	                <?php elseif($this->zfcUserIdentity() ||  $this->game->getVoteAnonymous()):?>
	                    <input type="image" src="<?php echo $this->frontendAssetPath('images/common/round-vote.png');?>" alt="Voter">
	                <?php elseif(! $this->game->getVoteAnonymous()):?>
	                    <a href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . '?redirect=' . $this->url('frontend/postvote/post', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel, 'post' => $this->post->getId())) ?>">
	                       <img src="<?php echo $this->frontendAssetPath('images/common/round-vote.png');?>" />
                        </a>
	                <?php endif;?>
	                <div class="bn-votes text-warning">
	                    <span class="nb-post-vote-number">
	                        <?php echo count($this->post->getVotes())?>
	                    </span> 
	                    <?php echo (count($this->post->getVotes()) > 1) ? 'votes' : 'vote'; ?>
                    </div>
	            </div>
            <?php endif ?>
            <?php echo $this->form()->closeTag();?>
        </div>
        <div class="col-md-12 humain">
            <?php if(!$this->zfcUserIdentity()): ?>
                <span class="text-error">*</span> 
                Pour prendre en compte votre vote, nous devons vérifer que vous êtes bien un être humain ;-)
            <?php endif ?>
        </div>
        <?php endif ?>
    </div>
</div>