<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundcms');// Pour le texte ?>

<h1><?php echo $this->translate('Block'); ?></h1>

<?php

$form = $this->createBlockForm;
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>
<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')) ?>
<div class="tab-pane active" id="general">
    <div>
        <div class="label-input">
        <?php echo $this->formHidden($form->get('id')); ?>
        </div>

        <div class="label-input">
        <?php echo $this->formLabel($form->get('title')); ?>
        <?php echo $this->formInput($form->get('title')); ?>
        <?php echo $this->formElementErrors($form->get('title')) ?>
        </div>

        <div class="label-input">
        <?php echo $this->formLabel($form->get('identifier')); ?>
        <?php echo $this->formInput($form->get('identifier')); ?>
        <?php echo $this->formElementErrors($form->get('identifier')) ?>
        </div>
        
        <div class="label-input">
            <?php echo $this->formLabel($form->get('is_active')); ?>
            <?php echo $this->formSelect($form->get('is_active')); ?>
            <?php echo $this->formElementErrors($form->get('is_active')) ?>
		</div>
		
		<div class="label-input">
            <?php echo $this->formLabel($form->get('on_call')); ?>
            <?php echo $this->formCheckbox($form->get('on_call')); ?>
            <?php echo $this->formElementErrors($form->get('on_call')) ?>
		</div>
		
		<div class="label-input ckeditor">
            <?php echo $this->formLabel($form->get('content')); ?>
            <?php echo $this->formTextArea($form->get('content')); ?>
            <?php echo $this->formElementErrors($form->get('content')); ?>
            <?php $this->QgCKEditor(
                'content',
                    array(
                    	'BasePath' => $this->adminAssetPath('js/lib/ckeditor'),
                    	'Width' => "50%",
                        'Height' => "100",
                        'filebrowserBrowseUrl' => '/elfinder', // eg. 'includes/elFinder/elfinder.html'
                        'uiColor' => '#9AB8F3',
                        //'Color' => "#000",
                        'Toolbar'=> array(
                             array('Source','Maximize'),
                             array('Templates','Styles','Format'),
                             array('Bold','Italic','Underline','Subscript','Superscript'),
                             array('NumberedList','BulletedList','Outdent','Indent'),
                             array('JustifyLeft','JustifyCenter','JustifyRight'),
                             array('Link','Unlink'),
                             array('Image','Table')
                         )
                    )
                );
            ?>
    	</div>

    </div>
</div>
<?php echo $this->form()->closeTag() ?>
