<?php
$this->plugin('translate')->setTranslatorTextDomain('playgroundgame');
$game = $this->game;
$user = $this->user;
$isSubscriber = $this->isSubscriber;
if(!$game->getPartner() || !$game->getPartner()->getBouncePage()):
?>
	<div class="mobile col-md-2">
		<img src="<?php echo $this->frontendAssetPath('images/common/logo-hd.png')?>" alt="Playground" class="partenaire-logo" />
	</div>
    <h2 class="col-md-10">
        <?php echo $this->gameType ?> vous a été offert par 
        <span class="mobile name-partner">Playground</span>
    </h2>
    <div class="row offer">
    	<div class="col-md-2 no-mobile">
			<img src="<?php echo $this->frontendAssetPath('images/common/logo-hd.png')?>" alt="Logo" class="partenaire-logo" />
		</div>
		<?php if(!$user->getAvatar() || !$user->getAddress() || !$user->getCity() || !$user->getTelephone() || !$user->getChildren()):?>
			<div class="col-md-3<?php if($this->facebooktemplate): echo ' fb-target'; endif ?>">
		    	<a href="<?php if(!$this->facebooktemplate) : echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel)); else : echo 'http://'.$this->channel['platform'].$this->url('frontend/zfcuser/profile', array('channel' => $this->channel)); endif; ?>">
			        <img src="<?php echo $this->frontendAssetPath('images/common/round-pencil.png')?>" />
	                <div>
	                    Remplir mes <br> coordonnées<br>
	                    <span class="points">et gagnez des points</span>
	                </div>
	           	</a>
		    </div>
	    <?php endif;?>
	    <?php if(!$user->getOptin()):?>
	    	<div class="col-md-3">
	    		<div class="bounce-newsform">
				    <form action="<?php echo $this->url('frontend/zfcuser/ajax_newsletter', array('channel' => $this->channel));?>" method="POST" id="ajax-newsletter">
				        <input type="hidden" value="1" name="optin" />
				    	<input class="btn btn-orange" class="bounce-newssubscribe" type="submit" value="La newsletter"/>
				    </form>
				</div>
				<div class="bounce-newssuccess">
				    Inscription prise
				    <br/>en compte!
				</div>
			</div>
	    <?php endif;?>
	    <div class="col-md-3">
	    	<a href="http://www.facebook.com/playground" target="_blank" class="facebook">
                <img src="<?php echo $this->frontendAssetPath('images/common/round-facebook-circle.png')?>" />
                <div>Devenir fan <br/>sur Facebook</div>
            </a>
	    </div>
    </div>
<?php else:?>
	<h2>
	    <?php echo $this->gameType ?> vous a été offert par <?php echo $game->getPartner()->getName();?>
	</h2>
    <div class="row offer partner">
    	<?php if($game->getPartner()->getLogo()):?>
			<div class="col-md-3">
				<img src="<?php echo $this->basePath($game->getPartner()->getLogo())?>" alt="<?php echo $game->getPartner()->getName();?>" />
			</div>
		<?php endif;?>
		<?php if($game->getPartner()->getNewsletter() && !$isSubscriber):?>
		    <div class="col-md-3">
	    		<div class="bounce-newsform">
				    <form action="<?php echo $this->url('frontend/partnership/ajax_newsletter', array('id' => $game->getPartner()->getId(), 'channel' => $this->channel));?>" method="POST" id="ajax-newsletter">
				        <input type="hidden" value="1" name="optin" />
				        <input type="hidden" value="<?php echo $game->getId();?>" name="gameId" />
				    	<input class="bounce-newssubscribe" type="submit" value="S'inscrire à la newsletter"/>
				    </form>
				</div>
				<div class="bounce-newssuccess">
				    Inscription prise
				    <br/>en compte!
				</div>
			</div>
		<?php endif;?>
		<?php if($game->getPartner()->getWebsite()):?>
			<div class="col-md-3">
		    	<a href="<?php echo $game->getPartner()->getWebsite()?>" target="_blank" class="website">
					<div>
					    Voir le <br/>
					    site Internet
					</div>
				</a>
			</div>
		<?php endif;?>
		<?php if($game->getPartner()->getFacebook()):?>
			<div class="col-md-3">
		        <a href="<?php echo $game->getPartner()->getFacebook()?>" target="_blank" class="facebook">
					<div>
					    Devenir fan <br/>
					    sur Facebook
					</div>
				</a>
			</div> 
		<?php endif;?>
	</div>
<?php endif;?>