<?php $achievements    = $this->activityWidget();?>
<?php $leaderboard     = $this->leaderboardWidget();?>
<?php $leaderboardWeek = $this->leaderboardWidget('','week');?>
<?php $baseUrl         = $this->url('frontend', array('channel' => $this->channel), array('force_canonical' => true)); ?>

<div class="sidebar col-md-4">

    <!-- BLOCK NEWSLETTER -->
	<?php if($this->zfcUserIdentity() && ! $this->zfcUserIdentity()->getOptin()): ?>
	    <div class="sb-block newsletter-connect">
	    	<img src="<?php echo $this->frontendAssetPath('images/common/icon-newsletter.png')?>" alt="newsletter" />
	    	<h5 class="sb-block-title">Inscrivez-vous à la newsletter et ne ratez aucun jeu !</h5>
			<div class="sb-block-content">
			    <form action="<?php echo $this->url('frontend/zfcuser/ajax_newsletter', array('channel' => $this->channel));?>" method="POST" id="ajax-newsletter">
			        <input type="hidden" value="1" name="optin" />
			    	<input class="btn btn-default up" type="submit" value="Je m’inscris !"/>
			    </form>
			    <div class="suscribe-success">Merci, votre inscription est bien prise en compte!</div>
			</div>
	    </div>
    <?php endif; ?>
    <!-- END BLOCK NEWSLETTER -->

    <?php if(($this->playgroundDynablock('column_home')) != ''):?>
    	<?php foreach($this->playgroundDynablock('column_home') as $block): ?>
    		<div class="sb-block ad"><?php echo $block ?></div>
    	<?php endforeach; ?>
    	<?php //echo $this->playgroundDynablock('column_home') ;?>
    <?php endif; ?>

	<!-- BLOCK TONNES CADEAUX -->
	<?php if(!$this->zfcUserIdentity()): ?>
	    <div class="sb-block tonnes-cadeaux">
	    	<img src="<?php echo $this->frontendAssetPath('images/common/icon-gifts.png')?>" alt="gifts" />
            <h5>Gagnez des tonnes de cadeaux !</h5>
	    	<div class="sb-content">
		    	<div class="txt">Inscrivez-vous sur Playground et participez aux jeux concours de nos partenaires pour gagner pleins de cadeaux.</div>
		    	<div class="accroche">Playground est 100% gratuit !</div>
		    	<a class="btn btn-default up" href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Je m’inscris !</a>
		    	<a class="btn btn-inverse" href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Connexion</a>
		    </div>
	    </div>
    <?php endif; ?><!-- END BLOCK TONNES CADEAUX -->

    <!-- ADSERVING SIDEBAR -->
    <?php //echo $this->partial('application/index/partial/col-adserving.phtml', array('cat1' => $this->cat1, 'cat2' => $this->cat2, 'cat3' => $this->cat3, 'channel' => $this->channel)); ?>
    <!-- END ADSERVING SIDEBAR -->

    <!-- BLOCK FACEBOOK -->
    <div class="sb-block fb-box">
    	<h5>Rejoignez-nous sur Facebook</h5>
    	<div class="sb-content">
    	   <div class="fb-like-box" data-href="http://www.facebook.com/adfabagency" data-width="280" data-height="291" data-show-faces="true" data-stream="false" data-border-color="#eeefef" data-header="false"></div>
	    </div>
    </div><!-- END BLOCK FACEBOOK -->

    <!-- BLOCK NEWSLETTER -->
    <!-- <?php if(!$this->zfcUserIdentity()): ?>
    	    <div class="sb-block newsletter">
    	    	<img src="<?php echo $this->frontendAssetPath('images/common/icon-newsletter.png')?>" width="82" height="81" border="0" alt="newsletter" />
    			<div class="bg-sdblock">
    				<p class="green">Inscrivez-vous à la newsletter et ne ratez aucun jeu !</p>
    		    	<form action="" method="POST">
    		    		<input class="input" type="email" name="email" value="Votre adresse email" onclick="if(this.value=='Votre adresse email'){this.value=''}" onblur="if(this.value==''){this.value='Votre adresse email'} " />
    		    		<input class="btn btn-greendark" type="submit" value="Ok"/>
    		    	</form>
    		    </div>
    	    </div>
    <?php endif; ?> -->
    <!-- END BLOCK NEWSLETTER -->

    <!-- BLOCK WIN POINTS -->
    <?php if($this->zfcUserIdentity()): ?>
		<div class="sb-block win-points">
			<img src="<?php echo $this->frontendAssetPath('images/common/icon-cup-home.png')?>" alt="cup" />
            <h5>Gagnez plus de points !</h5>
			<div class="sb-content">
				<ul class="links-list">
					<li class="coordonnees">
						<a href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel));?>" class="sb-picto-link">
						    <img src="<?php echo $this->frontendAssetPath('images/common/btn-coordonnees-hd.png')?>" alt="coordonnees" />
							Remplissez vos coordonnées<br />
							50 points
						</a>
					</li>
					<li class="parrain">
						<a href="<?php echo $this->url('frontend/sponsorfriends', array('channel' => $this->channel)); ?>" class="sb-picto-link">
                            <img src="<?php echo $this->frontendAssetPath('images/common/btn-parrain-hd.png')?>" alt="parrain" />
							Parrainez vos amis<br />
							100 points par amis parrainé
						</a>
					</li>
					<li class="partage">
						<a href="<?php echo $this->url('frontend/sponsorfriends', array('channel' => $this->channel)); ?>" class="sb-picto-link">
                            <img src="<?php echo $this->frontendAssetPath('images/common/btn-partage-hd.png')?>" alt="partage" />
							Partagez sur les réseaux sociaux<br />
							50 points
						</a>
					</li>
				</ul>
			</div>
		</div>
	<?php endif; ?><!-- END BLOCK WIN POINTS -->

    <!-- BLOCK HOW IT WORKS -->
    <div class="sb-block how-works">
    	<img src="<?php echo $this->frontendAssetPath('images/common/icon-question.png')?>" alt="question" />
    	<h5>Comment ça marche ?</h5>
		<div class="sb-content">
	    	<ul class="links-list">
	    		<li class="connect">
                    <img src="<?php echo $this->frontendAssetPath('images/common/btn-connect-account-hd.png')?>" alt="connect" />
	    		    <a href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Inscrivez-vous</a> ou<br />
	    		    <a href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">connectez-vous</a> à votre compte
    		    </li>
	    		<li class="game-play">
                    <img src="<?php echo $this->frontendAssetPath('images/common/btn-contest-play-hd.png')?>" alt="gameplay" />
	    		    <a href="<?php echo $this->url('frontend/jeuxconcours', array('channel' => $this->channel)); ?>">Participez aux jeux concours</a>
	    		    pour gagner des cadeaux
    		    </li>
	    		<li class="gain-points">
                    <img src="<?php echo $this->frontendAssetPath('images/common/btn-earn-points-hd.png')?>" alt="gain" />
                    Cumulez des points et obtenez des badges.
                </li>
	    	</ul>
	    	<a href="<?php echo $this->url('frontend/cms', array('id' => 'comment-ca-marche', 'channel' => $this->channel)); ?>">&gt; Voir comment gagner plus de points !</a>
	   </div>
    </div><!-- END BLOCK HOW IT WORKS -->

    <!-- BLOCK CLASSEMENT -->
    <div class="sb-block ranking">
        <img src="<?php echo $this->frontendAssetPath('images/common/icon-ranking.png')?>" alt="classement" />
    	<h5>
    	    <a href="<?php echo $this->url('frontend/reward/leaderboard', array('period'=>'general', 'channel' => $this->channel)); ?>">Classement</a>
    	</h5>
    	<div class="sb-content">
        	<div class="btn-group btn-group-justified">
        		<a href="#" class="btn btn-default up week active">Cette semaine</a>
        		<a href="#" class="btn btn-default up general">Général</a>
        	</div>
        	<ul class="list">
        	    <?php $i=1;foreach($leaderboard as $entry):?>
    				<li class="row general rank<?php echo $i?>">
    				    <div class="rank"><?php echo $i ?></div>
    					<div class="avatar">
    						<?php if($entry['avatar']): ?>
    							<img src="<?php echo $this->basePath($entry['avatar'])?>" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" />
    						<?php elseif($entry['title'] && $entry['title'] == 'M') : ?>
    							<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" width="33" height="33" border="0" />
    						<?php else : ?>
    							<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" width="33" height="33" border="0" />
    						<?php endif; ?>
    					</div>
    	    			<div class="name">
    	    				<?php
    	    				if($entry['username']):
    	    					echo $entry['username'];
    						else :
    							echo $entry['firstname'].' '.substr($entry['lastname'], 0, 1).'.';
    						endif;
    	    				?>
    	    			</div>
    	    			<div class="points">(<?php echo number_format($entry['points'], 0, ',', ' ' ); ?> points)</div>
    				</li>
    			<?php $i++;endforeach;?>
    
    			<?php $i=1;foreach($leaderboardWeek as $entry):?>
    				<li class="row week rank<?php echo $i?>">
                        <div class="rank"><?php echo $i ?></div>
    					<div class="avatar">
    						<?php if($entry['avatar']): ?>
    							<img src="<?php echo $this->basePath($entry['avatar'])?>" width="33" height="33" border="0" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" />
    						<?php elseif($entry['title'] && $entry['title'] == 'M') : ?>
    							<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" width="33" height="33" border="0" />
    						<?php else : ?>
    							<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" width="33" height="33" border="0" />
    						<?php endif; ?>
    					</div>
    	    			<div class="name">
    	    				<?php
    	    				if($entry['username']):
    	    					echo $entry['username'];
    						else :
    							echo $entry['firstname'].' '.substr($entry['lastname'], 0, 1).'.';
    						endif;
    	    				?>
    	    			</div>
    	    			<div class="points">(<?php echo number_format($entry['points'], 0, ',', ' ' );?> points)</div>
    				</li>
    			<?php $i++;endforeach;?>
    
        		<?php if($this->zfcUserIdentity()): ?>
        			<?php $rank =  $this->rankWidget($this->zfcUserIdentity()->getId());?>
    	    		<li class="row general current">
    					<div class="position">Votre position</div>
						<div class="avatar">
							<?php if($this->zfcUserIdentity()->getAvatar()):?>
								<img src="<?php echo $this->basePath($this->zfcUserIdentity()->getAvatar()) ?>" width="33" height="33" border="0" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" />
							<?php else:?>
								<?php if($this->zfcUserIdentity()->getTitle() && $this->zfcUserIdentity()->getTitle() == 'M'): ?>
	        			        	<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" width="33" height="33" border="0" />
	        			    	<?php else: ?>
	        			    		<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" width="33" height="33" border="0" />
	        			    	<?php endif; ?>
	        			    <?php endif;?>
						</div>
						<div class="points">
						    <?php echo number_format($rank['points'], 0, ',', ' ' );?> points<br />
							<?php echo $rank['rank']; ?><sup><?php echo ($rank['rank'] == 1)? 'ère':'ème'; ?></sup> position
						</div>
    				</li>
    				<?php $rank =  $this->rankWidget($this->zfcUserIdentity()->getId(), 'week');?>
    	    		<li class="row week current">
    					<div class="position">Votre position</div>
    					<div class="avatar">
    						<?php if($this->zfcUserIdentity()->getAvatar()):?>
    							<img src="<?php echo $this->basePath($this->zfcUserIdentity()->getAvatar()) ?>" width="33" height="33" border="0" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" />
    						<?php else:?>
    							<?php if($this->zfcUserIdentity()->getTitle() && $this->zfcUserIdentity()->getTitle() == 'M'): ?>
            			        	<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" width="33" height="33" border="0" />
            			    	<?php else: ?>
            			    		<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" width="33" height="33" border="0" />
            			    	<?php endif; ?>
            			    <?php endif;?>
                        </div>
						<div class="points">
						    <?php echo number_format($rank['points'], 0, ',', ' ' );?> points<br />
						    <?php echo $rank['rank']; ?><sup><?php echo ($rank['rank'] == 1)? 'ère':'ème'; ?></sup> position
					    </div>
    				</li>
    			<?php endif; ?>
        	</ul>
        	<a href="<?php echo $this->url('frontend/reward/leaderboard', array('period'=>'general', 'channel' => $this->channel)) ?>">&gt; Voir le classement général</a>
    	</div>
    </div>

    <!-- BLOC ACTIVITES RECENTES -->
    <?php if (count($achievements) > 0): ?>
	<div class="sb-block activities">
		<h5>Activités récentes</h5>
		<div class="sb-content">
    		<ul class="list">
        		<?php foreach($achievements as $achievement):?>
    			<li>
    				<div class="avatar">
    					<img src="<?php
    						if($achievement->getUser()->getAvatar()) :
    							echo $this->basePath($achievement->getUser()->getAvatar());
    						elseif($achievement->getUser()->getTitle() && $achievement->getUser()->getTitle() == 'M') :
    							echo $this->frontendAssetPath('images/user/no-avatar-small-h.png');
    						else :
    							echo $this->frontendAssetPath('images/user/no-avatar-small-f.png');
    						endif;
    					?>" width="33" height="33" border="0" alt="avatar" />
    				</div>
    				<div class="infos">
    					<span class="name">
    						<?php if($achievement->getUser()->getUsername()) :
    							echo $achievement->getUser()->getUsername();
    						else :
    							echo $achievement->getUser()->getFirstname().' '.substr($achievement->getUser()->getLastname(), 0, 1).'.';
    						endif; ?>
    					</span> a obtenu le badge <span class="badgename"><?php echo $achievement->getLabel() . " " . ucfirst(strtolower($achievement->getLevelLabel()));?></span></div>
    			</li>
    			<?php endforeach;?>
    		</ul>
		</div>
	</div>
	<?php endif; ?>
	<!-- END BLOC ACTIVITES RECENTES -->

	<?php
		try {
		    $channel = \Zend\Feed\Reader\Reader::import($this->rssUrl);
		} catch (Exception $e){
		    $channel = array();
		}

	?>
	<?php if(count($channel) > 0):?>
	<!-- BLOC NEWS -->
	<div class="sb-block news-feed">
		<h5>Sur TF1</h5>
        <div class="sb-content">
    		<?php $i=1; foreach ($channel as $item) : ?>
        		<?php if($i>5):?>
        		    <?php break;?>
        		<?php endif;?>
        		<?php if($i==1):?>
        		<div class="news-one row">
        			<p class="head-news">A la une</p>
        			<a href="<?php echo $item->getLink(); ?>" target="_blank">
        				<img src="<?php echo $item->getEnclosure()->url; ?>" alt="actualité à la une : <?php echo $item->getTitle(); ?>" />
        				<div class="title-news"><?php echo $item->getTitle(); ?></div>
        				<div class="content-news"><?php echo $item->getDescription(); ?></div>
        			</a>
        		</div>
        		<?php endif;?>
        		<?php if($i==2) :?>
        		<div class="news-list row">
        			<p class="head-news">Dans l’actu</p>
        			<ul>
        		<?php endif;?>
        		<?php if($i>=2):?>
        				<li <?php if($i&1) : echo 'class="right"'; endif; ?>>
        					<a href="<?php echo $item->getLink(); ?>" target="_blank">
        						<img src="<?php echo $item->getEnclosure()->url; ?>" height="63" border="0" alt="actualité : <?php echo $item->getTitle(); ?>" />
        						<div class="content-news"><?php echo $item->getTitle(); ?></div>
        					</a>
        				</li>
        		<?php endif;?>
        		<?php if($i==5):?>
        			</ul>
        		</div>
        		<?php endif;?>
    		<?php $i++; endforeach; ?>
		</div>
	</div><!-- END BLOC NEWS -->
	<?php endif;?>

</div>