<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounddesign');// Pour le texte ?>

<?php $badges =  $this->userBadges();?>

<?php $baseUrl = $this->url('frontend', array('channel' => $this->channel), array('force_canonical' => true)); ?>

<div id="fb-root">
</div>
<!-- ADSERVING LEFT -->
<div id="ad-left">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17603;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div><!-- ADSERVING LEFT -->

<!-- ADSERVING RIGHT -->
<div id="ad-right">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17603;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div><!-- END ADSERVING RIGHT -->

<!-- ADSERVING TOP -->
<div id="ad-top">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17604;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div>
<!-- END ADSERVING TOP -->

<!-- HEADER -->
<div class="wrap-header">
    <div class="header" id="header">
        
        <nav class="navbar navbar-default" role="navigation">
            
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-menu">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="logo-title" ><?php echo $this->translate('The first open source platform games!'); ?></div>
                
                <a class="navbar-brand" href="<?php echo $this->url('frontend', array('channel' => $this->channel)) ?>">
                    <img src="<?php echo $this->frontendAssetPath('images/common/logo-white.png')?>" alt="logo" />
                </a>
            </div>
                
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse-menu">
            <?php if(!$this->zfcUserIdentity()): ?>
                <?php echo $this->userLoginWidget(array('redirect' => $this->url('frontend', array('channel' => $this->channel)),'enableRegistration' => true)); ?>
            <?php else: ?>
                                
                <ul class="nav navbar-nav">
                    <li>
                        <a href="<?php echo $this->url('frontend/jeuxconcours', array('channel' => $this->channel)) ?>"
                            <?php if($this->pageGames != ''): echo ' class="'.$this->pageGames.'"'; endif; ?>><?php echo $this->translate('Contests'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('frontend/winner', array('channel' => $this->channel)) ?>"
                            <?php if($this->pageWinners != ''): echo ' class="'.$this->pageWinners.'"'; endif; ?>><?php echo $this->translate('Winners'); ?>
                        </a>
                    </li>
                </ul>
                
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel)) ?>">
                            <?php if($this->zfcUserIdentity()->getAvatar()):?>
                                <img src="<?php echo $this->basePath($this->zfcUserIdentity()->getAvatar()) ?>" width="28" height="28" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" />
                            <?php else:?>
                                    <?php if($this->zfcUserIdentity()->getTitle() && $this->zfcUserIdentity()->getTitle() == 'M'): ?>
                                        <span class="glyphicon glyphicon-user"></span>
                                    <?php else: ?>
                                        <span class="glyphicon glyphicon-user"></span>
                                    <?php endif; ?>
                            <?php endif;?>
                            <?php echo $this->zfcUserIdentity()->getUsername();?>
                       </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('My account'); ?>
                            <b class="caret"></b>
                        </a>
                         <ul class="dropdown-menu account">
                            <li>
                                <a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel));?>" class="badges-points">
                                    <span class="glyphicon glyphicon-tower"></span>
                                    <?php echo $this->translate('Badges and points'); ?>
                                </a>
                            </li>
                            
                            <li>
                                <a href="<?php echo $this->url('frontend/activity', array('channel' => $this->channel));?>" class="activity">
                                    <span class="glyphicon glyphicon-dashboard"></span>
                                    <?php echo $this->translate('My activity'); ?>
                                </a>
                            </li>
                            
                            <li>
                                <a href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel));?>" class="profile">
                                    <span class="glyphicon glyphicon-list"></span>
                                    <?php echo $this->translate('Change my informations'); ?>
                                </a>
                            </li>
                            
                            <li>
                                <a href="<?php echo $this->url('frontend/zfcuser/newsletter', array('channel' => $this->channel));?>" class="newsletter">
                                    <span class="glyphicon glyphicon-envelope"></span>
                                    <?php echo $this->translate('Manage my newletters'); ?>
                                </a>
                            </li>
                            
                            <li>
                                <a href="<?php echo $this->url('frontend/sponsorfriends', array('channel' => $this->channel)); ?>" class="sponsorfriends">
                                    <span class="glyphicon glyphicon-comment"></span>
                                    <?php echo $this->translate('Sponsor my friends'); ?>
                                </a>
                            </li>
                            
                            <li>
                                <a href="<?php echo $this->url('frontend/zfcuser/logout', array('channel' => $this->channel)) ?>" class="logout">
                                    <span class="glyphicon glyphicon-log-out"></span>
                                    <?php echo $this->translate('Logout'); ?>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('Badges'); ?><span class="badge"><?php echo count($badges);?></span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu all-badges">
                            <li>
                                <ul id="container-badge">
                                    <?php $i=0;foreach($badges as $badge): ?>
                                        <?php if($badge['reward']): ?>
                                            <?php if($badge['reward']->getHide() == false) : ?>
                                                <?php if($i<4): ?>                                        
                                                    <li <?php if ($i===0):?>id="first-item"<?php elseif($i===3):?>id="last-item"<?php endif;?>>
                                                        <?php if($badge['reward']->getImage()): ?>
                                                            <img src="/<?php echo $badge['reward']->getImage();?>" alt="/<?php echo $badge['reward']->getImage(); ?>" width="33" height="34" />
                                                        <?php else: ?>
                                                            <img  src="<?php echo $this->frontendAssetPath('images/badges/big-default.png')?>" alt="" width="33" height="34" />
                                                        <?php endif; ?>
                                                    </li>
                                                <?php endif; $i++; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endforeach;?>
                                </ul>
                                <a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel)) ?>">Tous les badges</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel)) ?>#title-point">
                            <span class="points"><?php echo number_format($this->userScore(), 0, ',', ' ');?></span> points
                        </a>
                    </li>
                </ul>
                <?php endif; ?>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- END HEADER -->

<!-- ADSERVING MEGA-BANNER -->
<div id="ad-mega-banner">
	<script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=18623;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script>
</div><!-- END ADSERVING MEGA-BANNER -->