<?php $badges =  $this->userBadges(0,false);?>
<?php $baseUrl = $this->url('frontend', array('channel' => $this->channel), array('force_canonical' => true)); ?>

<div id="fb-root">
</div>
<!-- ADSERVING LEFT -->
<div id="ad-left">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17603;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div><!-- ADSERVING LEFT -->

<!-- ADSERVING RIGHT -->
<div id="ad-right">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17603;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div><!-- END ADSERVING RIGHT -->

<!-- ADSERVING TOP -->
<div id="ad-top" class="row-fluid">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17604;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div>
<!-- END ADSERVING TOP -->

<!-- HEADER -->
<div id="header" class="row-fluid">
	<div class="logo"><a href="<?php echo $this->url('frontend', array('channel' => $this->channel)) ?>"><img src="<?php echo $this->frontendAssetPath('images/common/logo.png')?>" border="0" width="117" height="116" alt="logo" /></a></div>
	<div class="bartop row-fluid">
		 <?php if(($this->playgroundBlock('links')) != ''):?>
			<?php echo $this->playgroundBlock('links'); ?>
		<?php endif; ?>

		<?php if ($this->facebookUrl()):?>
            <!-- BLOCK FACEBOOK -->
            <div class="fb-jaime">
    			<span><a href="<?php echo $this->facebookUrl()?>" target="_blank">Playground</a></span>
    			<div class="fb-like" data-href="<?php echo $this->facebookUrl()?>" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false" data-font="arial"></div>
    		</div>
            <!-- END BLOCK FACEBOOK -->
        <?php endif;?>
		
	</div>
    <?php if(!$this->zfcUserIdentity()): ?>
        <?php echo $this->userLoginWidget(array('redirect' => $this->url('frontend', array('channel' => $this->channel)),'enableRegistration' => true)); ?>
    <?php else: ?>
	<div class="barnav row-fluid">
		<div id="menu"></div>
		<ul class="mainnav span7">
			<li class="nav-item games"><a href="<?php echo $this->url('frontend/jeuxconcours', array('channel' => $this->channel)) ?>"<?php if($this->pageGames != ''): echo ' class="'.$this->pageGames.'"'; endif; ?>>Jeux concours</a></li>
			<li class="nav-item winners"><a href="<?php echo $this->url('frontend/winner', array('channel' => $this->channel)) ?>"<?php if($this->pageWinners != ''): echo ' class="'.$this->pageWinners.'"'; endif; ?>>Les gagnants</a></li>
			<!-- <li class="nav-item shop"><a href="#">Boutique</a></li> -->
		</ul>
            <div id="logged">
    			<div class="connexion span5">
    				<ul id="user-info">
    					<li class="user-info" id="first-user-info">
	    					<a href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel)) ?>">
		    					<?php if($this->zfcUserIdentity()->getAvatar()):?>
		        			        <img src="<?php echo $this->basePath($this->zfcUserIdentity()->getAvatar()) ?>" width="28" height="28" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" />
		        			    <?php else:?>
		        			    		<?php if($this->zfcUserIdentity()->getTitle() && $this->zfcUserIdentity()->getTitle() == 'M'): ?>
		        			        		<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="no avatar" width="28" height="28" />
		        			    		<?php else: ?>
		        			    			<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="no avatar" width="28" height="28" />
		        			    		<?php endif; ?>
		        			    <?php endif;?>
	        			   </a>
    					    <span id="user-name">
    					    	<a href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel)) ?>"><?php echo $this->zfcUserIdentity()->getUsername();?></a>
    					    </span>
    					</li>
    					<li class="user-info">
    						<span id="user-account"><img src="<?php echo $this->frontendAssetPath('images/common/arrow-white-bottom.png') ?>" alt="arrow white bottom" /></span>
    					</li>
    					<li class="user-info badges">
    						<a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel)) ?>"><span id="user-badge">Vos badges <span id="count-badge"><?php echo $badges['userCountBadges'].'/'.count($badges);?></span></span></a>
    						<div id="slide-badge">
                                <div id="container-badge">
                                    <?php $i=0;foreach($badges as $badge): ?>
                                        <?php if($badge['reward']): ?>
                                            <?php if($badge['reward']->getHide() == false) : ?>
                                                <?php if($i<4): ?>                                        
                                                    <div class="slot-badge">
                                                        <?php if(!empty($badge['reward']->getImage())): ?>
                                                            <img src="/<?php echo $badge['reward']->getImage();?>" alt="/<?php echo $badge['reward']->getImage(); ?>" width="33" height="34"  />
                                                        <?php else: ?>
                                                            <img  src="<?php echo $this->frontendAssetPath('images/badges/big-default.png')?>" alt="" width="33" height="34" />
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; $i++; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endforeach;?>
                                </div>
                                <p><a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel)) ?>">Tous les badges</a></p>
                            </div>
    					</li>
    					<li class="user-info points">
    						<a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel)) ?>#title-point">
	    						<img src="<?php echo $this->frontendAssetPath('images/header/icon-cup.png') ?>" alt="icon cup" width="10" height="13" /><span id="user-point"><?php echo number_format($this->userScore(), 0, ',', ' ');?> points </span>
	    					</a>
	    				</li>

    				</ul>
    				<!-- menu slide connected -->
    				<div id="slide-connexion">
    					<div class="row-fluid">
    						<ul id="user-menu">
    							<li id="first-item">
    								<img src="<?php echo $this->frontendAssetPath('images/header/icon-money.png'); ?>" alt="icon money" /><a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel));?>">Mes badges et mes points</a>
    							</li>
    							<li>
    								<img src="<?php echo $this->frontendAssetPath('images/header/icon-calendar.png') ?>" alt="icon calendar" /><a href="<?php echo $this->url('frontend/activity', array('channel' => $this->channel));?>">Mon activité</a>
    							</li>
    							<li>
    								<img src="<?php echo $this->frontendAssetPath('images/header/icon-cog.png') ?>" alt="icon cog" /><a href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel));?>">Modifier mes informations</a>
    							</li>
    							<li>
    								<img class="icon-news" src="<?php echo $this->frontendAssetPath('images/header/icon-news.png') ?>" alt="icon news" /><a href="<?php echo $this->url('frontend/zfcuser/newsletter', array('channel' => $this->channel));?>">Gérer mes newletters</a>
    							</li>
    							<li>
    								<img src="<?php echo $this->frontendAssetPath('images/header/icon-users.png') ?>" alt="icon users" /><a href="<?php echo $this->url('frontend/sponsorfriends', array('channel' => $this->channel)); ?>">Parrainer mes amis</a>
    							</li>
    							<li id="last-item">
    								<img src="<?php echo $this->frontendAssetPath('images/header/icon-unlocked.png') ?>" alt="icon unlocked" /><a href="<?php echo $this->url('frontend/zfcuser/logout', array('channel' => $this->channel)) ?>">Déconnexion</a>
    							</li>
    						</ul>
    					</div>
    				</div>
    				<!-- // -->
    			</div>
    		</div>
    	</div>
    <?php endif; ?>
</div><!-- END HEADER -->

<!-- ADSERVING MEGA-BANNER -->
<div id="ad-mega-banner">
	<script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=18623;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script>
</div><!-- END ADSERVING MEGA-BANNER -->