<?php $badges =  $this->userBadges();?>

<?php $baseUrl = $this->url('frontend', array(), array('force_canonical' => true)); ?>

<div id="fb-root">
</div>
<!-- ADSERVING LEFT -->
<div id="ad-left">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17603;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div><!-- ADSERVING LEFT -->

<!-- ADSERVING RIGHT -->
<div id="ad-right">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17603;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div><!-- END ADSERVING RIGHT -->

<!-- ADSERVING TOP -->
<div id="ad-top" class="row-fluid">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17604;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div>
<!-- END ADSERVING TOP -->

<!-- HEADER -->
<div id="header" class="row-fluid">
	<div class="logo"><a href="<?php echo $this->url('frontend') ?>"><img src="<?php echo $this->frontendAssetPath('images/common/logo.png')?>" border="0" width="117" height="116" alt="logo" /></a></div>
	<div class="bartop row-fluid">
		 <?php if(($this->adfabBlock('links')) != ''):?>
			<?php echo $this->adfabBlock('links'); ?>
		<?php endif; ?>

		<div class="fb-jaime">
			<span><a href="http://www.facebook.com/adfabagency" target="_blank">Playground</a></span>
			<div class="fb-like" data-href="http://www.facebook.com/adfabagency" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false" data-font="arial"></div>
		</div>
	</div>
    <?php if(!$this->zfcUserIdentity()): ?>
        <?php echo $this->adfabUserLoginWidget(array('redirect' => $this->url('frontend'),'enableRegistration' => true)); ?>
    <?php else: ?>
	<div class="barnav row-fluid">
		<div id="menu"></div>
		<ul class="mainnav span7">
			<li class="nav-item games"><a href="<?php echo $this->url('frontend/jeuxconcours') ?>"<?php if($this->pageGames != ''): echo ' class="'.$this->pageGames.'"'; endif; ?>>Jeux concours</a></li>
			<li class="nav-item winners"><a href="<?php echo $this->url('frontend/winner') ?>"<?php if($this->pageWinners != ''): echo ' class="'.$this->pageWinners.'"'; endif; ?>>Les gagnants</a></li>
			<!-- <li class="nav-item shop"><a href="#">Boutique</a></li> -->
		</ul>
            <div id="logged">
    			<div class="connexion span5">
    				<ul id="user-info">
    					<li class="user-info" id="first-user-info">
	    					<a href="<?php echo $this->url('zfcuser/profile') ?>">
		    					<?php if($this->zfcUserIdentity()->getAvatar()):?>
		        			        <img src="<?php echo $this->basePath($this->zfcUserIdentity()->getAvatar()) ?>" width="28" height="28" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" />
		        			    <?php else:?>
		        			    		<?php if($this->zfcUserIdentity()->getTitle() && $this->zfcUserIdentity()->getTitle() == 'M'): ?>
		        			        		<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="no avatar" width="28" height="28" />
		        			    		<?php else: ?>
		        			    			<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="no avatar" width="28" height="28" />
		        			    		<?php endif; ?>
		        			    <?php endif;?>
	        			   </a>
    					    <span id="user-name">
    					    	<a href="<?php echo $this->url('zfcuser/profile') ?>"><?php echo $this->zfcUserIdentity()->getUsername();?></a>
    					    </span>
    					</li>
    					<li class="user-info">
    						<span id="user-account"><img src="<?php echo $this->frontendAssetPath('images/common/arrow-white-bottom.png') ?>" alt="arrow white bottom" /></span>
    					</li>
    					<li class="user-info badges">
    						<a href="<?php echo $this->url('frontend/badges') ?>"><span id="user-badge">Vos badges <span id="count-badge"><?php echo count($badges);?></span></span></a>
    						<!-- menu slide badge -->
    						<div id="slide-badge">
    							<div id="container-badge">
    							<?php $i=0;foreach($badges as $badge):?>
    							    <?php if($i>3) break;?>
    							    <?php
            					    $badgeColor = '';
            					    if($badge['level']>=3){
            					        $badgeColor = "gold-";
            					    }elseif($badge['level']==2){
            					        $badgeColor = "silver-";
            					    }elseif($badge['level']==1){
            					        $badgeColor = "bronze-";
            					    }
            					    ?>
    							    <div class="slot-badge">
    									<img src="<?php echo $this->frontendAssetPath('images/badges/'. strtolower($badgeColor) . $badge['category'] . '.png')?>" alt="badge <?php echo $badge['label'];?>" width="33" height="34" />
    								</div>
    							<?php $i++;endforeach;?>
    							<?php if($i==0): ?>
    								<div class="slot-badge">
    									<img src="<?php echo $this-> frontendAssetPath('images/badges/default.png')?>" alt="badge default" width="33" height="34" />
    								</div>
	    								<?php for($i;$i<=2;$i++):?>
	    									<div class="slot-badge"></div>
	    								<?php endfor;?>

    								<?php else: ?>
	    								<?php for($i;$i<=3;$i++):?>
	    									<div class="slot-badge"></div>
	    								<?php endfor;?>
    								<?php endif; ?>
    							</div>
    							<p><a href="<?php echo $this->url('frontend/badges') ?>">Tous les badges</a></p>
    						</div>
    						<!-- // -->
    					</li>
    					<li class="user-info points">
    						<a href="<?php echo $this->url('frontend/badges') ?>#title-point">
	    						<img src="<?php echo $this->frontendAssetPath('images/header/icon-cup.png') ?>" alt="icon cup" width="10" height="13" /><span id="user-point"><?php echo number_format($this->userScore(), 0, ',', ' ');?> points </span>
	    					</a>
	    				</li>

    				</ul>
    				<!-- menu slide connected -->
    				<div id="slide-connexion">
    					<div class="row-fluid">
    						<ul id="user-menu">
    							<li id="first-item">
    								<img src="<?php echo $this->frontendAssetPath('images/header/icon-money.png'); ?>" alt="icon money" /><a href="<?php echo $this->url('frontend/badges');?>">Mes badges et mes points</a>
    							</li>
    							<li>
    								<img src="<?php echo $this->frontendAssetPath('images/header/icon-calendar.png') ?>" alt="icon calendar" /><a href="<?php echo $this->url('frontend/activity');?>">Mon activité</a>
    							</li>
    							<li>
    								<img src="<?php echo $this->frontendAssetPath('images/header/icon-cog.png') ?>" alt="icon cog" /><a href="<?php echo $this->url('zfcuser/profile');?>">Modifier mes informations</a>
    							</li>
    							<li>
    								<img class="icon-news" src="<?php echo $this->frontendAssetPath('images/header/icon-news.png') ?>" alt="icon news" /><a href="<?php echo $this->url('zfcuser/newsletter');?>">Gérer mes newletters</a>
    							</li>
    							<li>
    								<img src="<?php echo $this->frontendAssetPath('images/header/icon-users.png') ?>" alt="icon users" /><a href="<?php echo $this->url('frontend/sponsorfriends'); ?>">Parrainer mes amis</a>
    							</li>
    							<li id="last-item">
    								<img src="<?php echo $this->frontendAssetPath('images/header/icon-unlocked.png') ?>" alt="icon unlocked" /><a href="<?php echo $this->url('zfcuser/logout') ?>">Déconnexion</a>
    							</li>
    						</ul>
    					</div>
    				</div>
    				<!-- // -->
    			</div>
    		</div>
    	</div>
    <?php endif; ?>
</div><!-- END HEADER -->

<!-- ADSERVING MEGA-BANNER -->
<div id="ad-mega-banner">
	<script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=18623;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script>
</div><!-- END ADSERVING MEGA-BANNER -->