<?php echo $this->doctype(); ?>
<?php $this->plugin('translate')->setTranslatorTextDomain('default');// Pour le texte ?>
<?php 
$children = $this->viewModel()
    ->getCurrent()
    ->getChildren();

$ourView  = $children[0];
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
    <head>
        <?php echo $this->head();?>
    </head>
    <body>
    	<div id="container">
        	<div id="fb-root"></div>
			<div id="content">	
	            <?php echo $this->header(array('adserving' => $this->adserving, 'currentPage' => $this->currentPage, 'channel' => $this->channel));?>     
	            <div id="containerpage" class="row">
	                
                    <?php echo $this->slider; ?>
                    <!-- Main content left-->
                    <div class="main-content col-md-8">
    	            	<?php if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : ?>
    	                    <ul class="flashMessages">
    	                        <?php foreach ($ourView->flashMessages as $fMessage) : ?>
    	                        <li><?php echo $this->translate($fMessage); ?></li>
    	                        <?php endforeach; ?>
    	                    </ul>
    	                <?php endif; ?>
    
                        <?php echo $this->content; ?>
                    </div>
                    	
                    	
                    <!-- Sidebar -->
                	<?php echo $this->column_right(array(
                	        'template' => $this->col_right,
                	        'adserving' => $this->adserving,
                			'channel' => $this->channel
                	)); ?>
	            </div>
                <?php echo $this->footer(array('channel' => $this->channel));?>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>

