<?php echo $this->doctype(); ?>
<?php $this->plugin('translate')->setTranslatorTextDomain('default');// Pour le texte ?>
<?php 
$children = $this->viewModel()
    ->getCurrent()
    ->getChildren();

$ourView  = $children[0];
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
    <head>
        <?php echo $this->head();?>
    </head>
    <body>
    	<div id="container">
        	<div id="fb-root"></div>
			<div id="content" class="row-fluid">	
	            <?php echo $this->header(array('adserving' => $this->adserving, 'currentPage' => $this->currentPage));?>     
	            <div id="containerpage">
	            	<?php if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : ?>
	                    <ul class="flashMessages">
	                        <?php foreach ($ourView->flashMessages as $fMessage) : ?>
	                        <li><?php echo $this->translate($fMessage); ?></li>
	                        <?php endforeach; ?>
	                    </ul>
	                <?php endif; ?>

                    <?php echo $this->slider; ?>
	                <div class="row-fluid">
	                	<div class="content-inner span8"><?php echo $this->content; ?></div>
	                	<?php echo $this->column_right(array(
	                	        'template' => $this->col_right,
	                	        'adserving' => $this->adserving
	                	)); ?>
	                </div>	
	            </div>
                <?php echo $this->footer();?>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
