<?php $badges =  $this->userBadges();?>

<?php $baseUrl = $this->url('frontend', array('channel' => $this->channel), array('force_canonical' => true)); ?>

<div id="fb-root">
</div>
<!-- ADSERVING LEFT -->
<div id="ad-left">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17603;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div><!-- ADSERVING LEFT -->

<!-- ADSERVING RIGHT -->
<div id="ad-right">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17603;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div><!-- END ADSERVING RIGHT -->

<!-- ADSERVING TOP -->
<div id="ad-top">
	<!-- script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=17604;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script-->
</div>
<!-- END ADSERVING TOP -->

<!-- HEADER -->
<div class="wrap-header">
    <div id="header">
        <div class="row" >
            <div class="col-md-2 logo">
                <a href="<?php echo $this->url('frontend', array('channel' => $this->channel)) ?>">
                    <img src="<?php echo $this->frontendAssetPath('images/common/logo-black.png')?>" alt="logo" />
                </a>
            </div>
            <div class="col-md-5 hook-title" >La première plateforme de jeux open source !</div>
        </div>
    </div>
        <?php if(!$this->zfcUserIdentity()): ?>
            <?php echo $this->userLoginWidget(array('redirect' => $this->url('frontend', array('channel' => $this->channel)),'enableRegistration' => true)); ?>
        <?php else: ?>
	<div class="barnav row">
        <nav class="navbar navbar-default" role="navigation">
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li class="active up">
                        <a href="<?php echo $this->url('frontend/jeuxconcours', array('channel' => $this->channel)) ?>"
                            <?php if($this->pageGames != ''): echo ' class="'.$this->pageGames.'"'; endif; ?>>Jeux concours</a>
                    </li>
                    <li class="up">
                        <a href="<?php echo $this->url('frontend/winner', array('channel' => $this->channel)) ?>"
                            <?php if($this->pageWinners != ''): echo ' class="'.$this->pageWinners.'"'; endif; ?>>Les gagnants</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav right">
                    <li>
                        <a href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel)) ?>">
                            <?php if($this->zfcUserIdentity()->getAvatar()):?>
                                <img src="<?php echo $this->basePath($this->zfcUserIdentity()->getAvatar()) ?>" width="28" height="28" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" />
                            <?php else:?>
                                    <?php if($this->zfcUserIdentity()->getTitle() && $this->zfcUserIdentity()->getTitle() == 'M'): ?>
                                        <img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="no avatar" />
                                    <?php else: ?>
                                        <img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="no avatar" />
                                    <?php endif; ?>
                            <?php endif;?>
                            <?php echo $this->zfcUserIdentity()->getUsername();?>
                       </a>
                    </li>
                    <li class="dropdown account-options">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li id="first-item">
                                <a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel));?>" class="badges-points">
                                    <span class="sprite-icon"></span>
                                    Mes badges et mes points
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('frontend/activity', array('channel' => $this->channel));?>" class="activity">
                                    <span class="sprite-icon"></span>
                                    Mon activité
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('frontend/zfcuser/profile', array('channel' => $this->channel));?>" class="profile">
                                    <span class="sprite-icon"></span>
                                    Modifier mes informations
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('frontend/zfcuser/newsletter', array('channel' => $this->channel));?>" class="newsletter">
                                    <span class="sprite-icon"></span>
                                    Gérer mes newletters
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('frontend/sponsorfriends', array('channel' => $this->channel)); ?>" class="sponsorfriends">
                                    <span class="sprite-icon"></span>
                                    Parrainer mes amis
                                </a>
                            </li>
                            <li id="last-item">
                                <a href="<?php echo $this->url('frontend/zfcuser/logout', array('channel' => $this->channel)) ?>" class="logout">
                                    <span class="sprite-icon"></span>
                                    Déconnexion
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- <a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel)) ?>" class="dropdown-toggle" data-toggle="dropdown"> -->
                            Vos badges <span class="badge"><?php echo count($badges);?></span>
                            <b class="caret"></b>
                        </a>
                        <!-- menu slide badge -->
                        <ul class="dropdown-menu">
                            <?php $i=0;foreach($badges as $badge):?>
                                <?php if($i>3) break;?>
                                <?php
                                $badgeColor = '';
                                if($badge['level']>=3){
                                    $badgeColor = "gold-";
                                }elseif($badge['level']==2){
                                    $badgeColor = "silver-";
                                }elseif($badge['level']==1){
                                    $badgeColor = "bronze-";
                                }
                                ?>
                                <li class="slot-badge">
                                    <img src="<?php echo $this->frontendAssetPath('images/badges/'. strtolower($badgeColor) . $badge['category'] . '.png')?>" alt="badge <?php echo $badge['label'];?>" width="33" height="34" />
                                </li>
                            <?php $i++;endforeach;?>
                            <?php if($i==0): ?>
                            <li class="slot-badge">
                                <img src="<?php echo $this-> frontendAssetPath('images/badges/default.png')?>" alt="badge default" width="33" height="34" />
                            </li>
                            <?php for($i;$i<=2;$i++):?>
                                <li class="slot-badge"></li>
                            <?php endfor;?>
                            <?php else: ?>
                                <?php for($i;$i<=3;$i++):?>
                                    <li class="slot-badge"></li>
                                <?php endfor;?>
                            <?php endif; ?>
                            <li>
                                <a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel)) ?>">Tous les badges</a>
                            </li>
                        </ul>
                    </li>
                    <li class="user-info points">
                        <a href="<?php echo $this->url('frontend/badges', array('channel' => $this->channel)) ?>#title-point">
                            points <span class="badge"><?php echo number_format($this->userScore(), 0, ',', ' ');?></span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
	</div>
    <?php endif; ?>
</div>
<!-- END HEADER -->

<!-- ADSERVING MEGA-BANNER -->
<div id="ad-mega-banner">
	<script type="text/javascript" language="JavaScript" src="http://eas4.emediate.eu/eas?cu=18623;cre=mu;js=y;target=_blank;cat1=<?php echo $this->cat1 ?>;cat2=<?php echo $this->cat2 ?>;cat3=<?php echo $this->cat3 ?>"></script>
</div><!-- END ADSERVING MEGA-BANNER -->