<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundreward'); ?>

<?php
	$currentPageItems = $this->leaderboard->getCurrentPageNumber() * 100;
	$result = $currentPageItems - $this->leaderboard->getTotalItemCount();
	$lastPageItems = 100 - $result;
?>

<div id="leaderboard" class="row-fluid">

	<div class="row-fluid">
		<h1 class="span8"><?php echo $this->translate('The ranking');?></h1>

		<?php if($this->zfcUserIdentity()): ?>
		    <?php $rank =  $this->rankWidget($this->zfcUserIdentity()->getId());?>
			<div class="current-position span4">
				<div class="row-fluid">
					<div class="ribbon span3"></div>
					<div class="avatar span3">
						<?php if($this->zfcUserIdentity()->getAvatar()):?>
							<img src="<?php echo $this->basePath($this->zfcUserIdentity()->getAvatar()) ?>" width="32" height="32" border="0" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" />
						<?php else:?>
							<?php if($this->zfcUserIdentity()->getTitle() && $this->zfcUserIdentity()->getTitle() == 'M'): ?>
					        	<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" width="32" height="32" border="0" />
					   		<?php else: ?>
					        	<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="<?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>" width="32" height="32" border="0" />
					   		<?php endif; ?>
					    <?php endif;?>
					</div>
					<div class="span6">
						<div class="rank"><?php echo $rank['rank'];?><sup><?php echo ($rank['rank'] == 1)? 'er':'ème'; ?></sup></div>
						<div class="name">
							<?php if($this->zfcUserIdentity()->getUsername()) :
								echo $this->zfcUserIdentity()->getUsername();
							else :
								echo $this->zfcUserIdentity()->getFirstname().' '.substr($this->zfcUserIdentity()->getLastname(), 0, 1).'.';
							endif;
							?>
						</div>
						<div class="points"><?php echo number_format($rank['points'], 0, ',', ' ' ); ?> points</div>
					</div>
				</div>
			</div>
		<?php endif; ?>
	</div>

	<!-- sort leader board -->
	<div id="sort-leaderboard" class="row-fluid orange-dot-double">
		<div class="span2">
			<div class="btn btn-inverse active">
				<a href="<?php echo $this->url('frontend/reward/leaderboard', array('channel' => $this->channel)); ?>"><?php echo $this->translate('General');?></a>
			</div>
		</div>
		<div class="span3">
			<select name="filter-leaderboard" id="filter-leaderboard">
				<option value="">Sélectionner</option>
				<?php foreach ($filters as $leaderboardType) : ?>
					<option value="<?php echo $this->url('frontend/reward/leaderboard',array('channel' => $this->channel, 'filter' => $leaderboardType->getName())) ?>" <?php echo ($this->filter == $leaderboardType->getName())? 'selected' : '';?>><?php echo $this->translate($leaderboardType->getName());?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div class="span4 search-leaderboard">
			<form action="<?php echo $this->url('frontend/reward/leaderboard', array('channel' => $this->channel, 'filter' => $this->filter)); ?>" method="GET" class="row-fluid">
			<div class="span10">
				<input type="text" name="name" id="" placeholder="<?php echo $this->translate('Search');?>" value="<?php echo $this->search?>"/>
			</div>
			<div class="span2">
				<input type="submit" class="btn btn-success" value="<?php echo $this->translate('Search');?>" />
				<img class="btn-glass" src="<?php echo $this->frontendAssetPath('images/common/btn-glass.png')?>" alt="" width="16" height="17"/>
			</div>
			</form>
		</div>
	</div>
	<!--// sort leader board -->

	<!-- list leaderboard -->
	<div id="list-leaderboard" class="row-fluid">

		<!-- first -->
		<?php $i=1;foreach($this->leaderboard as $entry):?>
			
			<?php $achievements =  $this->userBadges($entry['id'], true);?>
			<?php if($i<=25 && $this->leaderboard->getCurrentPageNumber() <= 1):?>
				
				<div id="lead<?php echo $i;?>" class="list-lead rounded row-fluid">
					<div class="wrap-lead">
						<div class="span2 ribon">
							<p class="podium"><?php echo $i + $this->leaderboard->getItemCountPerPage() * ( $this->leaderboard->getCurrentPageNumber() - 1 ) ?></p>
						</div>
						<div class="lead-user span4">
							<?php if($entry['avatar']): ?>
								<img src="<?php echo $this->basePath($entry['avatar'])?>" width="35" height="35" border="0" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" />
							<?php elseif($entry['title'] && $entry['title'] == 'M') : ?>
								<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" width="35" height="35" border="0" />
							<?php else : ?>
								<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" width="35" height="35" border="0" />
							<?php endif; ?>
							<p><?php if($entry['username']) : echo substr($entry['username'], 0, 15); else : echo substr($entry['firstname'].' '.substr($entry['lastname'], 0, 1), 0, 15).'.'; endif; ?></p>
						</div>
						<div class="lead-badge span3">
							<ul>
							<?php foreach($achievements as $key => $achievement):?>
								<?php if(!empty($achievement['reward'])): ?>
							   		<?php $badge = $achievement['reward'];?>
									<li>
									    <?php if($badge && $badge->getImage()): ?>
										     <img src="/<?php echo $badge->getImage();?>" alt="/<?php echo $badge->getImage(); ?>" width="33" height="34"  />
										<?php endif; ?>
										<p></p>
									</li>
								<?php endif;?>
						    <?php endforeach; ?> 
							</ul>
						</div>

						<?php if($this->filter != 'social') : ?>
						<div class="lead-points span3">
							<p><?php echo number_format($entry['points'], 0, ',', ' ' ); ?> points</p>
						</div>
						<?php endif; ?>
					</div>
				</div>
				
			<?php else:?>
				
				<!-- small -->
				<?php if(($i == 26 && $this->leaderboard->getCurrentPageNumber() <= 1) || ($i == 1 && $this->leaderboard->getCurrentPageNumber() > 1)):?>
				<div class="col-lead">
				<?php endif ?>
					<div class="small-lead wrap-lead rounded">
						<div class="ribon span3">
							<p><span><?php echo $i + $this->leaderboard->getItemCountPerPage() * ( $this->leaderboard->getCurrentPageNumber() - 1 )?></span></p>
						</div>
						<div class="span3">
							<?php if($entry['avatar']): ?>
								<img src="<?php echo $this->basePath($entry['avatar'])?>" width="35" height="35" border="0" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" />
							<?php elseif($entry['title'] && $entry['title'] == 'M') : ?>
								<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" width="35" height="35" border="0" />
							<?php else : ?>
								<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="<?php echo $entry['firstname']; ?> <?php echo $entry['lastname']; ?>" width="35" height="35" border="0" />
							<?php endif; ?>
						</div>
						<p class="span6">
							<?php
								if($entry['username']):
			    					echo substr($entry['username'], 0, 15);
								else :
									echo substr($entry['firstname'].' '.substr($entry['lastname'], 0, 1), 0, 15).'.';
								endif;
							?><br/>
							<span class="green"><?php echo number_format($entry['points'], 0, ',', ' ' );?> points</span>
						</p>
					</div>
				<?php if($i == $this->leaderboard->getItemCountPerPage() || ($i == $lastPageItems)) : ?>
				</div>
				<?php endif ?>
				
			<?php endif;?>
		
		<?php $i++;endforeach;?>
	</div>
	<!-- //list leaderboard -->

</div>

<?php echo $this->paginationControl($this->leaderboard, 'Sliding', 'playground-reward/index/pagination.phtml', array('url' => 'frontend/reward/leaderboard','filter' => $this->filter)); ?>