<style>
  .column { width: 250px; float: left; border-style: solid; border-width:1px; margin:15px; padding: 5px; min-height:140px}
  .portlet { margin: 0 0 1em 0; }
  .portlet-header { margin: 0.3em; padding-bottom: 4px; padding-left: 0.2em; }
  .portlet-header .ui-icon { float: right; }
  .portlet-content { padding: 0.4em; }
  .ui-sortable-placeholder { border: 1px dotted black; visibility: visible !important; height: 50px !important; }
  .ui-sortable-placeholder * { visibility: hidden; }
</style>

<h1>Dynablock</h1>


<div class="column">
Les dynablocks à ma dispo
<?php foreach($this->blocks as $block):?>
    <div class="portlet" id="<?php echo 'block';?>_<?php echo $block->getId()?>">
		<div class="portlet-header"><?php echo $block->getTitle()?></div>
		<div class="portlet-content">Lorem ipsum dolor sit amet, consectetuer adipiscing elit</div>
	</div>
<?php endforeach;?>
</div>

<div class="column" id="dynablock_<?php echo $this->dynarea; ?>">
La dynarea <?php echo $this->dynarea;?>
<?php foreach ($this->dynablocks as $dynablock): ?>
    <div class="portlet" id="<?php echo 'block';?>_<?php echo $dynablock->getId()?>">
		<div class="portlet-header"><?php echo $dynablock->getIdentifier()?></div>
		<div class="portlet-content">Lorem ipsum dolor sit amet, consectetuer adipiscing elit</div>
	</div>
<?php endforeach; ?>
</div>
<script>

  $(function() {

	  $( ".column" ).sortable({
	      connectWith: ".column",
	      update: function(event, ui) {
	    	  if (this.id == 'dynablock_<?php echo $this->dynarea; ?>') {
    	    	  var blockList = $(this).sortable('toArray');//$('#dynablock_<?php //echo $this->dynarea; ?>').sortable('serialize');//
  	    	      var dynarea = '<?php echo $this->dynarea; ?>';

    	    	  $.post(
    			    '<?php echo $this->url('admin/playgroundcmsadmin/dynablocks/create', array('dynareaId' => $this->dynarea))?>',
	    	    	{blockList: blockList, dynarea: dynarea},
	    	    	function(returnVal) {
	    	    	    // TODO
	    	    	}
    	    	 );
	    	  }
	      }
	    });

    $( ".portlet" ).addClass( "ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" )
      .find( ".portlet-header" )
        .addClass( "ui-widget-header ui-corner-all" )
        .prepend( "<span class='ui-icon ui-icon-plusthick'></span>")
        .end()
      .find( ".portlet-content" ).toggle();

    $( ".portlet-header .ui-icon" ).click(function() {
      $( this ).toggleClass( "ui-icon-minusthick" ).toggleClass( "ui-icon-plusthick" );
      $( this ).parents( ".portlet:first" ).find( ".portlet-content" ).toggle();
    });

    $( ".column" ).disableSelection();
  });

  </script>