<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<a class="btn btn-default right" href="<?php echo $this->url('admin/playgroundflow/story');?>"><?php echo $this->translate('Retour'); ?></a>

<h1><?php echo $this->translate('Création'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?><?php echo $this->formButton($form->get('submit')) ?>

<div id="content">
    <div>
		<div class="label-input">
            <?php echo $this->formLabel($form->get('code')); ?>
            <?php echo $this->formInput($form->get('code')); ?>
            <?php echo $this->formElementErrors($form->get('code')) ?>
		</div>
		<div class="label-input">
            <?php echo $this->formLabel($form->get('label')); ?>
            <?php echo $this->formInput($form->get('label')); ?>
            <?php echo $this->formElementErrors($form->get('label')) ?>
		</div>
		<div class="label-input">
            <?php echo $this->formLabel($form->get('definition')); ?>
            <?php echo $this->formTextarea($form->get('definition')); ?>
            <?php echo $this->formElementErrors($form->get('definition')) ?>
		</div>
		<div class="label-input">
            <?php echo $this->formLabel($form->get('action')); ?>
            <?php echo $this->formSelect($form->get('action')); ?>
            <?php echo $this->formElementErrors($form->get('action')) ?>
		</div>
		<div class="label-input">
            <?php echo $this->formLabel($form->get('object')); ?>
            <?php echo $this->formSelect($form->get('object')); ?>
            <?php echo $this->formElementErrors($form->get('object')) ?>
		</div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>