<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>


<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-default right')) ?>
<h1><?php echo $this->translate('Création'); ?></h1>
<div id="content">
    <div>
		<div class="form-group">
            <?php echo $this->formLabel($form->get('code')); ?>
            <?php echo $this->formInput($form->get(('code'))->setAttribute('class', 'form-control')); ?>
            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('code'))) ?>
		</div>
		<div class="form-group">
            <?php echo $this->formLabel($form->get('label')); ?>
            <?php echo $this->formInput($form->get(('label'))->setAttribute('class', 'form-control')); ?>
            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('label'))) ?>
		</div>
		<div class="form-group">
            <?php echo $this->formLabel($form->get('definition')); ?>
            <?php echo $this->formTextarea($form->get(('definition'))->setAttribute('class', 'form-control')->setAttribute('row', '4')); ?>
            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('definition'))) ?>
		</div>
		<div class="form-group">
            <?php echo $this->formLabel($form->get('action')); ?>
            <?php echo $this->formSelect($form->get(('action'))->setAttribute('class', 'form-control')); ?>
            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('action'))) ?>
		</div>
		<div class="form-group">
            <?php echo $this->formLabel($form->get('objects')); ?>
            <?php echo $this->formMultiCheckbox($form->get(('objects'))->setAttribute('class', 'form-control')); ?>
            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('objects'))) ?>
		</div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
<script>
	
    var template = $('#condition_entry > span');
    var datatemplate = $('#condition_entry > span').data('template');
    template.data('template', '<fieldset id="conditions__index__">'+datatemplate+'</fieldset>');
    
    function add_condition() {
        var currentCount = $('#condition_entry fieldset').length;
        var template = $('#condition_entry > span').data('template');
        template = template.replace(/__index__/g, currentCount);
        $('#condition_entry').append('<fieldest>');
        $('#condition_entry').append(template);
        $('#condition_entry').append('<hr/>');
        $('#condition_entry').append('</fieldset>');

        return false;
    }
	

    $( document ).on( "click", "#condition_entry button", function(){
    	$(this).parent().empty();
    	return false;
    });
    
</script>
