<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<div class="return"><a href="<?php echo $this->url('admin/playgroundflow/story');?>"><?php echo $this->translate('Retour'); ?></a></div>

<h1><?php echo $this->translate('Création'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div id="content">
        <div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('code')); ?>
	            <?php echo $this->formInput($form->get('code')); ?>
	            <?php echo $this->formElementErrors($form->get('code')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('label')); ?>
	            <?php echo $this->formInput($form->get('label')); ?>
	            <?php echo $this->formElementErrors($form->get('label')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('definition')); ?>
	            <?php echo $this->formTextarea($form->get('definition')); ?>
	            <?php echo $this->formElementErrors($form->get('definition')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('action')); ?>
	            <?php echo $this->formSelect($form->get('action')); ?>
	            <?php echo $this->formElementErrors($form->get('action')) ?>
			</div>
			<div id="condition_entry" class="control-group">
            <?php foreach($form->get('objects') as $fieldset):?>
                <fieldset>
                <?php foreach($fieldset as $element):?>
                    <?php echo $this->formRow($element); ?>
                <?php endforeach;?>
                </fieldset>
            <?php endforeach;?>
            <?php echo $this->formCollection()->renderTemplate($form->get('objects'));?>
            </div>
            
            <ul class="liste-buttons">
				<li class="btn-admin"><a href="#" onclick="add_condition()"><?php echo $this->translate('Add a condition'); ?></a></li>
			</ul>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
<script>
	
    var template = $('#condition_entry > span');
    var datatemplate = $('#condition_entry > span').data('template');
    template.data('template', '<fieldset id="conditions__index__">'+datatemplate+'</fieldset>');
    
    function add_condition() {
        var currentCount = $('#condition_entry fieldset').length;
        var template = $('#condition_entry > span').data('template');
        template = template.replace(/__index__/g, currentCount);
        $('#condition_entry').append('<fieldest>');
        $('#condition_entry').append(template);
        $('#condition_entry').append('<hr/>');
        $('#condition_entry').append('</fieldset>');

        return false;
    }
	

    $( document ).on( "click", "#condition_entry button", function(){
    	$(this).parent().empty();
    	return false;
    });
    
</script>