<?php $this->plugin('translate')->setTranslatorTextDomain('application');// Pour le texte ?>

<?php //echo $this->partialLoop('application/index/partial/item.phtml', $this->games) ?>
<?php foreach ($this->missions as $mission) : ?>
    <?php echo $this->partial('playground-game/partial/mission.phtml', array('mission' => $mission, 'channel' => $this->channel)) ?>
<?php endforeach; ?>

<?php foreach($this->items as $item):?>
    <?php if(! $item instanceof PlaygroundCms\Entity\Page):?>
        <?php $this->partial()->setObjectKey('game')?>
        <?php echo $this->partial('playground-game/partial/game.phtml', array('game' => $item, 'channel' => $this->channel)) ?>
    <?php else:?>
        <?php $this->partial()->setObjectKey('page')?>
        <?php echo $this->partial('playground-cms/page/partial/page.phtml', array('page' => $item, 'channel' => $this->channel)) ?>
    <?php endif;?>
<?php endforeach;?>
<?php echo $this->paginationControl($this->items, 'Sliding', 'application/index/partial/pagination.phtml', array('url' => 'frontend/pagination')); ?>