<?php $this->plugin('translate')->setTranslatorTextDomain('application');// Pour le texte ?>

<?php //echo $this->partialLoop('application/index/partial/item.phtml', $this->games) ?>

<?php foreach($this->items as $item):?>
    <?php if(! $item instanceof AdfabCms\Entity\Page):?>
        <?php $this->partial()->setObjectKey('game')?>
        <?php echo $this->partial('adfab-game/partial/game.phtml', array('game' => $item, 'channel' => $this->channel)) ?>
    <?php else:?>
        <?php $this->partial()->setObjectKey('page')?>
        <?php echo $this->partial('adfab-cms/page/partial/page.phtml', array('game' => $item, 'channel' => $this->channel)) ?>
    <?php endif;?>
<?php endforeach;?>
<?php echo $this->paginationControl($this->items, 'Sliding', 'application/index/partial/pagination.phtml', array('url' => 'frontend/pagination')); ?>