<?php
$this->plugin('translate')->setTranslatorTextDomain('playgroundgame');
$fbShareMsg = $this->translate('Come play games Playground');
$twShareMsg = $this->translate('Come play games Playground');
$fbRequestMsg = $this->translate('Come play games Playground');
?>
<!-- SPONSOR (parrainer amis) (user page) -->
<div id="sponsor-friends" class="row">
	<div
	   id="datas-result"
	   data-url="<?php echo $this->url('frontend', array('channel' => $this->channel), array('force_canonical' => true)); ?>" data-secretkey="<?php echo $this->secretKey; ?>"
	   data-fbmsg="<?php echo $fbShareMsg; ?>" data-twmsg="<?php echo $twShareMsg; ?>"
	   data-fbrequest="<?php echo $fbRequestMsg; ?>"
	   data-sociallink="<?php echo $this->socialLinkUrl; ?>"
	   data-route="<?php echo $this->url('frontend/sponsorfriends', array('channel' => $this->channel)); ?>">
    </div>
	<!-- content -->
	<div id="badges-resume">
		<h1>
		    <?php echo $this->translate('Sponsor my friends'); ?>
		</h1>
		<h2>
			<?php echo $this->translate('Invite your friends and earn 250 points for each friend who registers on Playground'); ?>
		</h2>
		<!-- SPONSOR (parrainer) -->
        <?php echo $this->partial('playground-game/partial/result-share'); ?>
		<!-- //END SPONSOR (parrainer) -->
		<?php if(count($this->events)>0):?>
		<div class="row">
			<h1>
			    <?php echo $this->translate('Friends sponsored'); ?>
			</h1>
			<?php
			foreach($this->events as $event):
                if(in_array($event->getActionId(), array(20))):
                $now = new \DateTime('now');
                $interval = $now->diff($event->getCreatedAt());
    		    $duration = 0;
    	        if($interval->days < 1) $duration = $this->translate('less than 1 day');
    	        elseif($interval->days < 2) $duration = $this->translate('1 day');
    	        elseif($interval->days < 31) $duration = $interval->days . ' '.$this->translate('days');
    	        elseif($interval->days < 365) $duration = $interval->m . ' '.$this->translate('month');
    	        elseif($interval->days < 730) $duration = $interval->y . ' '.$this->translate('year');
    	        else $duration = $interval->y . ' '.$this->translate('years');
    	        ?>
    			<div class="row orange-dot-top">
    				<div class="col-md-8">
    					<p>
    						<?php echo $this->translate('You sponsored'); ?>
    						<a class="green-underline" href="">
    						    <?php echo $this->translate($event->getLabel()); ?>
    						</a>
    						<br/>
    						<span class="small">
    						    <?php echo $this->translate('Since'); ?> <?php echo $duration;?>
    						</span>
    					</p>
    				</div>
    				<div class="col-md-4">
    					<p>
    					    + <?php echo $event->getPoints()?> points
    					</p>
    				</div>
    			</div>
    			<?php endif;?>
			<?php endforeach;?>
		</div>
		<?php endif;?>
	</div>
</div>
<!-- END SPONSOR (parrainer amis) (user page) -->
