<?php
$children = $this->viewModel()
->getCurrent()
->getChildren();
if(isset($children[0])){
    $ourView  = $children[0];
}

?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle('Playground')->setSeparator(' - ')->setAutoEscape(false) ?>

<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

<!-- Le styles -->
<?php /*echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))*/
?>

<!-- Scripts -->
<?php /*echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))*/

?>
<?php
	echo $this->plugin('HeadLink');
    echo $this->plugin('HeadStyle');
    echo $this->plugin('HeadScript');
?>
</head>
<body>
    <header class="navbar">
        
        <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <a class="nav navbar-nav navbar-left" href="<?php echo $this->url('admin') ?>">
                    <img src="<?php echo $this->adminAssetPath('images/common/logo.png'); ?>" alt="<?php echo $this->translate('Admin'); ?>" border="0" width="80" />
                </a>
                
                <ul class="nav navbar-nav navbar-right">
                    <li class="margin-left10"><a href="#"><?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?></a></li>
                    <li class="margin-left10"><a href="<?php echo $this->url('frontend/zfcuser/logout', array('channel' => $this->channel)) ?>?redirect=<?php echo $this->url('admin', array('channel' => $this->channel)) ?>"
                            class="logout">Se déconnecter <span class="glyphicon glyphicon-log-out"></span></a></li>
                    <li class="margin-left10"><a href="<?php echo $this->url('frontend', array('channel' => $this->channel)) ?>" target="_blank">Accéder au site<span class="glyphicon glyphicon-chevron-right"></span></a></li>
                </ul>
    		</nav>
    	</div>

        <div class="container">
        	<nav class="navbar navbar-default" role="navigation">
        	    <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                
                <div class="collapse navbar-collapse navbar-ex1-collapse">
            		<ul class="nav navbar-nav">
            			<?php echo $this->adminMenu()->setPartial(array('playground-core/menu.phtml', 'default')); ?>
            		</ul>
                </div>
            </nav>
        </div>
    </header>

	<div class="container">
		<?php if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : ?>
		<ul class="flashMessages">
			<?php foreach ($ourView->flashMessages as $fMessage) : ?>
			<li><?php echo $fMessage; ?></li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
		<?php echo $this->navigation()
		->breadcrumbs('admin_navigation')
		->setMaxDepth(3)
		->setPartial(array('playground-core/breadcrumbs.phtml', 'default'));
		?>
		<?php echo $this->content; ?>

		<footer>
			<p>&copy; 2013 by playground. All rights reserved.</p>
		</footer>
	</div>
	<!-- /container -->
	<?php echo $this->inlineScript() ?>
</body>
</html>
