<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('frontend/zfcuser/ajaxlogin',array('channel' => $this->channel)));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'header-login');
?>
<ul class="nav navbar-nav">
    
    <li>
        <a href="<?php echo $this->url('frontend', array('channel' => $this->channel)) ?>"<?php if($this->pageGames != ''): echo ' class="'.$this->pageGames.'"'; endif; ?>>
            <?php echo $this->translate('Home');?>
        </a>
    </li>
</ul>

<ul class="nav navbar-nav navbar-right">
    <li><a href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Create an account'); ?></a></li>
    <li class="separator">/</li>
    <li class="dropdown">
        <a href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>" class="dropdown-toggle" data-toggle="dropdown">
            <?php echo $this->translate('Log in'); ?>
            <b class="caret"></b>
        </a>
         <ul class="dropdown-menu login">
            <li>
               <div class="row">
                  <div class="col-md-12">
                    <?php echo $this->form()->openTag($form) ?>
                        <span id="input-login-error"></span>
                        <div class="form-group">
                            <label class="sr-only" for="exampleInputEmail2"><?php echo $form->get('identity')->getAttribute('placeholder'); ?></label>
                            <?php echo $this->formInput($form->get('identity')->setAttributes(array('class' => 'form-control'))) ?>
                        </div>
                        <div class="form-group">
                           <label class="sr-only" for="exampleInputPassword2"><?php echo $form->get('credential')->getAttribute('placeholder'); ?></label>
                            <?php echo $this->formInput($form->get('credential')->setAttributes(array('class' => 'form-control'))) ?>
                            <a href="<?php echo $this->url('frontend/zfcuser/forgotpassword', array('channel' => $this->channel)) ?>">
                                <?php echo $this->translate('Forgot your password?');?>
                            </a>
                        </div>
                        <?php if ($this->redirect): ?>
                            <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
                        <?php endif ?>
                        <div class="form-group">
                            <?php echo $this->formButton($form->get('submit')->setAttributes(
                                array('class' => 'btn btn-default btn-block', 'id' => 'login-header-btn')
                            )) ?>
                        </div>
                     </form>
                    <?php echo $this->form()->closeTag() ?>
               </div>
            </li>
            <li>
                <!--a href="<?php echo $this->url('frontend/zfcuser/register',array('socialnetwork' => 'facebook', 'channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '');?>" class="fbconnect-header">
                   <img src="<?php echo $this->frontendAssetPath('images/header/fb-connect.png') ?>" alt="Facebook Connect" />
                </a-->
                <a href="<?php echo $this->url('frontend/zfcuser/register',array('socialnetwork' => 'facebook', 'channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '');?>" class="btn btn-primary" id="sign-in-google">Sign In with Facebook</a>
            </li>
         </ul>
  </li>
</ul>