<?php
$this->plugin('translate')->setTranslatorTextDomain('playgrounduser');
$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'validate');
?>

<div id="register-form" class="coordinates row">
	<!-- start form -->
    <?php echo $this->form()->openTag($form) ?>
		<div class="row">
			<div class="block-left col-md-4">
			    <?php echo $form->get('lastname')->getLabel(); ?>
			</div>
			<div class="block-right col-md-4">
				<?php echo $this->formInput($form->get('lastname')->setAttributes(array('class' => 'form-control'))) ?>
				<?php echo $this->formElementErrors($form->get('lastname')) ?>
			</div>
		</div>
		<div class="row">
			<div class="block-left col-md-4">
			    <?php echo $form->get('firstname')->getLabel(); ?>
			</div>
			<div class="block-right col-md-4">
				<?php echo $this->formInput($form->get('firstname')->setAttributes(array('class' => 'form-control'))) ?>
				<?php echo $this->formElementErrors($form->get('firstname')) ?>
			</div>
		</div>
		<div class="row">
			<div class="block-left col-md-4">
			    <?php echo $form->get('email')->getLabel(); ?>
		    </div>
			<div class="block-right col-md-4">
			    <?php echo $this->formInput($form->get('email')->setAttributes(array('class' => 'form-control'))) ?>
			    <?php echo $this->formElementErrors($form->get('email')) ?>
			</div>
		</div>
		<div class="row">
			<div class="block-left col-md-4">
			    <?php echo $this->translate('Confirmer votre email'); ?>
		    </div>
			<div class="block-right col-md-4">
			    <input name="emailConfirm" type="email" class="form-control" placeholder="" value="">
			</div>
		</div>

		<!-- opt-in -->
		<div class="row opt-in">
			<div class="col-md-2">
				<input type="checkbox" name="optin" value="1">
			</div>
			<div class="col-md-8">
				<p>
				    <?php echo $this->translate('S\'inscrire à la newsletter')?>
				</p>
			</div>
		</div>

		<div id="btn-create-account" class="row">
			<div class="col-md-7 center">
				<?php echo $this->formButton($form->get('submit')->setAttributes(array('class' => 'btn btn-default'))) ?>
			</div>
		</div>
		<?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
        <?php endif ?>
    <?php echo $this->form()->closeTag() ?>
	<!-- end form -->
</div>
