<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-default right')) ?>

<h1><?php echo $this->translate($this->title); ?></h1>

<div id="content" class="tabbable tabs-left">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#general" data-toggle="tab"><?php echo $this->translate('General'); ?></a></li>
        <li><a href="#mechanics" data-toggle="tab"><?php echo $this->translate('Game Mechanics'); ?></a></li>
        <li><a href="#prizes" data-toggle="tab"><?php echo $this->translate('Lots'); ?></a></li>
        <li><a href="#platform" data-toggle="tab"><?php echo $this->translate('Plateforme'); ?></a></li>
        <li><a href="#facebook" data-toggle="tab"><?php echo $this->translate('Facebook'); ?></a></li>
        <li><a href="#design" data-toggle="tab"><?php echo $this->translate('Design'); ?></a></li>
        <li><a href="#column" data-toggle="tab"><?php echo $this->translate('Colonne de droite'); ?></a></li>
        <li><a href="#share" data-toggle="tab"><?php echo $this->translate('Partage'); ?></a></li>
        <li><a href="#welcome_page" data-toggle="tab"><?php echo $this->translate('Bloc de bienvenue'); ?></a></li>
        <li><a href="#terms_page" data-toggle="tab"><?php echo $this->translate('Page de règlement'); ?></a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <?php echo $this->game_form;?>

        <div class="tab-pane" id="mechanics">
        	<div class="form-group">
	            <?php //echo $this->formLabel($form->get('occurrenceType')); ?>
	            <?php echo $this->formInput($form->get(('occurrenceType'))->setAttribute('class', 'form-control')); ?>
	            <?php //echo $this->formElementErrors() ?>
	        </div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('scheduleOccurrenceAuto')); ?>
	            <?php echo $this->formSelect($form->get(('scheduleOccurrenceAuto'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('scheduleOccurrenceAuto'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('occurrenceNumber')); ?>
	            <?php echo $this->formInput($form->get(('occurrenceNumber'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('occurrenceNumber'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('occurrenceDrawFrequency')); ?>
	            <?php echo $this->formSelect($form->get(('occurrenceDrawFrequency'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('occurrenceDrawFrequency'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('uploadScratchcardImage')); ?>
	            <?php echo $this->formFile($form->get('uploadScratchcardImage')); ?>
	            <?php if($form->get('scratchcardImage')->getValue() != ''):?>
	            	<img src="<?php echo $this->basePath($form->get('scratchcardImage')->getValue()); ?>" />
	            <?php endif;?>
	        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>