<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<div class="game-lottery row-fluid welcome">
	<h1><?php echo $this->game->getTitle(); ?></h1>

	<!-- BLOCK GAME START -->
    <?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game, 'channel' => $this->channel));?>
    <!-- END BLOCK GAME START -->

	<!-- contenu article -->
    <div id="content-article" class="lottery">
		<div class="welcome-block<?php if($this->layout()->facebooktemplate): echo ' fb-target'; endif ?>">
		    <?php echo $this->game->getWelcomeBlock(); ?>
		</div>
		<?php if($this->game->isStarted()):?>
        <div class="clearfix">
    		<div class="btn btn-default btn-arrow-right"<?php if ($this->isCtaActive) { echo ' id="fb-play"'; } ?>>
    			<a href="<?php echo $this->url('frontend/'. $this->game->getClassType() . '/'. $this->game->nextStep('index'), array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" class="arrow-right">
    				<span class="left">left</span>
    				<span class="center"><?php echo $this->translate('Participate'); ?></span>
    				<span class="right">right</span>
    			</a>
            </div>
        </div>
		<?php endif;?>
	</div>
</div>