<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<div class="row looser">
	<div class="col-md-1">
		<img src="<?php echo $this->frontendAssetPath('images/common/round-wrong.png')?>" alt="Perdu" class="result-quizz" />
	</div>
	<div class="col-md-11">
		<?php if(count($this->flashMessages)>0):?>
			<p class="already-play"><?php echo $this->flashMessages[0];?></p>
	    <?php endif;?>
        <p id="valid-text">
            <?php echo $this->userCorrectAnswers ?>/<?php echo $this->maxCorrectAnswers?> <?php echo $this->translate('good answers'); ?>. <br/>
            <?php echo $this->translate('Thank you for playing, unfortunately you do not have the right answers'); ?>...<br/>
	    </p>
	</div>
</div>
