<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
			
<div class="row <?php if($this->prediction):?>prediction<?php endif; ?>">
	<div class="col-md-1">
		<img src="<?php echo $this->frontendAssetPath('images/common/round-valid.png')?>" alt="Gagné" class="result-quizz" />
	</div>
	<div class="col-md-11">
		<?php if(count($this->flashMessages)>0):?>
			<p class="already-play"><?php echo $this->flashMessages[0];?></p>
	    <?php endif;?>
        <p id="valid-text">
        <?php if(! $this->prediction):?>
            <?php if($this->userCorrectAnswers >= $this->maxCorrectAnswers && $this->game->getVictoryConditions() > 0):?>
    			<?php echo $this->translate('Congratulations you have all the right answers !');?><br/>
    	    <?php elseif($this->game->getVictoryConditions() > 0):?>
    	        <?php echo $this->translate('Congratulations, you have');?> <?php echo $this->userCorrectAnswers;?> <?php echo $this->translate('good answers');?> <?php echo $this->translate('on');?> <?php echo $this->maxCorrectAnswers;?>!<br/>
    	    <?php else:?>
    	        <?php echo $this->translate('Thanks to participate');?>,<br/>
    	    <?php endif;?>
            <?php echo $this->translate('Your participation in the draw has been taken into account !');?>
       <?php else:?> 
            <?php echo $this->translate('Thank you, your input has been taken into account!');?>
       <?php endif;?>
	   </p>
	</div>
</div>
