<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<div id="terms" class="game-postvote row-fluid">
	<h1><?php echo $this->translate('Rules'); ?></h1>
	
	<?php if($this->layout()->facebooktemplate): ?><div class="fb-target"><?php endif ?>
		<?php echo $this->game->getTermsBlock();?>
	<?php if($this->layout()->facebooktemplate): ?></div><?php endif ?>

</div>