<?php $this->plugin('translate')->setTranslatorTextDomain('adfabgame');// Pour le texte ?>

<!-- THEMATIQUES -->
<div id="jeux-concours" class="thematique">
    <div class="row-fluid">
        <h1><?php echo $this->prizeCategory->getTitle();?></h1>
    </div>
	<?php
		if(count($this->flashMessages)>0):
			echo $this->flashMessages[0];
		else :
			$this->partialLoop()->setObjectKey('game');
    		echo $this->partialLoop('adfab-game/partial/game.phtml', array('game' => $this->games, 'channel' => $this->channel));
		endif;
		
	?>
</div><!-- END THEMATIQUES -->
<?php echo $this->paginationControl($this->games, 'Sliding', 'adfab-game/prize-category/pagination.phtml', array('id' => $this->identifier)); ?>