<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundreward');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form) 
?>
<div class="row-fluid show-grid">
    <div class="span8">
        <?php echo $this->formHidden($form->get('id')); ?>

        <?php echo $this->formLabel($form->get('name')); ?>
        <?php echo $this->formInput($form->get('name')); ?>
        <?php echo $this->formElementErrors($form->get('name')) ?>
    </div>
</div>
<div class="row-fluid show-grid">
    <div class="span12">
        <?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
        <?php echo $this->formButton($form->get('submit')) ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>