<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<div class="corrections row-fluid">
	<div class="span10 offset2">
		<ul>
			<?php $i=0; foreach($this->gameCorrectAnswers as $q):?>
			    <li class="question<?php if($this->layout()->facebooktemplate): echo ' fb-target'; endif ?>"><b><?php echo $this->translate('Question'); ?> <?php echo $i+1; ?> :</b> <?php echo $q['question'];?>
				    <ul>
    				<?php foreach ($q['answers'] as $k => $a):?>			
        				<li class="response">
                            <?php if($a['correctAnswers']) : ?>
                                <?php if($a['found']) : ?>
                                    <span class="right-answer"><?php echo $this->translate('Good answer !'); ?> </span>
                                    <?php echo $a['answer']; ?>
                                <?php else : ?>
                                    <span class="your-answer"><?php echo $this->translate('You didn\'t find'); ?>  </span>
                                    <?php echo $a['answer']; ?>
                                <?php endif; ?>
                            <?php else : ?>
                                <?php if($a['yourChoice']) : ?>
                                    <span class="your-answer"><?php echo $this->translate('Your choice : '); ?> </span>
                                    <?php echo $a['answer']; ?>
                                <?php else : ?>
                                    <?php echo $a['answer']; ?>
                                <?php endif; ?>
                            <?php endif; ?>
        				</li>
    				<?php endforeach;?>
    				</ul>
    			</li>
			<?php ++$i;endforeach;?>
		</ul>
	</div>
</div>