<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<div class="game-instantwin welcome">
	<h1>
	    <?php echo $this->game->getTitle(); ?>
	</h1>
	<!-- BLOCK GAME START -->
    <?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game, 'channel' => $this->channel));?>
    <!-- END BLOCK GAME START -->
	<!-- contenu article -->
	<div id="content-article" >
		<div class="welcome-block<?php if($this->layout()->facebooktemplate): echo ' fb-target'; endif ?>">
		    <?php echo $this->game->getWelcomeBlock(); ?>
		</div>
		<div class="center">
			<div class="btn-group btn-default">
	    		<?php if($game->isStarted()):?>
	    			<?php if($game->getTermsOptin()):?>
	    				<?php echo $this->translate('I accept the rules'); ?>
	    			<?php endif;?>
	    		    <a href="<?php echo $this->url('frontend/instantwin/play', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" class="btn btn-default"<?php if ($this->isCtaActive) { echo ' id="cta-play"'; } ?> >
	    		        <span class="left">left</span><span class="center"><?php echo $this->translate('Participate'); ?></span><span class="right">right</span>
	    		    </a>
	    		<?php endif;?>
	        </div>
	         <p id="reglement">
				<a href="<?php echo $this->url('frontend/instantwin/terms', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" class="btn btn-default" >
	                <?php echo $this->translate('Rules'); ?>
	            </a>
			</p>
        </div>
	</div>
</div>
