<?php $cpt = 0; ?>
<div id="carousel-pictures" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
    <?php foreach ($this->data as $key => $value) : ?>
        <div class="item <?php if($cpt++ == 0) { echo 'active'; }; ?>">
            <img src="<?php echo $this->basePath($value); ?>" alt="" />
            <div class="carousel-caption"></div>
        </div>
    <?php endforeach; ?> <!-- Controls -->
    </div>
    <a class="left carousel-control" href="#carousel-pictures" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-pictures" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>