<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 4.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title></title>
</head>
<body>
<table width="100%" cellpadding="0" cellspacing="5" border="0" bgcolor="#F3F3F3">
	<tr>
		<td align="center">
			<table width="516" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td height="952">
							<table width="516" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
								<tr height="952" align="left">
									<td height="952" width="18" style="font-size:0" valign="top">
										<img border="0" src="<?php echo $this->skinUrl.'images/content/email/email1-big.jpg';?>" alt="" height="952" width="18"/>
									</td>
									<td height="952" width="480" style="font-size:0" valign="top">
										<table width="480" cellpadding="0" cellspacing="0" border="0">
											<tr height="102">
												<td height="102" width="480" valign="top">
													<table width="480" cellpadding="0" cellspacing="0" border="0">
														<tr height="102">
															<td height="102" width="417" style="font-size:0"><img border="0" src="<?php echo $this->skinUrl.'images/content/email/email3.jpg';?>" alt="" height="102" width="417"/></td>
															<td height="102" width="63" style="font-size:0"><a href="http://facebook.com/playground/"><img border="0" src="<?php echo $this->skinUrl.'images/content/email/email4.jpg';?>" alt="" height="102" width="63"/></a></td>
														</tr>
													</table>
												</td>
											</tr>
											<tr height="487">
												<td height="487" width="480" style="font-size:0">
													<table width="480" cellpadding="0" cellspacing="0" border="0">
														<td height="487" width="15" valign="bottom" style="font-size:0"><img border="0" src="<?php echo $this->skinUrl.'images/content/email/email5.jpg';?>" alt="" height="487" width="15"/></td>
														<td height="487" width="450">
															<table width="450" cellpadding="0" cellspacing="0" border="0">
																<tr height="487">
																	<td height="487" width="450">
																		<table width="450" cellpadding="0" cellspacing="0" border="0">
																			<tr height="85">
																				<td height="85" width="450" style="font-size:18px;">
																					<font face="Arial" color="#FFFFFF" style="font-size:18px;background-color:#8DC63F;padding-left:5px;padding-top:5px;padding-bottom:5px;padding-right:5px;line-height:35px;"><?php echo $this->translate('Good morning'); ?>,</font><br/>
																					<font face="Arial" color="#FFFFFF" style="font-size:18px;background-color:#8DC63F;padding-left:5px;padding-top:5px;padding-bottom:5px;padding-right:5px;"><?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->translate('invites you to discover Playground'); ?> :</font><br/>
																					<font face="Arial" color="#565656" style="font-size:14px;line-height:50px;"><b><?php echo $this->translate('Try to win lots of gifts !'); ?></b></font>
																				</td>
																			</tr>
																			
																			<tr height="35">
																				<td height="35" width="450" style="font-size:14px;">
																					<font face="Arial" color="#565656"><?php echo $this->translate('Join our games and try to win loads of freebies! High tech, culture, travel ... There\'s something for everyone!'); ?>. </font>
																				</td>
																			</tr>
																			<tr height="55">
																				<td height="55" width="450" style="font-size:24px;">
																					<font face="Arial" color="#8DC63F"><b><?php echo $this->translate('See the games being'); ?> :</b></font>
																				</td>
																			</tr>
																			
																			<!-- -->
																			<?php $i = 1; foreach($this->game as $onegame): ?>
																			<tr height="65">
																				<td height="65" width="450" style="font-size:24px;">
																					<font face="Arial" color="#000000"><?php echo htmlentities($onegame->getTitle(), ENT_QUOTES, "UTF-8"); ?></font>
																				</td>
																			</tr>
																			<tr height="115">
																				<td height="115" width="450" style="font-size:0px;">
																					<img border="0" src="<?php echo $this->url('frontend', array('channel' => $this->channel), array('force_canonical' => true)).$onegame->getMainImage(); ?>" alt="" height="115" width="450"/>
																				</td>
																			</tr>
																			<tr height="55">
																				<td height="55" width="450" style="font-size:14px;">
																					<table width="450" cellpadding="0" cellspacing="0" border="0">
																						<tr height="55">
																							<td height="55" width="305" style="font-size:13px">
																								<font face="Arial" color="#000000">
																								<b>Jeu offert par 
																									<?php if($onegame->getPartner()): echo htmlentities($onegame->getPartner()->getName(), ENT_QUOTES, "UTF-8"); else : echo 'Playground'; endif; ?>
																								</b>
																								</font>
																							</td>
																							<td height="55" width="152" style="font-size:0px">
																								<?php $gameclasstype = str_replace('/', '', $this->url('frontend/' . $onegame->getClassType())); ?>
																								<a href="<?php echo $this->skinUrl . $gameclasstype . '/' . $onegame->getIdentifier();?>?key=<?php echo $this->secretKey ?>"><img border="0" src="<?php echo $this->skinUrl.'images/content/email/jouer.jpg';?>" alt="Jouer" height="45" width="152"/></a>
																							</td>
																						</tr>
																					</table>
																				</td>
																			</tr>
																			<tr height="35">
																				<td height="35" width="450" style="font-size:0">
																					<img border="0" src="<?php echo $this->skinUrl.'images/content/email/email7.jpg';?>" alt="" height="35" width="450"/>
																				</td>
																			</tr>
																			<?php if($i == 2): break; endif; ?>
																			<?php $i++; endforeach; ?>
																			<!-- -->
																			
																			<tr height="54">
																				<td height="54" width="450" style="font-size:14px;" align="center">
																					<font face="Arial" color="#565656"><b><?php echo $this->translate('Thank you and see you soon on Playground!'); ?></b><br/><?php echo $this->translate('Playground team'); ?></font>
																				</td>
																			</tr>
																			<tr height="20">
																				<td height="20" width="450" style="font-size:0">
																					<img border="0" src="<?php echo $this->skinUrl.'images/content/email/email8.jpg';?>" alt="" height="20" width="450"/>
																				</td>
																			</tr>
																			<tr height="38">
																				<td height="38" width="450" bgcolor="#F3F3F3">
																					<table width="450" cellpadding="0" cellspacing="0" border="0">
																						<tr height="38">
																							<td height="38" width="124" style="font-size:0">&nbsp;</td>
																							<td height="38" width="208" style="font-size:0">
																								<table width="208" cellpadding="0" cellspacing="0" border="0">
																									<tr height="38">
																										<td height="38" width="34" style="font-size:0">
																											<img border="0" src="<?php echo $this->skinUrl.'images/content/email/email9.jpg';?>" alt="" height="38" width="34"/>
																										</td>
																										<td height="38" width="174" style="font-size:14px">
																											<a href="http://facebook.com/playground/" style="color:#3B5A99;"><font face="Arial" color="#3B5A99"><?php echo $this->translate('Follow us on Facebook'); ?></font></a>
																										</td>
																									</tr>
																								</table>
																							</td>
																							<td height="38" width="118" style="font-size:0">&nbsp;</td>
																						</tr>
																					</table>
																				</td>
																			</tr>
																		</table>
																	</td>
																</tr>
															</table>
														</td>
														<td height="487" width="15" valign="bottom" style="font-size:0"><img border="0" src="<?php echo $this->skinUrl.'images/content/email/email5.jpg';?>" alt="" height="487" width="15"/></td>
													</table>
												</td>
											</tr>
										</table>
									</td>
									<td height="952" width="18" style="font-size:0" valign="top">
										<img border="0" src="<?php echo $this->skinUrl.'images/content/email/email2-big.jpg';?>" alt="" height="952" width="18"/>
									</td>	
								</tr>	
							</table>
					</td>					
				</tr>	
			</table>		
		</td>
	</tr>
</table>
		
</body>
</html>
