<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php if ($this->game->getStartDate() && $this->game->getEndDate()):?>
    <?php $play =  $this->translate('Play').' '.$this->translate('from').' ' . strftime("%d %B", $this->game->getStartDate()->format('U')) . ' '.$this->translate('to').' ' . strftime("%d %B", $this->game->getEndDate()->format('U')) . ' '.$this->translate('with'); ?>
<?php elseif ($this->game->getStartDate()):?>
    <?php $play =  $this->translate('Play').' '.$this->translate('after').' ' . strftime("%d %B", $this->game->getStartDate()->format('U')) . ' '.$this->translate('with');?>
<?php elseif ($this->game->getEndDate()):?>
    <?php $play =  $this->translate('Play').' '.$this->translate('up to').' ' . strftime("%d %B", $this->game->getEndDate()->format('U')) . ' '.$this->translate('with');?>
<?php else:?>
    <?php $play =  $this->translate('Play').' '.$this->translate('with');?>
<?php endif; ?>
<?php if ($this->game->isOpen()): ?>
<!-- BLOCK GAME START -->
<div class="block-game <?php if($this->game->isFinished()):?>over<?php else:?>start<?php endif;?> <?php if ($this->basePath($this->game->getMainImage()) == "") echo "no-image"; ?>">
	<div class="img-content">
		<a href="<?php echo $this->url('frontend/' . $this->game->getClassType(), array('id' =>$this->game->getIdentifier(), 'channel' => $this->layout()->channel)); ?>">
            <?php if ($this->basePath($this->game->getMainImage()) != "") : ?>
                <img class="rounded" src="<?php echo $this->basePath($this->game->getMainImage()); ?>" alt="<?php echo $this->game->getTitle()?>" />
			<?php endif;?>
		</a>
		<div class="icon-bloc-game <?php echo $this->game->getClassType();?>">&nbsp;</div>
		<?php if($this->game->getPartner() && $this->game->getPartner()->getLogo()):?>
			<div class="logo-sponsor">
				<img src="<?php echo $this->basePath($this->game->getPartner()->getLogo());?>" alt="<?php echo $this->game->getPartner()->getName();?>" />
			</div>
		<?php else :?>
			<div class="logo-sponsor">		
				<img src="<?php echo $this->frontendAssetPath('images/common/logo-game-start.png')?>" alt="logo" />
			</div>
		<?php endif;?>
		
		<div class="dark-overlay row">
			<div class="col-md-12">
		        <div class="wrapper-game">
		        	<h2 class="col-md-10">
						<a href="<?php echo $this->url('frontend/' . $this->game->getClassType(), array('id' =>$this->game->getIdentifier(), 'channel' => $this->layout()->channel)); ?>">
							<?php echo $this->game->getTitle()?>
						</a>
					</h2>
			        <div class="game-infos">
						<div class="desc <?php echo $this->game->getClassType();?>">
							<?php echo $this->translate($this->game->getClassType());?> : <?php echo $play;?>
						</div>
						<div class="logo-partner">
							<?php if($this->game->getPartner()):?>
								<?php if($this->game->getPartner()->getSmallLogo()) : ?>
									<img src="<?php echo $this->basePath($this->game->getPartner()->getSmallLogo()) ?>" alt="<?php echo $this->game->getPartner()->getName();?>" class="logo"/>
								<?php else:?>
									<span>
									    <?php echo $this->game->getPartner()->getName();?>
									</span>
								<?php endif;?>
							<?php else :?>
								<img src="<?php echo $this->frontendAssetPath('images/common/logo-game-start.png');?>" alt="Logo" class="logo"/>
							<?php endif;?>
						</div>
						<?php if(!$this->game->isFinished()):?>
							<?php echo $this->partial(
				                'playground-game/partial/share.phtml',
				                array(
				                    'color' => 'grey',
				                    'game'=>$this->game,
				                    '$this->layout()->channel' => $this->layout()->channel,
				                    'url'=>$this->url(
				                        'frontend/' . $game->getClassType(), array('id' => $this->game->getIdentifier()),
				                        array(
				                            'force_canonical' => true
				                        )
				                    )
				                )
				            );?>
						<?php endif;?>
					</div>			        
			        <ul class="social-share">
			        	<li><a href="#" class="link fb">&nbsp;</a></li>
			        	<li><a href="#" class="link twitter">&nbsp;</a></li>
			        	<li><a href="#" class="link google">&nbsp;</a></li>
			        </ul>
		        </div>
		        <div class="button-play">
		        	<?php if($game->isStarted()):?>
			            <div class="button-wrap">
			                <div class="btn btn-orange">
			                    <a href="<?php echo $this->url('frontend/' . $game->getClassType(), array('id' => $game->getIdentifier(), 'channel' => $this->channel)) ; ?>" class="arrow-right-big">
			                        <?php echo $this->translate('Play'); ?>
			                    </a>
			                </div>
			            </div>
			        <?php elseif($game->isOpen() && !$game->isFinished() ):?>
			            <div class="button-wrap">
			                <div class="btn btn-orange">
			                    <a href="<?php echo $this->url('frontend/' . $game->getClassType(), array('id' => $game->getIdentifier(), 'channel' => $this->channel)) ; ?>" class="arrow-right-big">
			                        <?php echo $this->translate('Soon'); ?>
			                    </a>
			                </div>
			            </div>
		        <?php endif;?>
		        </div>
		    </div>
		</div>
        <?php if($this->game->isFinished()):?>
            <div class="stamp">
                <img src="<?php echo $this->frontendAssetPath('images/common/stamp-termine.png')?>" alt="<?php echo $this->translate('game ended'); ?>" />
            </div>
        <?php endif;?>
	</div>
</div>
<!-- END BLOCK GAME START -->
<?php endif; ?>
