<?php if ($game->getStartDate() && $game->getEndDate()):?>
    <?php $play =   $this->translate('Play').' '.$this->translate('from').' ' . strftime("%d %B", $game->getStartDate()->format('U')) . ' au ' . strftime("%d %B", $game->getEndDate()->format('U')) . ' '.$this->translate('with');?>
<?php elseif ($game->getStartDate()):?>
    <?php $play =  $this->translate('Play').' '.$this->translate('after').' ' . strftime("%d %B", $game->getStartDate()->format('U')) . ' '.$this->translate('with');?>
<?php elseif ($game->getEndDate()):?>
    <?php $play =  $this->translate('Play').' '.$this->translate('up to').' ' . strftime("%d %B", $game->getEndDate()->format('U')) . ' '.$this->translate('with');?>
<?php else:?>
    <?php $play =  $this->translate('Play').' '.$this->translate('with');?>
<?php endif; ?>
<div class="item <?php if(isset($game->first) && $game->first) echo "active"; ?> ">
    <img src="<?php echo $this->basePath($game->getMainImage());?>" alt="<?php echo $game->getTitle(); ?>" />
    <div class="carousel-caption">
        <h1 class="title-promo">
            <a href="<?php echo $this->url('frontend/' . $game->getClassType(), array('id' => $game->getIdentifier(), 'channel' => $this->channel)) ; ?>">
                <?php echo $game->getTitle(); ?>
            </a>
        </h1>
        <?php if($game->isStarted()):?>
            <div class="button-wrap">
                <div class="btn btn-orange">
                    <a href="<?php echo $this->url('frontend/' . $game->getClassType(), array('id' => $game->getIdentifier(), 'channel' => $this->channel)) ; ?>" class="arrow-right-big">
                        <?php echo $this->translate('Play'); ?>
                    </a>
                </div>
            </div>
        <?php elseif($game->isOpen() && !$game->isFinished() ):?>
            <div class="button-wrap">
                <div class="btn btn-orange">
                    <a href="<?php echo $this->url('frontend/' . $game->getClassType(), array('id' => $game->getIdentifier(), 'channel' => $this->channel)) ; ?>" class="arrow-right-big">
                        <?php echo $this->translate('Soon'); ?>
                    </a>
                </div>
            </div>
        <?php endif;?>
    </div>
</div>