<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<div class="return"><a href="<?php echo $this->url('admin/playgroundflow/object/attribute');?>"><?php echo $this->translate('Retour'); ?></a></div>

<h1><?php echo $this->translate('Edition'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?><?php echo $this->formButton($form->get('submit')) ?>

<div id="content">
        <div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('xpath')); ?>
	            <?php echo $this->formInput($form->get('xpath')); ?>
	            <?php echo $this->formElementErrors($form->get('xpath')) ?>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>