<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundflow');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<div class="return"><a href="<?php echo $this->url('admin/playgroundflow/domain');?>"><?php echo $this->translate('Retour'); ?></a></div>

<h1><?php echo $this->translate('Création'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?><?php echo $this->formButton($form->get('submit')) ?>

<div id="content">
        <div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('title')); ?>
	            <?php echo $this->formInput($form->get(('title'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('title'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('domain')); ?>
	            <?php echo $this->formInput($form->get(('domain'))->setAttribute('class', 'form-control')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('domain'))) ?>
			</div>
			<div class="form-group">
	            <?php echo $this->formLabel($form->get('description')); ?>
	            <?php echo $this->formTextarea($form->get(('description'))->setAttribute('class', 'form-control')->setAttribute('row', '4')); ?>
	            <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('description'))) ?>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>