<?php
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-default right')) ?>

<h1><?php echo $this->translate('Edit FAQ'); ?></h1>

<div>
        <?php echo $this->formHidden($form->get('id')); ?>

        <div class="form-group">
        <?php echo $this->formTextarea($form->get(('question'))->setAttribute('class', 'form-control')->setAttribute('row', '4')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('question'))) ?>
        <?php $this->QgCKEditor(
            'question',
                array(
                	'BasePath' => $this->libAssetPath('js/ckeditor'),
                	'Width' => "50%",
                    'Height' => "100",
                    //'filebrowserBrowseUrl' => '/elfinder', // eg. 'includes/elFinder/elfinder.html'
                    'uiColor' => '#9AB8F3',
                    //'Color' => "#000",
                    'Toolbar'=> array(
                         array('Bold','Italic','Underline','NumberedList','BulletedList','Outdent','Indent','Link','Unlink','Source'),
                     )
                )
            );
        ?>
        <div>
        <div class="form-group">
        <?php echo $this->formTextarea($form->get(('answer'))->setAttribute('class', 'form-control')->setAttribute('row', '4')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('answer'))) ?>
        <?php $this->QgCKEditor(
            'answer',
                array(
                	'BasePath' => $this->libAssetPath('js/ckeditor'),
                	'Width' => "50%",
                    'Height' => "100",
                    //'filebrowserBrowseUrl' => '/elfinder', // eg. 'includes/elFinder/elfinder.html'
                    'uiColor' => '#9AB8F3',
                    //'Color' => "#000",
                    'Toolbar'=> array(
                         array('Bold','Italic','Underline','NumberedList','BulletedList','Outdent','Indent','Link','Unlink','Source'),
                     )
                )
            );
        ?>
        <div>
        <div class="form-group">
        <?php echo $this->formLabel($form->get('isActive')); ?>
        <?php echo $this->formSelect($form->get(('isActive'))->setAttribute('class', 'form-control')); ?>
        <?php echo $this->formElementErrors()
						->setMessageOpenFormat('<div class="alert alert-danger">')
						->setMessageCloseString('</div>')->render($form->get(('isActive'))) ?>
        <div>

</div>

<?php echo $this->form()->closeTag() ?>

