<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<div class="sidebar col-md-4">
	<div>
		<!-- COLUMNBLOCK1 (if not null) -->
		<?php if($this->game->getColumnBlock1() != ''):?>
			<div class="sd-block block-custom">
				<?php echo $this->game->getColumnBlock1();?>
			</div>
		<?php endif; ?>
		<!-- END COLUMNBLOCK1 -->
		<!-- COLUMNBLOCK2 (if not null) -->
		<?php if($this->game->getColumnBlock2() != ''):?>
		<div class="sd-block block-custom">
			<?php echo $this->game->getColumnBlock2();?>
		</div>
		<?php endif;?>
		<!-- END COLUMNBLOCK2 -->
		<div id="sidebar-game" class="sd-block">
			<p class="green"><?php echo $this->translate('How to participate ?'); ?></p>
			<div id="reply" class="row">
				<div class="col-md-2">
					<img src="<?php echo $this->frontendAssetPath('images/common/btn-reply.png') ?>" alt="" />
				</div>
				<div class="col-md-10">
					<p><?php echo $this->translate('Click to participate'); ?></p>
				</div>
			</div>
			<div id="quiz-question" class="row">
				<div class="col-md-2">
					<img src="<?php echo $this->frontendAssetPath('images/common/btn-question.png') ?>" alt="" />
				</div>
				<?php
					$questions = $this->game->getQuestions();
					$prediction = false;
			        foreach ($questions as $q) {
			            if($q->getPrediction()){
			                $prediction = true;
			            }
			        }
				?>
				<!-- Pronostic -->
				<?php if($prediction == true): ?> 
					<div class="col-md-10 col-prediction">
						<p><?php echo $this->translate('Choose your answer'); ?></p>
					</div>
				<!-- Condition 0 => sondage -->
				<?php elseif($game->getVictoryConditions() == 0): ?>
					<div class="col-md-10 col-novictory">
						<p><?php echo $this->translate('Answer the questions'); ?></p>
					</div>
				<!-- Condition > 0 -->
				<?php else : ?>
					<div class="col-md-10">
						<p><?php echo $this->translate('Correctly answer the questions'); ?></p>
					</div>
				<?php endif; ?>
			</div>
			<div id="ecusson" class="row">
				<div class="col-md-2">
					<img src="<?php echo $this->frontendAssetPath('images/common/btn-ecusson.png') ?>" alt="" />
				</div>
				<!-- Pronostic -->
				<?php if($prediction == true): ?>
					<div class="col-md-10 col-prediction">
						<p><?php echo $this->translate('Pronostic message'); ?></p>
					</div>
				<!-- 0 ou 100 => sondage ou 100% de bonnes réponses -->
				<?php elseif($game->getVictoryConditions() == 0 || $game->getVictoryConditions() == 100): ?>
					<div class="col-md-10 col-novictory">
						<p><?php echo $this->translate('Your participation in the draw will be taken into account!'); ?> <?php echo $this->translate('You can earn more chances by inviting your friends to play'); ?></p>
					</div>
				<!-- 0 < Condition < 100 -->
				<?php else: ?>
					<div class="col-md-10">
						<p><?php echo $this->translate('If you find enough good answers, your participation in the draw will be taken into account!');?> <?php echo $this->translate('You can earn more chances by inviting your friends to play'); ?></p>
					</div>
				<?php endif; ?>
			</div>
		</div>
		<!-- COLUMNBLOCK3 (if not null) -->
		<?php if($this->game->getColumnBlock3() != ''):?>
			<div class="sd-block block-custom">
				<?php echo $this->game->getColumnBlock3();?>
			</div>
		<?php endif;?>
		<!-- END COLUMNBLOCK3 -->
	</div>
</div>
