<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<div class="sidebar game-sidebar col-md-4">
	<div>
		<!-- COLUMNBLOCK1 (if not null) -->
		<?php if($this->game->getColumnBlock1() != ''):?>
			<div class="sd-block block-custom">
				<?php echo $this->game->getColumnBlock1();?>
			</div>
		<?php endif; ?>
		<!-- END COLUMNBLOCK1 -->
		<!-- COLUMNBLOCK2 (if not null) -->
		<?php if($this->game->getColumnBlock2() != ''):?>
		<div class="sd-block block-custom">
			<?php echo $this->game->getColumnBlock2();?>
		</div>
		<?php endif;?>
		<!-- END COLUMNBLOCK2 -->
		<div id="sidebar-game" >
			<div class="sd-block participate">
				<img src="<?php echo $this->frontendAssetPath('images/common/icon-participate.png')?>" alt="participate" />
				<h5><?php echo $this->translate('How to participate ?'); ?></h5>
				<div class="sb-content">
					<ul id="reply" class="row links-list">
						<li><?php echo $this->translate('Click to participate'); ?></li>
						<li>
							<?php
								$questions = $this->game->getQuestions();
								$prediction = false;
						        foreach ($questions as $q) {
						            if($q->getPrediction()){
						                $prediction = true;
						            }
						        }
							?>
							<!-- Pronostic -->
							<?php if($prediction == true): ?> 
								<?php echo $this->translate('Choose your answer'); ?>
							<!-- Condition 0 => sondage -->
							<?php elseif($game->getVictoryConditions() == 0): ?>
								<?php echo $this->translate('Answer the questions'); ?>
							<!-- Condition > 0 -->
							<?php else : ?>
								<?php echo $this->translate('Correctly answer the questions'); ?>
							<?php endif; ?>
						</li>
						<li>
							<!-- Pronostic -->
							<?php if($prediction == true): ?>
								<?php echo $this->translate('Pronostic message'); ?>
							<!-- 0 ou 100 => sondage ou 100% de bonnes réponses -->
							<?php elseif($game->getVictoryConditions() == 0 || $game->getVictoryConditions() == 100): ?>
								<?php echo $this->translate('Your participation in the draw will be taken into account!'); ?> <?php echo $this->translate('You can earn more chances by inviting your friends to play'); ?>
							<!-- 0 < Condition < 100 -->
							<?php else: ?>
								<?php echo $this->translate('If you find enough good answers, your participation in the draw will be taken into account!');?> <?php echo $this->translate('You can earn more chances by inviting your friends to play'); ?>
							<?php endif; ?>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!-- COLUMNBLOCK3 (if not null) -->
		<?php if($this->game->getColumnBlock3() != ''):?>
			<div class="sd-block block-custom">
				<?php echo $this->game->getColumnBlock3();?>
			</div>
		<?php endif;?>
		<!-- END COLUMNBLOCK3 -->
	</div>
</div>
