<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('frontend/quiz/play', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel)));
?>
<?php $totalQuestions = count($this->questions);?>
<!-- GAME QUIZ - FERME QUESTIONS -->
<?php //if($this->state == 'quiz') : ?>
<div id="dz-root"></div>
<div class="game-quiz play wrap-game">
	<h1>
	    <?php echo $this->game->getTitle(); ?>
	</h1>
	
	<!-- Content -->
	<div id="content-article" class="content-game clearfix">
	    <div class="col-md-1"></div>
		<?php echo $this->form()->openTag($form) ?>
		<?php $i=0;foreach ($form as $groupFieldset): ?>
	        <div class="page col-md-10" id="<?php echo $groupFieldset->getName()?>">
                <?php foreach ($groupFieldset as $element): ?>
                <?php $question = $this->questions[$i];?>
    			<div>
    				<div class="heading">
                        Question <?php echo $i+1; ?>
                    </div>
    				<div class="orange-dot"></div>
    				<div class="question<?php if($this->layout()->facebooktemplate): echo ' fb-target'; endif ?>">
    				    <?php echo $question->getQuestion();?>
    				</div>
    				<?php if($question->getHint()):?>
				    <div class="clue<?php if($this->layout()->facebooktemplate): echo ' fb-target'; endif ?> text-center">
				        <span class="text-center">
				            <?php echo $this->translate('Indication'); ?> : 
				        </span>
				        <?php echo $question->getHint();?>
				    </div>
    				<?php endif;?>
    				<div class="wrap-checker">
    					<?php if($question->getImage()):?>
	        				<div>
	    						<img src="<?php echo $this->basePath($question->getImage())?>" class="question-image" alt="<?php echo $question->getQuestion();?>" />
	        					<div class="answers">
	        						<?php if ($element instanceof Zend\Form\Element\Radio): ?>
	                                    <?php // echo $this->formRadio($element, null, false) ?>
                                        <?php $attributes = $element->getAttributes(); ?>
                                        <?php foreach ($element->getValueOptions() as $k => $option) : ?>
                                            <label>
                                                <input type="radio" value="<?php echo $k ?>" name="<?php echo $attributes['name']; ?>">
                                                <?php echo $option ?>
                                            </label>
                                        <?php endforeach; ?> 
	                                <?php elseif ($element instanceof Zend\Form\Element\MultiCheckbox): ?>
	                                    <?php //echo $this->formMultiCheckbox($element);?>
                                        <?php $attributes = $element->getAttributes(); ?>
                                        <?php foreach ($element->getValueOptions() as $k => $option) : ?>
                                            <label>
                                                <input type="checkbox" value="<?php echo $k ?>" name="<?php echo $attributes['name']; ?>">
                                                <?php echo $option ?>
                                            </label>
                                        <?php endforeach; ?> 
	                                <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
	                                    <?php echo $this->formTextarea($element); ?>
	                                <?php endif;?>
                                    <?php if ( ! $element instanceof Zend\Form\Element\Textarea): ?>
                                    <!-- <div class="explanation">
                                        <?php foreach ($element->getvalueOptions() as $answerLabel) :?>
                                            <span><?php echo $this->explanations[$answerLabel]; ?></span>
                                        <?php endforeach; ?>  
                                    </div> -->
                                    <?php endif;?>
	                                <?php if ($element->getMessages()) : echo '<div class="quiz-error">Merci de répondre à la question.</div>'; endif; ?>
	        					</div>
	        				</div>
	    				<?php else:?>
	        				<?php if ($element instanceof Zend\Form\Element\Radio): ?>
	                            <?php //echo $this->formRadio($element) ?>
                                <?php $attributes = $element->getAttributes(); ?>
                                <?php foreach ($element->getValueOptions() as $k => $option) : ?>
                                    <label>
                                        <input type="radio" value="<?php echo $k ?>" name="<?php echo $attributes['name']; ?>">
                                        <?php echo $option ?>
                                    </label>
                                <?php endforeach; ?> 
	                        <?php elseif ($element instanceof Zend\Form\Element\MultiCheckbox): ?>
	                            <?php //echo $this->formMultiCheckbox($element);?>
                                <?php $attributes = $element->getAttributes(); ?>
                                <?php foreach ($element->getValueOptions() as $k => $option) : ?>
                                    <label>
                                        <input type="checkbox" value="<?php echo $k ?>" name="<?php echo $attributes['name']; ?>">
                                        <?php echo $option ?>
                                    </label>
                                <?php endforeach; ?>  
	                        <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
	                            <?php echo $this->formTextarea($element); ?>
	                        <?php endif;?>
                            <?php if ( ! $element instanceof Zend\Form\Element\Textarea): ?>
	                        <!-- <div class="explanation">
                                <?php foreach ($element->getvalueOptions() as $answerLabel) :?>
                                    <span><?php echo $this->explanations[$answerLabel]; ?></span>
                                <?php endforeach; ?>  
                            </div> -->
                            <?php endif;?>
							<?php if ($element->getMessages()) : echo '<div class="quiz-error">Merci de répondre à la question.</div>'; endif; ?>
	                    <?php endif;?>
    				</div>
                    <?php if($question->getVideo()):?>
                        <div class="video" data-src="<?php echo $question->getVideo(); ?>">
        					
        				</div>
                    <?php endif;?>
                    <?php if($question->getAudio() != 0):?>
                        <audio id="<?php echo $question->getAudio(); ?>" class="audio" controls="controls" value="<?php echo $question->getAutoplay(); ?>"></audio>
                    <?php endif;?>
    			</div>
    		    <?php ++$i;endforeach;?>
            </div>
		<?php endforeach;?>
		
		<div class="center">
			<?php if($this->game->getTimer() && $this->game->getTimerDuration() > 0):?>
	            <div class="timer">
	                <?php echo $this->game->getTimerDuration() * 100;?>
	            </div>
	        <?php endif;?>
        </div>
        
		<div class="text-center">
            <div class="btn btn-default btn-green previous">
                <a id="previous" href="#content-article">
                    <?php echo $this->translate('Previous questions'); ?>
                </a>
            </div>
            <div class="btn btn-default btn-green next">
                <a id="next" href="#content-article">
                    <?php echo $this->translate('Next questions'); ?>
                </a>
            </div>
	    </div>
	    <div class="text-center">
            <button type="submit" name="submitForm" value="" class="btn btn-default btn-green end">
                Valider mes réponses
            </button>
	    </div>
		<?php echo $this->form()->closeTag() ?>
        <div class="col-md-1"></div>
	</div>
</div>
<?php //else: ?>
   <?php //echo $this->formUser ?>
<?php //endif;?>

<?php //echo $this->formRegister ?>
<!-- END GAME QUIZ - FERME QUESTIONS-->
<script type="text/javascript">
    jQuery(document).ready(function ($)
    {
        $('#tabs').tab();
    });
</script>
