<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('frontend/zfcuser/ajaxlogin',array('channel' => $this->channel)));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'header-login');
?>
<div class="barnav row">
    <nav class="navbar navbar-default" role="navigation">
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li class="active up">
                    <a href="<?php echo $this->url('frontend', array('channel' => $this->channel)) ?>"<?php if($this->pageGames != ''): echo ' class="'.$this->pageGames.'"'; endif; ?>>Home</a>
                </li>
            </ul>
            <ul class="nav navbar-nav right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->translate('Me connecter'); ?> / <?php echo $this->translate('Créer un compte'); ?>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="dropdown">
                            <?php echo $this->form()->openTag($form) ?>
                            <div>
                                <div id="input-login" class="">
                                    <div class="input-login-error"></div>
                                    <?php echo $this->formInput($form->get('identity')) ?>
                                    <?php echo $this->formInput($form->get('credential')) ?>
                                    <?php if ($this->redirect): ?>
                                        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
                                    <?php endif ?>
                                </div>
                            </div>
                            <div class="txt-center" >
                                <a href="<?php echo $this->url('frontend/zfcuser/forgotpassword', array('channel' => $this->channel)) ?>">
                                    Mot de passe oublié ?
                                </a>
                                <?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
                                <?php echo $this->formButton($form->get('submit')) ?>
                                <?php if ($this->enableRegistration) : ?>
                                    <a class="btn-gray-dark" href="<?php echo $this->url('frontend/zfcuser/register', array('channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">
                                        Créer un compte
                                    </a>
                                    <div class="clearfix"></div>
                                    <a href="<?php echo $this->url('frontend/zfcuser/register',array('socialnetwork' => 'facebook', 'channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '');?>" class="fbconnect-header">
                                       <img src="<?php echo $this->frontendAssetPath('images/header/fb-connect.png') ?>" alt="Facebook Connect" />
                                    </a>
                                <?php endif; ?>
                            </div>
                            <?php echo $this->form()->closeTag() ?>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</div>